package com.seanora.fluentai.core.model

import kotlinx.serialization.Serializable

/**
 * Type of activity assigned within Today's Practice plan.
 */
@Serializable
enum class TodayItemType(val displayName: String) {
    REVIEW_DUE("Spaced Review"),
    MISTAKE_TARGETED("Targeted Mistake Remediation"),
    SPEAKING_SESSION("Speaking Practice"),
    CURRICULUM_NEW("Curriculum Step"),
    COMPREHENSION_READING("Reading Practice"),
    COMPREHENSION_LISTENING("Listening Practice"),
    WEAK_SKILL_BOOST("Skill Reinforcement")
}

/**
 * A discrete learning item scheduled within Today's Practice plan.
 * Each item carries a deterministic, human-readable [explanation] justifying its inclusion.
 */
@Serializable
data class TodayPlanItem(
    val id: String,
    val planId: String,
    val contentId: String,
    val title: String,
    val domain: String, // "vocabulary", "grammar", "reading", "listening", "speaking", "review"
    val itemType: TodayItemType,
    val estimatedMinutes: Int,
    val targetCefrLevel: String,
    val explanation: String,
    val isCompleted: Boolean = false,
    val completedAt: Long? = null,
    val orderIndex: Int = 0
)

/**
 * The complete daily plan generated by TodayPlanner for a specific calendar date.
 * Per AGENTS.md & PHASES.md:
 * - Local-first, deterministic, reproducible for a given user state.
 * - Explainable through [rationale] and per-item explanations.
 * - Balances due reviews, weak skills, recent mistakes, curriculum progression, and time budget.
 */
@Serializable
data class TodayPracticePlan(
    val id: String,
    val date: String, // YYYY-MM-DD
    val targetCefrLevel: String,
    val allocatedMinutes: Int,
    val rationale: String,
    val items: List<TodayPlanItem> = emptyList(),
    val createdAt: Long = System.currentTimeMillis()
) {
    val completedItemsCount: Int
        get() = items.count { it.isCompleted }

    val totalItemsCount: Int
        get() = items.size

    val totalMinutes: Int
        get() = items.sumOf { it.estimatedMinutes }

    val completedMinutes: Int
        get() = items.filter { it.isCompleted }.sumOf { it.estimatedMinutes }

    val isCompleted: Boolean
        get() = items.isNotEmpty() && items.all { it.isCompleted }

    val progressPercent: Float
        get() = if (items.isEmpty()) 0f else completedItemsCount.toFloat() / totalItemsCount.toFloat()

    val nextUncompletedItem: TodayPlanItem?
        get() = items.sortedBy { it.orderIndex }.firstOrNull { !it.isCompleted }
}

/**
 * Summary metrics of user's practice and review activity for the current day.
 */
@Serializable
data class DailyMetrics(
    val practiceMinutesToday: Int = 0,
    val reviewsClearedToday: Int = 0,
    val streakDays: Int = 0
)

