#!/usr/bin/env python3
"""
tools/curriculum_batch_001/expand_12_readings_to_1000_words.py

Deeply expands 12 target B2-C2 articles with 7-8 rich paragraphs each, ensuring every one of them
exceeds 1,000 words (> 1,000 words), while synchronizing exact word_count and estimated_reading_minutes
across all 50 reading articles.
"""

import os
import sys
from pathlib import Path
import yaml

project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(project_root))

# We define 7-8 full sections per article to ensure each reaches 1,020 - 1,150 words.
ARTICLES_DATA = {
    "reading.b2.continuous-integration-evolution": [
        ("The Genesis of Integration Friction",
         "In the early decades of enterprise software engineering, development teams worked in prolonged isolation for weeks or even months before attempting to combine their disparate code branches. This fragmented methodology culminated in what industry veterans grimly termed 'integration hell,' a protracted and agonizing project phase characterized by hundreds of conflicting file diffs, broken build artifacts, and endless finger-pointing among developers. The root cause of this operational friction was not poor craftsmanship, but rather the exponential growth of divergent state across multiple branches. When codebases drift apart over extended calendar periods, the cognitive burden of reconciling incompatible database schemas, altered method signatures, and competing business logic becomes staggering. Engineers would spend more time manually cherry-picking commits and fixing catastrophic merge conflicts than authoring new business value. Recognizing this massive drain on organizational velocity, pioneers in extreme programming began advocating for continuous integration: the discipline of merging all developer working copies to a shared mainline several times every day.",
         "Kurumsal yazılım mühendisliğinin ilk on yıllarında, geliştirme ekipleri farklı kod dallarını birleştirmeye çalışmadan önce haftalarca, hatta aylarca süren uzun bir izolasyon içinde çalışırdı. Bu parçalanmış metodoloji, sektör emektarlarının 'entegrasyon cehennemi' olarak adlandırdığı; yüzlerce çakışan dosya farkı, bozuk derleme çıktıları ve geliştiriciler arasında bitmek bilmeyen suçlamalarla karakterize edilen uzun ve acı verici bir proje aşamasıyla sonuçlanırdı. Bu operasyonel sürtüşmenin temel nedeni zayıf işçilik değil, birden fazla dal arasındaki ıraksak durumun katlanarak büyümesiydi. Kod tabanları uzun takvim dönemleri boyunca birbirinden uzaklaştığında, uyumsuz veritabanı şemalarını, değiştirilmiş metot imzalarını ve çelişen iş mantıklarını uzlaştırmanın bilişsel yükü ezici hale gelirdi. Mühendisler, yeni iş değeri üretmekten ziyade manuel olarak commit seçmek ve felaket düzeyindeki birleştirme çakışmalarını düzeltmek için daha fazla zaman harcardı. Organizasyonel hızdaki bu devasa kaybı fark eden çevik programlama öncüleri, sürekli entegrasyonu savunmaya başladı: tüm geliştirici çalışma kopyalarını her gün birkaç kez paylaşılan ana dala birleştirme disiplini."),
        ("Automated Build Servers as Objective Arbiter",
         "The mechanical foundation of continuous integration is an automated build server that continuously monitors the central source repository for new commits. The moment an engineer pushes a branch or opens a pull request, the CI pipeline triggers an isolated environment using containerized virtual runners. It checks out the latest code, resolves external dependencies, compiles the source artifacts, and executes an exhaustive suite of unit and integration tests. If even a single assertion fails, the entire build is marked as broken, and the authoring squad receives immediate telemetry via Slack or email. This strict gatekeeping mechanism enforces a fundamental cultural contract: no code that compromises trunk stability is allowed into the mainline. By detecting regressions within minutes of their introduction, teams slash the mean time to repair (MTTR) by orders of magnitude. The author still has the mental context fresh in mind, enabling rapid diagnosis and remediation rather than a forensic investigation weeks later.",
         "Sürekli entegrasyonun mekanik temeli, yeni commit'ler için merkezi kaynak deposunu sürekli olarak izleyen otomatik bir derleme sunucusudur. Bir mühendis bir dalı ittiği veya bir pull request açtığı anda, CI boru hattı konteynerleştirilmiş sanal çalıştırıcılar kullanarak izole bir ortamı tetikler. En son kodu çeker, harici bağımlılıkları çözer, kaynak çıktıları derler ve kapsamlı bir birim ve entegrasyon testi paketini yürütür. Tek bir doğrulama bile başarısız olursa, tüm derleme bozuk olarak işaretlenir ve yazar ekip Slack veya e-posta yoluyla anında telemetri alır. Bu katı denetim mekanizması temel bir kültürel sözleşmeyi dayatır: ana dal kararlılığını tehlikeye atan hiçbir kodun ana hatta girmesine izin verilmez. Regresyonları ortaya çıkışlarından dakikalar sonra tespit ederek ekipler, ortalama onarım süresini (MTTR) katbekat azaltır. Yazarın zihinsel bağlamı hala tazedir; bu da haftalar sonra adli bir soruşturma yürütmek yerine hızlı teşhis ve düzeltme sağlar."),
        ("The Testing Pyramid and Flaky Test Remediation",
         "A resilient continuous integration pipeline relies critically on a disciplined testing pyramid. At the broad base of the pyramid sit thousands of fast, deterministic unit tests that execute in mere milliseconds without external network or database I/O. The middle tier contains integration tests that verify contract boundaries between microservices, message brokers, and persistence layers. At the apex are end-to-end user journey tests running in headless browser environments. The primary enemy of continuous integration at scale is the flaky test—a test that intermittently passes and fails without any underlying code alterations. When engineers encounter inconsistent test results, they lose psychological trust in the pipeline, often re-running builds until they pass by sheer chance. High-performing engineering organizations maintain zero tolerance for flakiness, aggressively quarantining unstable tests until non-deterministic concurrency bugs or race conditions are permanently resolved.",
         "Dayanıklı bir sürekli entegrasyon boru hattı, kritik olarak disiplinli bir test piramidine dayanır. Piramidin geniş tabanında, harici ağ veya veritabanı I/O'su olmadan yalnızca milisaniyeler içinde çalışan binlerce hızlı, deterministik birim test yer alır. Orta katman, mikroservisler, mesaj aracıları ve kalıcılık katmanları arasındaki sözleşme sınırlarını doğrulayan entegrasyon testlerini içerir. Zirvede ise başlıksız tarayıcı ortamlarında çalışan uçtan uca kullanıcı yolculuğu testleri bulunur. Ölçekte sürekli entegrasyonun birincil düşmanı kararsız (flaky) testtir; altta yatan herhangi bir kod değişikliği olmaksızın aralıklı olarak başarılı olan ve başarısızlığa uğrayan bir test. Mühendisler tutarsız test sonuçlarıyla karşılaştıklarında, boru hattına olan psikolojik güvenlerini kaybeder ve genellikle derlemeleri tamamen tesadüfen geçene kadar tekrar tekrar çalıştırırlar. Yüksek performanslı mühendislik organizasyonları kararsızlığa karşı sıfır tolerans gösterir ve kararsız testleri deterministik olmayan eşzamanlılık hataları veya yarış koşulları kalıcı olarak çözülene kadar agresif bir şekilde karantinaya alır."),
        ("Branching Strategies: Trunk-Based Development versus GitFlow",
         "Continuous integration cannot function effectively in an organization that practices long-lived feature branching. Heavy branching workflows such as GitFlow encourage developers to hoard features on isolated branches for multiple sprints, re-creating the very integration delays that CI was designed to eliminate. Modern cloud-native engineering squads have decisively migrated toward Trunk-Based Development. In this paradigm, developers merge small, incremental pull requests directly into the trunk branch multiple times per day. Because incomplete features are continuously merged into production-bound branches, teams utilize feature flags (feature toggles) to decouple code deployment from feature release. Engineers can safely deploy dormant code behind a dynamic configuration flag, test the functionality in staging, and gradually expose the feature to internal employees before toggling it on for general market availability.",
         "Sürekli entegrasyon, uzun ömürlü özellik dallanması (feature branching) uygulayan bir organizasyonda etkili bir şekilde çalışamaz. GitFlow gibi ağır dallanma iş akışları, geliştiricileri özellikleri birden fazla sprint boyunca izole dallarda tutmaya teşvik ederek, CI'ın ortadan kaldırmak için tasarlandığı entegrasyon gecikmelerini yeniden üretir. Modern bulut tabanlı mühendislik ekipleri kararlı bir şekilde Ana Dal Temelli Geliştirmeye (Trunk-Based Development) geçiş yapmıştır. Bu paradigmada geliştiriciler, günde birden çok kez küçük, artımlı pull request'leri doğrudan ana dala birleştirirler. Tamamlanmamış özellikler üretime giden dallara sürekli olarak birleştirildiğinden, ekipler kod dağıtımını özellik sürümünden ayırmak için özellik bayraklarını (feature flags / feature toggles) kullanırlar. Mühendisler, uykudaki kodu dinamik bir yapılandırma bayrağının arkasına güvenle dağıtabilir, işlevselliği hazırlık ortamında test edebilir ve genel pazar erişimine açmadan önce özelliği dahili çalışanlara kademeli olarak sunabilirler."),
        ("Continuous Delivery: From Verified Code to Releasable Artifacts",
         "Once continuous integration stabilizes, technology organizations naturally progress toward continuous delivery (CD). While CI guarantees that code in trunk compiles and passes automated validation, continuous delivery ensures that the compiled artifact is in a releasable state at all times. Automated packaging steps generate immutable container images tagged with unique semantic commit hashes. These artifacts are signed with cryptographic certificates to guarantee provenance and stored in secure artifact registries. In mature continuous deployment pipelines, successful builds automatically progress through staging into production environments using canary releases and blue-green deployments. Rather than shifting entire user traffic simultaneously, canary ingress controllers direct five percent of requests to the new service version, monitoring error rates, HTTP 5xx responses, and P99 latency anomalies. If metrics deviate from baseline thresholds, automated circuit breakers instantly rollback the deployment before end users experience widespread service degradation.",
         "Sürekli entegrasyon kararlı hale geldiğinde, teknoloji organizasyonları doğal olarak sürekli teslimata (CD) doğru ilerler. CI, ana daldaki kodun derlendiğini ve otomatik doğrulamayı geçtiğini garanti ederken; sürekli teslimat, derlenen çıktının her zaman yayınlanabilir bir durumda olmasını sağlar. Otomatik paketleme adımları, benzersiz anlamsal commit karmalarıyla etiketlenmiş değişmez konteyner görüntüleri üretir. Bu çıktılar, kaynak doğruluğunu garanti etmek için kriptografik sertifikalarla imzalanır ve güvenli çıktı kayıt depolarında saklanır. Olgun sürekli dağıtım boru hatlarında, başarılı derlemeler kanarya sürümleri ve mavi-yeşil dağıtımlar kullanarak hazırlık ortamından üretim ortamlarına otomatik olarak ilerler. Tüm kullanıcı trafiğini aynı anda aktarmak yerine, kanarya giriş denetleyicileri isteklerin yüzde beşini yeni servis sürümüne yönlendirir; hata oranlarını, HTTP 5xx yanıtlarını ve P99 gecikme anomalilerini izler. Metrikler temel eşiklerden saparsa, otomatik devre kesiciler son kullanıcılar yaygın hizmet bozulması yaşamadan önce dağıtımı anında geri alır."),
        ("Security and Compliance in the Pipeline (DevSecOps)",
         "In modern high-consequence enterprise environments, continuous integration pipelines have expanded beyond functional testing to encompass automated security governance, a paradigm known as DevSecOps. Security cannot remain an afterthought conducted during manual quarterly audits. Modern CI pipelines embed static application security testing (SAST) tools that scan source code for SQL injection vulnerabilities and hardcoded secrets on every commit. Software composition analysis (SCA) scanners inspect third-party dependencies against open vulnerability databases, blocking builds that introduce critical CVEs. Dynamic application security testing (DAST) runs automated penetration attacks against ephemeral staging instances. By shifting security leftward into the automated developer loop, organizations achieve continuous compliance with stringent regulatory frameworks like SOC2 and ISO 27001 without introducing bureaucratic approval delays.",
         "Modern yüksek riskli kurumsal ortamlarda, sürekli entegrasyon boru hatları fonksiyonel testlerin ötesine geçerek DevSecOps olarak bilinen otomatik güvenlik yönetimini kapsayacak şekilde genişlemiştir. Güvenlik, manuel üç aylık denetimler sırasında yürütülen sonradan akla gelen bir düşünce olarak kalamaz. Modern CI boru hatları, her commit'te kaynak kodunu SQL enjeksiyonu açıkları ve sabit kodlanmış sırlar açısından tarayan statik uygulama güvenliği testi (SAST) araçlarını gömer. Yazılım bileşimi analizi (SCA) tarayıcıları, üçüncü taraf bağımlılıkları açık güvenlik açığı veritabanlarına karşı denetler ve kritik CVE'ler getiren derlemeleri engeller. Dinamik uygulama güvenliği testi (DAST), geçici hazırlık örneklerine karşı otomatik sızma saldırıları yürütür. Güvenliği otomatik geliştirici döngüsünün soluna kaydırarak (shift-left), kurumlar bürokratik onay gecikmeleri getirmeden SOC2 ve ISO 27001 gibi katı yasal çerçevelere sürekli uyum sağlar."),
        ("The Compounding Economics of High-Velocity Engineering",
         "Investing in continuous integration and deployment infrastructure yields compounding economic returns across the software lifecycle. According to comprehensive State of DevOps research, organizations with elite automated delivery pipelines deploy code hundreds of times more frequently, exhibit three times lower change failure rates, and recover from production incidents twenty-four times faster. Beyond pure operational resilience, the psychological impact on developer morale is profound. When engineers know that a comprehensive automated safety net guards every commit, they refactor legacy codebases with confidence, experiment with ambitious architectural paradigms, and deliver customer-requested features without existential dread. In modern technology enterprises, continuous integration is no longer a luxury toolchain; it is the fundamental operating system of competitive digital delivery.",
         "Sürekli entegrasyon ve dağıtım altyapısına yatırım yapmak, yazılım yaşam döngüsü boyunca katlanarak artan ekonomik getiriler sağlar. Kapsamlı State of DevOps araştırmasına göre, seçkin otomatik teslimat boru hatlarına sahip organizasyonlar kodu yüzlerce kat daha sık dağıtır, üç kat daha düşük değişiklik hata oranı sergiler ve üretim olaylarından yirmi dört kat daha hızlı toparlanır. Saf operasyonel dayanıklılığın ötesinde, geliştirici morali üzerindeki psikolojik etki de derindir. Mühendisler kapsamlı bir otomatik güvenlik ağının her commit'i koruduğunu bildiklerinde, eski kod tabanlarını güvenle yeniden yapılandırır, iddialı mimari paradigmaları dener ve varoluşsal bir korku duymadan müşterilerin talep ettiği özellikleri sunarlar. Modern teknoloji işletmelerinde sürekli entegrasyon artık lüks bir araç zinciri değil; rekabetçi dijital teslimatın temel işletim sistemidir.")
    ]
}

# We can dynamically generate 7 balanced, rich paragraphs for all 12 articles.
# Let's write a python function to inject them and run calibration.
print("Script template ready.")
