#!/usr/bin/env python3
"""
Comprehensive Exercise Generator for B2 Grammar.
Generates exactly 20 exercises for each of the 10 B2 grammar lessons = 200 exercises.
"""
from mcq_balancer import McqBalancer

balancer = McqBalancer(seed=703)

def make_ex(ex_id, target_id, level, prompt_en, prompt_tr, stem, correct, distractors, exp_en, exp_tr, dist_exps, diff="standard"):
    options, idx = balancer.balance_options(correct, distractors)
    return {
        "id": ex_id,
        "target_content_id": target_id,
        "cefr_level": level,
        "skill_domain": "grammar",
        "exercise_type": "multiple_choice",
        "prompt_en": prompt_en,
        "prompt_tr_hint": prompt_tr,
        "stem": stem,
        "options": options,
        "correct_answer": correct,
        "explanation_en": exp_en,
        "explanation_tr": exp_tr,
        "distractor_explanations": dist_exps,
        "difficulty": diff,
        "status": "APPROVED",
        "version": 1
    }

B2_EXERCISES = []

def add_lesson(lesson_id, short_id, items, prompt_en, prompt_tr):
    for i, data in enumerate(items, 1):
        stem, corr, dists, en_exp, tr_exp, d_exps = data
        B2_EXERCISES.append(make_ex(f"exercise.b2.{short_id}-{i:02d}", lesson_id, "B2",
                                    prompt_en, prompt_tr, stem, corr, dists, en_exp, tr_exp, d_exps))

# grammar.b2.third-mixed-conditionals
add_lesson("grammar.b2.third-mixed-conditionals", "third-mixed-cond", [
    ('If our DevOps team had configured redundancy, the outage ___ our customers today.', 'would not be affecting', ['would not have affected', 'will not affect', 'did not affect'],
     "Mixed conditional: past condition ('had configured') with a present result ('today').", "Mixed Conditional: Geçmişteki eylemin ('had configured') günümüzdeki sonucunu ('today') anlatırken 'would not be affecting' kullanılır.",
     {'would not have affected': "Third Conditional geçmişteki sonucu anlatır, 'today' ile uyumsuzdur.", 'will not affect': 'First conditional gelecek zaman kipidir.', 'did not affect': 'Geçmiş zaman kipidir.'}),
    ("If they ___ the security vulnerability earlier, the data breach wouldn't have occurred.", 'had discovered', ['discovered', 'would discover', 'would have discovered'],
     "Third conditional 'if' clause requires Past Perfect ('had + V3').", "Üçüncü tip şart cümlesinin 'if' tarafı Past Perfect ('had discovered') gerektirir.",
     {'discovered': 'Second conditional kipi geçmişteki olayı karşılamaz.', 'would discover': "'If' cümleciğinde 'would' kullanılmaz.", 'would have discovered': "'Would have' 'if' cümleciğinde yer alamaz."}),
    ('We would have won the government contract if our bid ___ 10% lower.', 'had been', ['was', 'were', 'would be'],
     'Third conditional expressing past hypothetical outcome.', 'Teklifimiz %10 daha düşük olsaydı ihaleyi kazanırdık (geçmiş şart: had been).',
     {'was': "Gayriresmi Second Conditional kipi ana cümledeki 'would have won' ile uyumsuzdur.", 'were': 'Second conditional kipidir.', 'would be': "'If' içine 'would' girmez."}),
    ('If I had accepted that job in Zurich, I ___ living in Switzerland right now.', 'would be', ['would have been', 'will be', 'am'],
     "Mixed conditional: past action affecting present residency ('right now').", "Zürih'teki işi kabul etmiş olsaydım şu an İsviçre'de yaşıyor olurdum (Mixed Conditional: would be).",
     {'would have been': "Geçmişteki durumu anlatır, 'right now' ile çelişir.", 'will be': 'Gelecek zamandır.', 'am': 'Gerçekliği ifade eder, varsayımı değil.'}),
    ('Had the board of directors ___ informed sooner, the crisis could have been mitigated.', 'been', ['had been', 'were', 'being'],
     "Inverted third conditional structure: 'Had + subject + past participle'.", "Devrik üçüncü tip şart cümlesinde 'Had the board... been' yapısı kullanılır.",
     {'had been': "'Had' cümlenin başına geçtiği için tekrar 'had' yazılamaz.", 'were': 'Devrik Second Conditional kipidir.', 'being': 'Continuous ortaçtır.'}),
    ("If she hadn't missed the connecting flight, she ___ here with us for the kickoff.", 'would be', ['would have been', 'will be', 'is'],
     'Mixed conditional linking past flight delay to current absence.', 'Aktarmayı kaçırmamış olsaydı şu an açılış toplantısında bizimle olurdu.',
     {'would have been': 'Geçmişteki anı ifade eder, şu anki durumu vermez.', 'will be': 'Gelecek zamandır.', 'is': 'Gerçekliği bildirir.'}),
    ('The project ___ on schedule if the vendor had delivered the API tokens on time.', 'would have remained', ['remained', 'would remain', 'will remain'],
     "Third conditional main clause: 'would have + past participle'.", 'Tedarikçi tokenları zamanında verseydi proje takvimde kalırdı.',
     {'remained': 'Past Simple kipi şart yapısını kuramaz.', 'would remain': 'Second Conditional bugünkü durumu ifade eder.', 'will remain': 'First Conditional kipidir.'}),
    ("If you ___ more attention during onboarding, you wouldn't be asking basic questions now.", 'had paid', ['paid', 'would pay', 'would have paid'],
     'Mixed conditional: past inattention resulting in present confusion.', 'İşe alışma sürecinde dikkat etseydin şimdi temel sorular sormazdın.',
     {'paid': 'Second conditional kipi geçmişteki süreci tam vermez.', 'would pay': "'If' cümleciğinde 'would' kullanılmaz.", 'would have paid': "'Would have' 'if' içine girmez."}),
    ("Had we ___ the warning signs, we wouldn't have invested in that volatile venture.", 'heeded', ['heed', 'heeding', 'been heeded'],
     'Inverted conditional with transitive active verb.', 'Uyarı işaretlerini dikkate almış olsaydık o riskli girişime yatırım yapmazdık.',
     {'heed': "Yalın fiil 'had' ardına gelemez.", 'heeding': 'Continuous form devrik şart yapısına uymaz.', 'been heeded': 'Edilgen anlam taşır, etken özneye uymaz.'}),
    ("If the lead architect hadn't resigned, we ___ much further ahead today.", 'would be', ['would have been', 'had been', 'were'],
     "Mixed conditional: past resignation impacting today's standing.", 'Baş mimar istifa etmemiş olsaydı bugün çok daha ileride olurduk.',
     {'would have been': "Geçmişte kalmış durumu anlatır, 'today' ile uyumsuzdur.", 'had been': "Ana cümlede tek başına 'had been' şart sonucu bildirmez.", 'were': 'Second conditional ana cümlesi olamaz.'}),
    ('If the team had tested the patch in staging, it ___ production databases.', 'would not have corrupted', ['would not corrupt', 'will not corrupt', 'did not corrupt'],
     'Third conditional: completed past consequence of past oversight.', 'Yama staging ortamında test edilseydi canlı veri tabanını bozmazdı.',
     {'would not corrupt': 'Şu anki sonucu anlatır.', 'will not corrupt': 'Gelecek zamandır.', 'did not corrupt': 'Past Simple kipi şart yapısını kuramaz.'}),
    ('Had I known about the schedule conflict, I ___ the interview.', 'would have rescheduled', ['rescheduled', 'would reschedule', 'will reschedule'],
     'Inverted third conditional with past result.', 'Takvim çakışmasını bilseydim mülakatı ertelerdim.',
     {'rescheduled': "Şart sonucu için 'would have' gereklidir.", 'would reschedule': 'Bugünkü ertelemeyi ifade eder.', 'will reschedule': 'Gelecek zamandır.'}),
    ('If he ___ fluent in German, he would have applied for the Berlin relocation.', 'were', ['had been', 'is', 'will be'],
     "Mixed conditional: enduring present trait ('were fluent') causing a past missed opportunity.", 'Almancası akıcı olsaydı (genel durum) Berlin transferine başvururdu (geçmiş fırsat).',
     {'had been': 'Geçmişte akıcı olup artık olmadığını ima eder.', 'is': 'Gerçekliği bildirir.', 'will be': 'Gelecek zamandır.'}),
    ('The investor ___ us a term sheet if our revenue model had been clearer.', 'would have offered', ['offered', 'would offer', 'will offer'],
     'Third conditional standard main clause.', 'Gelir modelimiz daha net olsaydı yatırımcı bize teklif sunardı.',
     {'offered': 'Past Simple şart yapısını vermez.', 'would offer': 'Bugünkü teklifi ima eder.', 'will offer': 'Gelecek zamandır.'}),
    ("If they hadn't implemented caching, the servers ___ under the Black Friday load.", 'would have crashed', ['crashed', 'would crash', 'will crash'],
     'Third conditional past counterfactual.', 'Önbellekleme yapmasalardı sunucular çöküş yaşardı.',
     {'crashed': 'Geçmişte çöktüğünü söyler.', 'would crash': 'Bugünkü durumu anlatır.', 'will crash': 'Gelecektir.'}),
    ('Had the legal team ___ the contract clauses, this dispute could have been avoided.', 'examined', ['examine', 'examining', 'been examined'],
     'Inverted conditional with active past participle.', 'Hukuk ekibi maddeleri incelemiş olsaydı bu uyuşmazlık önlenebilirdi.',
     {'examine': 'Yalın fiildir.', 'examining': 'Ulaçtır.', 'been examined': 'Edilgendir, etken hukuk ekibine uymaz.'}),
    ("If she hadn't spent five years in Tokyo, she ___ Japanese so well today.", 'would not speak', ['would not have spoken', 'did not speak', 'will not speak'],
     'Mixed conditional: past experience creating current language competence.', "Tokyo'da 5 yıl geçirmemiş olsaydı bugün bu kadar iyi Japonca konuşamazdı.",
     {'would not have spoken': "Geçmişteki konuşmayı ifade eder, 'today' ile uyumsuzdur.", 'did not speak': 'Geçmiş zamandır.', 'will not speak': 'Gelecektir.'}),
    ("If the driver ___ the speed limit, the crash wouldn't have occurred.", 'had respected', ['respected', 'respects', 'would respect'],
     "Third conditional 'if' clause.", 'Sürücü hız sınırına uymuş olsaydı kaza meydana gelmezdi.',
     {'respected': 'Second conditional kipi geçmiş kazaya uymaz.', 'respects': 'Geniş zamandır.', 'would respect': "'If' içine 'would' girmez."}),
    ("We ___ the quarterly target if the major client hadn't churned.", 'would have achieved', ['achieved', 'would achieve', 'will achieve'],
     'Third conditional result.', 'Büyük müşteri ayrılmasaydı çeyreklik hedefi tuttururduk.',
     {'achieved': 'Tutturduğumuzu söyler.', 'would achieve': 'Bugünkü durumu anlatır.', 'will achieve': 'Gelecektir.'}),
    ('Had the system architect ___ the failover mechanism, the data loss would have been zero.', 'tested', ['test', 'testing', 'been tested'],
     'Inverted third conditional.', 'Sistem mimarı yük devretme mekanizmasını test etmiş olsaydı veri kaybı sıfır olurdu.',
     {'test': 'Yalın fiildir.', 'testing': 'Ulaçtır.', 'been tested': 'Edilgendir.'}),
], 'Choose the correct verb form for third or mixed conditionals:', 'Geçmişteki varsayımlar (Third Conditional) veya geçmişin şu ana etkileri (Mixed Conditional) için doğru kipi seçiniz.')

# grammar.b2.past-modal-deduction
add_lesson("grammar.b2.past-modal-deduction", "past-mod-deduct", [
    ('The database server was completely unresponsive; someone ___ pulled the power cord.', 'must have', ["can't have", 'should have', 'might not have'],
     "'Must have + V3' expresses near certainty about a past event based on strong evidence.", "Geçmişe yönelik güçlü çıkarım: Sunucu tamamen kapandıysa biri fişi çekmiş olmalıdır ('must have').",
     {"can't have": 'İmkansızlık bildirir, mevcut duruma uymaz.', 'should have': 'Tavsiye veya gereklilik bildirir.', 'might not have': 'Zayıf olumsuz ihtimaldir.'}),
    ('He only joined the firm yesterday; he ___ authorized that million-dollar wire transfer.', "can't have", ['must have', 'should have', 'might have'],
     "'Can't have + V3' expresses logical impossibility regarding past actions.", "Dün işe başlayan birinin milyon dolarlık transferi onaylamış olması mantıksal olarak imkansızdır ('can't have').",
     {'must have': 'Kesinlikle onaylamıştır anlamına gelir ki durumla çelişir.', 'should have': 'Onaylamalıydı anlamına gelir.', 'might have': 'Onaylamış olabilir anlamına gelir.'}),
    ("The delivery truck hasn't arrived; it ___ been delayed by the severe snowfall on the mountain pass.", 'might have', ["can't have", "mustn't have", "shouldn't have"],
     "'Might have + V3' suggests a plausible past reason for an ongoing delay.", "Kamyon gelmediyse dağdaki yoğun kardan gecikmiş olabilir ('might have').",
     {"can't have": 'Gecikmiş olamaz anlamına gelir.', "mustn't have": "İngilizcede geçmiş çıkarımda 'mustn't have' kullanılmaz.", "shouldn't have": 'Gecikmemeliydi anlamına gelir.'}),
    ('All thirty test cases passed flawlessly; the developer ___ spent hours debugging the code.', 'must have', ["couldn't have", 'might not have', 'should have'],
     'Positive certainty from observed perfection.', 'Otuz testin hepsi hatasız geçtiyse yazılımcı saatlerce kod ayıklamış olmalıdır.',
     {"couldn't have": 'Vakit harcamış olamaz anlamına gelir.', 'might not have': 'Harcamamış olabilir anlamına gelir.', 'should have': 'Harcamalıydı anlamına gelir.'}),
    ('She was in a transatlantic flight at that hour; she ___ sent that email.', "couldn't have", ['must have', 'might have', 'should have'],
     'Logical impossibility in the past.', "O saatte uçakta olan biri o e-postayı göndermiş olamaz ('couldn't have').",
     {'must have': 'Kesinlikle göndermiştir anlamına gelir.', 'might have': 'Göndermiş olabilir anlamına gelir.', 'should have': 'Göndermeliydi anlamına gelir.'}),
    ("I can't locate my badge; I ___ left it on the cafeteria table.", 'could have', ["can't have", "mustn't have", 'should have'],
     'Plausible past location of an accidentally left item.', "Kartımı bulamıyorsam kafeteryada bırakmış olabilirim ('could have').",
     {"can't have": 'Bırakmış olamam anlamına gelir.', "mustn't have": 'Geçmiş çıkarımda kullanılmaz.', 'should have': 'Bırakmalıydım anlamına gelir.'}),
    ('The package was delivered in pristine packaging; it ___ dropped during transit.', "can't have been", ['must have been', 'should have been', 'could have been'],
     'Deduction of impossibility for passive past event.', "Paket kusursuz teslim edildiyse yolda düşürülmüş olamaz ('can't have been').",
     {'must have been': 'Kesinlikle düşürülmüştür anlamına gelir.', 'should have been': 'Düşürülmeliydi anlamına gelir.', 'could have been': 'Düşürülmüş olabilir anlamına gelir.'}),
    ('The startup grew 500% in one year; the founders ___ worked around the clock.', 'must have', ["can't have", 'might not have', 'should have'],
     'Deduction explaining extraordinary business growth.', 'Bir yılda %500 büyüdülerse kurucular gece gündüz çalışmış olmalıdır.',
     {"can't have": 'Çalışmış olamazlar anlamına gelir.', 'might not have': 'Çalışmamış olabilirler anlamına gelir.', 'should have': 'Çalışmalıydılar anlamına gelir.'}),
    ('Nobody heard the security siren; the wiring ___ disconnected by the intruders.', 'must have been', ["can't have been", 'might not have been', 'should have been'],
     'Passive deduction explaining a silent alarm.', 'Kimse sireni duymadıysa kablolar içeri girenler tarafından kesilmiş olmalıdır.',
     {"can't have been": 'Kesilmiş olamaz anlamına gelir.', 'might not have been': 'Kesilmemiş olabilir anlamına gelir.', 'should have been': 'Kesilmeliydi anlamına gelir.'}),
    ('He looks completely refreshed; he ___ stayed up late gaming.', "can't have", ['must have', 'could have', 'should have'],
     'Impossibility deduced from fresh appearance.', 'Tamamen dinç görünüyorsa geç saatlere kadar oyun oynamış olamaz.',
     {'must have': 'Kesinlikle oynamıştır anlamına gelir.', 'could have': 'Oynamış olabilir anlamına gelir.', 'should have': 'Oynamalıydı anlamına gelir.'}),
    ('The payment cleared instantly; they ___ used a real-time settlement gateway.', 'must have', ["couldn't have", 'might not have', 'should have'],
     'High probability explaining instantaneous transaction.', 'Ödeme anında onaylandıysa gerçek zamanlı ödeme altyapısı kullanmış olmalıdırlar.',
     {"couldn't have": 'Kullanmış olamazlar anlamına gelir.', 'might not have': 'Kullanmamış olabilirler anlamına gelir.', 'should have': 'Kullanmalıydılar anlamına gelir.'}),
    ("I didn't receive the calendar invitation; you ___ typed my email address incorrectly.", 'might have', ["can't have", "mustn't have", 'should have'],
     'Polite past deduction suggesting a possible mistake.', "Davetiye gelmediyse e-posta adresimi yanlış yazmış olabilirsiniz ('might have').",
     {"can't have": 'Yanlış yazmış olamazsınız anlamına gelir.', "mustn't have": 'Hatalı yapıdır.', 'should have': 'Yanlış yazmalıydınız anlamına gelir.'}),
    ('The road is bone dry; it ___ rained heavily last night.', "can't have", ['must have', 'could have', 'might have'],
     'Physical impossibility deduced from dry ground.', 'Yol kupkuruysa dün gece sağanak yağmış olamaz.',
     {'must have': 'Kesinlikle yağmıştır anlamına gelir.', 'could have': 'Yağmış olabilir anlamına gelir.', 'might have': 'Yağmış olabilir anlamına gelir.'}),
    ('She scored 100% on the C2 exam; she ___ prepared meticulously.', 'must have', ["can't have", 'might not have', 'should have'],
     'Deduction explaining academic perfection.', 'C2 sınavından tam puan aldıysa titizlikle hazırlanmış olmalıdır.',
     {"can't have": 'Hazırlanmış olamaz anlamına gelir.', 'might not have': 'Hazırlanmamış olabilir anlamına gelir.', 'should have': 'Hazırlanmalıydı anlamına gelir.'}),
    ('The office was completely spotless this morning; the cleaners ___ spent hours on it.', 'must have', ["can't have", 'might not have', 'should have'],
     'Deduction explaining extreme cleanliness.', 'Ofis tertemizse temizlikçiler saatlerce uğraşmış olmalıdır.',
     {"can't have": 'Uğraşmış olamazlar anlamına gelir.', 'might not have': 'Uğraşmamış olabilirler anlamına gelir.', 'should have': 'Uğraşmalıydılar anlamına gelir.'}),
    ("He didn't recognize his former manager; he ___ forgotten his face after twenty years.", 'might have', ["can't have", "mustn't have", "shouldn't have"],
     'Plausible explanation for not recognizing someone.', 'Eski müdürünü tanıyamadıysa 20 yıl sonra yüzünü unutmuş olabilir.',
     {"can't have": 'Unutmuş olamaz anlamına gelir.', "mustn't have": 'Hatalı yapıdır.', "shouldn't have": 'Unutmamalıydı anlamına gelir.'}),
    ('The encryption key was 256 bits long; they ___ cracked it by brute force in ten seconds.', "couldn't have", ['must have', 'should have', 'might have'],
     'Technical mathematical impossibility.', "Anahtar 256 bit ise 10 saniyede kaba kuvvetle kırmış olamazlar ('couldn't have').",
     {'must have': 'Kesinlikle kırmışlardır anlamına gelir.', 'should have': 'Kırmalıydılar anlamına gelir.', 'might have': 'Kırmış olabilirler anlamına gelir.'}),
    ('The coffee machine was still warm at 7 AM; someone ___ arrived very early.', 'must have', ["can't have", 'might not have', 'should have'],
     'Deduction from physical warmth.', 'Kahve makinesi hala sıcaksa biri çok erken gelmiş olmalıdır.',
     {"can't have": 'Gelmiş olamaz anlamına gelir.', 'might not have': 'Gelmemiş olabilir anlamına gelir.', 'should have': 'Gelmeliydi anlamına gelir.'}),
    ('The missing files were backed up on cloud storage; we ___ panicked so much.', "needn't have", ['must have', "can't have", 'might have'],
     "'Needn't have + V3' expresses an action that was performed unnecessarily.", "Dosyalar bulutta yedekliymiş; bu kadar paniklememize hiç gerek yokmuş ('needn't have').",
     {'must have': 'Paniklemiş olmalıyız anlamına gelir.', "can't have": 'Paniklemiş olamayız anlamına gelir.', 'might have': 'Paniklemiş olabiliriz anlamına gelir.'}),
    ('She looked puzzled during the lecture; she ___ understood the complex economic theory.', "can't have", ['must have', 'could have', 'might have'],
     'Deduction from puzzled expression.', 'Ders boyunca kafası karışık baktıysa karmaşık teoriyi anlamış olamaz.',
     {'must have': 'Kesinlikle anlamıştır anlamına gelir.', 'could have': 'Anlamış olabilir anlamına gelir.', 'might have': 'Anlamış olabilir anlamına gelir.'}),
], "Choose the correct past modal of deduction (must have, can't have, might/could have):", "Geçmişe yönelik mantıksal çıkarım kiplerini (must have, can't have, might/could have) doğru seçiniz.")

# grammar.b2.passive-voice-formal
add_lesson("grammar.b2.passive-voice-formal", "passive-formal", [
    ('The confidential strategic roadmap ___ by the executive board tomorrow morning.', 'is to be reviewed', ['is reviewing', 'reviews', 'has reviewed'],
     "Formal structure 'be to be + past participle' denotes official planned schedule.", "Resmi protokol ve planlarda 'is to be reviewed' (incelenecektir) kalıbı kullanılır.",
     {'is reviewing': 'Yol haritasının inceleme yapacağını söyler.', 'reviews': 'Geniş zamandır.', 'has reviewed': 'Etken geçmiş zamandır.'}),
    ('All prospective suppliers are required ___ proof of ISO certification.', 'to submit', ['submitting', 'submit', 'submitted'],
     "Passive verb followed by infinitive: 'are required to + base verb'.", "'Be required to' kalıbından sonra mastar ('to submit') gelir.",
     {'submitting': "'Required' ardından gerund almaz.", 'submit': "'To' eksiktir.", 'submitted': 'Geçmiş zaman kipi gelemez.'}),
    ('The financial discrepancies ___ by external auditors last month.', 'were investigated', ['investigated', 'have been investigated', 'are investigated'],
     'Past formal passive with specific past time marker.', 'Mali tutarsızlıklar geçen ay bağımsız denetçiler tarafından soruşturuldu.',
     {'investigated': 'Tutarsızlıkların soruşturma yaptığını ima eder.', 'have been investigated': "Present Perfect 'last month' ile kullanılamaz.", 'are investigated': 'Geniş zamandır.'}),
    ('Measures must ___ to prevent further unauthorized database access.', 'be implemented', ['implement', 'be implementing', 'have implemented'],
     "Modal passive: 'must be + past participle'.", 'Yetkisiz veri tabanı erişimini engellemek için önlemler uygulanmalıdır.',
     {'implement': 'Önlemlerin uygulama yapacağını söyler.', 'be implementing': 'Önlemlerin uygulamakta olduğunu söyler.', 'have implemented': 'Önlemler uygulamıştır anlamına gelir.'}),
    ('The new compliance regulations are understood ___ into effect on July 1st.', 'to come', ['coming', 'come', 'came'],
     "Formal reporting passive: 'are understood to + infinitive'.", "Yeni uyumluluk kurallarının 1 Temmuz'da yürürlüğe gireceği anlaşılmaktadır.",
     {'coming': 'Gerund yapısı bu raporlama kalıbına uymaz.', 'come': "'To' eksiktir.", 'came': 'Geçmiş zaman kipi gelemez.'}),
    ('No employee shall ___ access to personal customer records without authorization.', 'be granted', ['grant', 'be granting', 'have granted'],
     "Formal legal passive with modal 'shall'.", 'Hiçbir çalışana yetkisiz müşteri kayıtlarına erişim hakkı tanınmayacaktır.',
     {'grant': 'Çalışanın hak tanıyacağını söyler.', 'be granting': 'Çalışan hak tanımaktadır anlamına gelir.', 'have granted': 'Etken zamandır.'}),
    ('The software patch ___ across all production servers overnight.', 'was deployed', ['deployed', 'was deploying', 'has deployed'],
     'Formal operational passive.', 'Yazılım yaması gece boyunca tüm sunuculara dağıtıldı/yüklendi.',
     {'deployed': 'Yamanın dağıtım yaptığını ima eder.', 'was deploying': 'Yamanın dağıtmakta olduğunu söyler.', 'has deployed': 'Etken tamamlanmış zamandır.'}),
    ('Applications submitted after the midnight deadline will not ___ .', 'be considered', ['consider', 'be considering', 'have considered'],
     'Future formal passive rejection notice.', 'Gece yarısından sonra iletilen başvurular dikkate alınmayacaktır.',
     {'consider': 'Başvuruların dikkate alacağını söyler.', 'be considering': 'Başvuruların değerlendirmekte olduğunu söyler.', 'have considered': 'Etken zamandır.'}),
    ('The infrastructure is designed ___ high-volume transactional spikes.', 'to withstand', ['withstanding', 'withstand', 'withstood'],
     'Passive + infinitive indicating design purpose.', 'Altyapı yoğun işlem artışlarına dayanacak şekilde tasarlanmıştır.',
     {'withstanding': "Tasarım amacında 'to + infinitive' kullanılır.", 'withstand': "'To' eksiktir.", 'withstood': 'Geçmiş zaman kipi gelemez.'}),
    ('The keynote speaker was invited ___ at the global sustainability forum.', 'to address', ['addressing', 'address', 'addressed'],
     'Passive + infinitive structure.', 'Ana konuşmacı küresel foruma hitap etmek üzere davet edildi.',
     {'addressing': "'Invite' ardından mastar alır.", 'address': "'To' eksiktir.", 'addressed': 'Geçmiş zaman kipi gelemez.'}),
    ('Submissions must ___ in PDF format via the online portal.', 'be provided', ['provide', 'be providing', 'have provided'],
     'Institutional submission requirement.', 'Başvurular online portal üzerinden PDF formatında sunulmalıdır.',
     {'provide': 'Başvuruların sunum yapacağını söyler.', 'be providing': 'Başvurular sunmaktadır anlamına gelir.', 'have provided': 'Etken tamamlanmış zamandır.'}),
    ('The breach ___ to have originated from a phishing email.', 'is believed', ['believes', 'is believing', 'believed'],
     'Impersonal passive reporting origin.', 'İhlalin bir oltalama e-postasından kaynaklandığına inanılmaktadır.',
     {'believes': 'İhlalin inandığını söyler.', 'is believing': "'Believe' durum fiilidir.", 'believed': 'Geçmişte inanıldı bitti anlamı verir.'}),
    ('All visitors are expected ___ identification upon entry.', 'to present', ['presenting', 'present', 'presented'],
     'Institutional expectation rule.', 'Tüm ziyaretçilerin girişte kimlik göstermeleri beklenmektedir.',
     {'presenting': "'Expected' mastar alır.", 'present': "'To' eksiktir.", 'presented': 'Geçmiş zaman kipi gelemez.'}),
    ('The contract ___ by both legal counsels before signing.', 'was vetted', ['vetted', 'vets', 'was vetting'],
     'Formal legal review passive.', 'Sözleşme imzalanmadan önce her iki tarafın hukuk müşavirlerince incelendi.',
     {'vetted': 'Sözleşmenin inceleme yaptığını söyler.', 'vets': 'Geniş zamandır.', 'was vetting': 'Sözleşmenin incelemekte olduğunu söyler.'}),
    ('Any discrepancies should ___ immediately to compliance officers.', 'be reported', ['report', 'be reporting', 'have reported'],
     'Corporate compliance directive.', 'Her türlü tutarsızlık derhal uyum görevlilerine bildirilmelidir.',
     {'report': 'Tutarsızlıkların bildirim yapacağını söyler.', 'be reporting': 'Tutarsızlıklar bildirmektedir anlamına gelir.', 'have reported': 'Etken zamandır.'}),
    ('The proposal ___ as unviable during the preliminary assessment.', 'was dismissed', ['dismissed', 'dismisses', 'was dismissing'],
     'Formal rejection passive.', 'Teklif ön değerlendirme sırasında uygulanamaz bulunarak reddedildi.',
     {'dismissed': 'Teklifin bir şeyi reddettiğini ima eder.', 'dismisses': 'Geniş zamandır.', 'was dismissing': 'Teklifin reddetmekte olduğunu söyler.'}),
    ("Staff members are reminded ___ the clean-desk policy at day's end.", 'to observe', ['observing', 'observe', 'observed'],
     'Passive reminder + infinitive.', 'Personel gün sonunda temiz masa politikasına uymaları konusunda uyarılmaktadır.',
     {'observing': "'Remind' mastar alır.", 'observe': "'To' eksiktir.", 'observed': 'Geçmiş zaman kipi gelemez.'}),
    ('The transaction ___ flagged for suspected money laundering.', 'was', ['has', 'did', 'had'],
     "Passive auxiliary 'was' + past participle.", 'İşlem şüpheli kara para aklama nedeniyle işaretlendi.',
     {'has': 'Etken zamandır.', 'did': 'Soru veya vurgu yardımcı fiilidir.', 'had': 'Past Perfect etken zamandır.'}),
    ("Candidates will ___ notified of the committee's decision by Friday.", 'be', ['been', 'have', 'being'],
     "Future passive auxiliary 'will be'.", 'Adaylar komite kararından cuma gününe kadar haberdar edilecektir.',
     {'been': "'Will' ardına 'been' gelemez.", 'have': 'Etken anlam oluşturur.', 'being': "'Will' ardına 'being' gelemez."}),
    ('The report is said ___ several controversial recommendations.', 'to contain', ['containing', 'contain', 'contained'],
     'Reporting passive with infinitive.', 'Raporun tartışmalı birkaç öneri içerdiği söylenmektedir.',
     {'containing': 'Raporlama kalıbında mastar kullanılır.', 'contain': "'To' eksiktir.", 'contained': 'Geçmiş zaman kipi gelemez.'}),
], 'Choose the correct formal passive construction:', 'Resmi ve kurumsal yazışmalarda kullanılan ileri düzey edilgen çatı yapılarını seçiniz.')

# grammar.b2.reporting-passives-impersonal
add_lesson("grammar.b2.reporting-passives-impersonal", "rep-passive-impers", [
    ('___ that the central bank will raise interest rates next month.', 'It is expected', ['He is expected', 'There expects', 'Is expected'],
     "'It + passive verb + that clause' is the standard impersonal reporting pattern.", "'It is expected that...' (Beklenmektedir ki...) kalıbı kişisel olmayan resmi aktarımların standart yapısıdır.",
     {'He is expected': "Özne banka kararı olduğu için 'he' uygunsuzdur.", 'There expects': "'There' etken fiille beklenti kuramaz.", 'Is expected': 'Cümlede özne eksiktir.'}),
    ('The CEO is rumored ___ stepping down at the end of the fiscal year.', 'to be', ['that he is', 'being', 'is'],
     "'Subject + passive reporting verb + to-infinitive' pattern.", "Kişisel aktarım kalıbında öznenin ardından mastar gelir: 'The CEO is rumored to be...'",
     {'that he is': "'The CEO' özne olarak öne çıktığı için 'that' cümlesi tekrar kurulamaz.", 'being': 'Gerund yapısı bu aktarıma uymaz.', 'is': 'Çift çekimli fiil hatası yaratır.'}),
    ('___ believed that the ancient settlement dates back to the Bronze Age.', 'It is', ['He is', 'There is', 'That is'],
     "Impersonal passive introductory dummy subject 'It is'.", "'It is believed that...' kalıbı.",
     {'He is': 'Tarihi yerleşim için kişi zamiri kullanılamaz.', 'There is': "'There is believed' yanlış dizilimdir.", 'That is': "Giriş öznesi 'it' olmalıdır."}),
    ('The new semiconductor architecture is reported ___ performance by 40%.', 'to boost', ['boosting', 'boosts', 'that boosts'],
     'Passive reporting followed by infinitive.', "Yeni mimarinin performansı %40 artırdığı bildirilmektedir ('is reported to boost').",
     {'boosting': 'Raporlama yapısında ulaç kullanılmaz.', 'boosts': 'Çift çekimli fiil hatasıdır.', 'that boosts': 'Bağlaç yapısı bozar.'}),
    ('___ widely acknowledged that renewable energy reduces long-term carbon emissions.', 'It is', ['There is', 'This is', 'He is'],
     'Impersonal introductory passive.', "Yenilenebilir enerjinin emisyonları azalttığı genel kabul görmektedir ('It is widely acknowledged that...').",
     {'There is': 'Var olmak anlamı katar.', 'This is': "Resmi impersonal yapıda 'it' kullanılır.", 'He is': 'Kişi zamiridir.'}),
    ('The missing manuscript is thought ___ destroyed during the fire in 1845.', 'to have been', ['to be', 'being', 'having been'],
     "Reporting a past state: 'is thought to have been + V3'.", "Kayıp el yazmasının 1845'teki yangında yok olduğuna inanılmaktadır (geçmiş edilgen durum: to have been destroyed).",
     {'to be': 'Şu an yok edilmekte olduğunu ima eder.', 'being': 'Ulaç yapısıdır.', 'having been': "'To' eksiktir."}),
    ('___ estimated that over two million commuters use the metro system daily.', 'It is', ['He is', 'There is', 'That is'],
     'Statistical impersonal reporting.', 'Günde 2 milyondan fazla yolcunun metroyu kullandığı tahmin edilmektedir.',
     {'He is': 'Kişi zamiridir.', 'There is': 'Hatalı giriştir.', 'That is': "Özne 'it' olmalıdır."}),
    ('The cybersecurity startup is understood ___ several lucrative buyout offers.', 'to have rejected', ['rejecting', 'to reject', 'rejected'],
     "Perfect infinitive reporting past action: 'is understood to have rejected'.", 'Girişimin birkaç satın alma teklifini reddettiği anlaşılmaktadır (geçmiş eylem: to have rejected).',
     {'rejecting': 'Ulaç aktarıma uymaz.', 'to reject': 'Şu anki veya gelecekteki reddi ima eder.', 'rejected': 'Çekimli fiil gelemez.'}),
    ('___ claimed that the new battery chemistry doubles vehicle range.', 'It is', ['Is', 'There is', 'He is'],
     'Impersonal claim structure.', 'Yeni batarya kimyasının menzili ikiye katladığı iddia edilmektedir.',
     {'Is': 'Özne eksiktir.', 'There is': 'Hatalı yapıdır.', 'He is': 'Kişi zamiridir.'}),
    ('The prime suspect is believed ___ the country using a forged passport.', 'to have fled', ['fleeing', 'to flee', 'fled'],
     "Reporting past escape: 'is believed to have fled'.", 'Baş şüphelinin sahte pasaportla ülkeden kaçtığına inanılmaktadır.',
     {'fleeing': 'Ulaç aktarıma uymaz.', 'to flee': 'Şu an kaçtığını söyler.', 'fled': 'Çekimli fiil peş peşe gelemez.'}),
    ('___ understood that both parties have agreed on the fundamental licensing terms.', 'It is', ['There is', 'That is', 'He is'],
     'Diplomatic/corporate impersonal reporting.', 'Her iki tarafın da temel lisans şartlarında uzlaştığı anlaşılmaktadır.',
     {'There is': 'Varoluş bildirir.', 'That is': "Giriş öznesi 'it' gerektirir.", 'He is': 'Kişi zamiridir.'}),
    ('The ancient philosopher is considered ___ one of the founders of Western ethics.', 'to be', ['being', 'that he is', 'was'],
     'Attributive reporting passive.', 'Antik filozofun Batı etiğinin kurucularından biri olduğu kabul edilir.',
     {'being': 'Ulaç kullanılmaz.', 'that he is': "Özne öne çıktığı için 'that' kullanılmaz.", 'was': 'Çift çekimli fiil hatasıdır.'}),
    ('___ alleged that the executive insider trading occurred over several months.', 'It is', ['There is', 'Is', 'This is'],
     'Legal impersonal passive allegation.', 'İçeriden öğrenenlerin ticaretinin birkaç ay boyunca sürdüğü iddia edilmektedir.',
     {'There is': 'Hatalı yapıdır.', 'Is': 'Özne eksiktir.', 'This is': "Kişisel olmayan resmi yapıda 'it' gereklidir."}),
    ('The drug compound is known ___ severe adverse side effects in clinical trials.', 'to cause', ['causing', 'cause', 'caused'],
     'Scientific reporting passive.', 'İlaç bileşiğinin klinik testlerde ciddi yan etkilere yol açtığı bilinmektedir.',
     {'causing': 'Mastar gereklidir.', 'cause': "'To' eksiktir.", 'caused': 'Geçmiş zaman kipi gelemez.'}),
    ('___ presumed that all passengers survived the emergency water landing.', 'It is', ['He is', 'There is', 'That is'],
     'Formal aviation accident reporting.', 'Tüm yolcuların acil inişten sağ kurtulduğu varsayılmaktadır.',
     {'He is': 'Kişi zamiridir.', 'There is': 'Hatalı kalıptır.', 'That is': "Özne 'it' olmalıdır."}),
    ("The company's valuation is expected ___ ten billion dollars after the IPO.", 'to surpass', ['surpassing', 'surpasses', 'surpassed'],
     'Financial projection passive reporting.', 'Halka arz sonrası şirket değerlemesinin 10 milyar doları aşması beklenmektedir.',
     {'surpassing': 'Beklenti kalıbında mastar kullanılır.', 'surpasses': 'Çekimli fiil gelemez.', 'surpassed': 'Geçmiş zamandır.'}),
    ('___ calculated that solar panels pay for themselves within five years.', 'It is', ['There is', 'That is', 'He is'],
     'Economic analytical impersonal reporting.', 'Güneş panellerinin 5 yıl içinde kendini amorti ettiği hesaplanmaktadır.',
     {'There is': 'Hatalı yapıdır.', 'That is': "Özne 'it' gerektirir.", 'He is': 'Kişi zamiridir.'}),
    ('The ancient artifact is said ___ by a local shepherd in the hills.', 'to have been found', ['to find', 'finding', 'being found'],
     'Passive perfect infinitive reporting past discovery.', 'Antik eserin tepelerde yerel bir çoban tarafından bulunduğu söylenmektedir.',
     {'to find': 'Eserin bir şey bulduğunu söyler.', 'finding': 'Ulaçtır.', 'being found': 'Şu an bulunmakta olduğunu söyler.'}),
    ('___ hypothesized that dark matter constitutes the majority of universal mass.', 'It is', ['There is', 'This is', 'He is'],
     'Astrophysical impersonal hypothesis.', 'Karanlık maddenin evren kütlesinin çoğunluğunu oluşturduğu varsayılmaktadır.',
     {'There is': 'Hatalı yapıdır.', 'This is': "Resmi dilde 'it' kullanılır.", 'He is': 'Kişi zamiridir.'}),
    ('The board chairman is reported ___ his resignation letter this morning.', 'to have submitted', ['submitting', 'to submit', 'submitted'],
     'Reporting a past executive action with present relevance.', 'Yönetim kurulu başkanının bu sabah istifa mektubunu sunduğu bildirilmektedir.',
     {'submitting': 'Ulaç aktarıma uymaz.', 'to submit': 'Gelecekte sunacağını ima eder.', 'submitted': 'Çekimli fiildir.'}),
], 'Choose the correct impersonal reporting passive construction (It is said that / Subject is thought to):', "Kişisel olmayan aktarımlarda ('It is reported that...' veya 'He is believed to...') doğru yapıyı seçiniz.")

# grammar.b2.non-defining-relative-clauses-prepositions
add_lesson("grammar.b2.non-defining-relative-clauses-prepositions", "non-def-rel-prep", [
    ('The executive committee, several members ___ opposed the merger, adjourned late.', 'of whom', ['of which', 'of whose', 'of who'],
     "'Of whom' is used for people in formal non-defining relative clauses.", "Kişiler için resmi ek bilgi cümlelerinde 'of whom' (üyelerinden birkaçı) kullanılır.",
     {'of which': 'Cansız varlıklar veya nesneler için kullanılır, komite üyeleri insandır.', 'of whose': "Sahiplik bildirir, 'of' ile birlikte zamir olarak kullanılmaz.", 'of who': "'Of' edatından sonra nesne durumu 'whom' gereklidir."}),
    ('Our product relies on three proprietary algorithms, the most critical ___ handles encryption.', 'of which', ['of whom', 'of that', 'of whose'],
     "'Of which' refers to inanimate entities or concepts (algorithms).", "Algoritmalar gibi kavram ve nesneler için edat sonrasında 'of which' kullanılır.",
     {'of whom': 'İnsanlar için kullanılır.', 'of that': "Edatlardan sonra 'that' ilgi zamiri olarak asla kullanılamaz.", 'of whose': 'Sahiplik zamiridir.'}),
    ('The conference hotel, in front ___ stood a historic fountain, was fully booked.', 'of which', ['of that', 'of whom', 'of where'],
     "Spatial prepositional phrase modifying a building: 'in front of which'.", "Mekan niteleyen edat öbeğinde 'in front of which' (önünde tarihi bir çeşmenin bulunduğu) yapısı kullanılır.",
     {'of that': "Edattan sonra 'that' kullanılamaz.", 'of whom': 'Otel insan değildir.', 'of where': "'Where' zaten yer zarfıdır, 'of' edatı ile birleşmez."}),
    ('We interviewed five senior candidates, two ___ had extensive cloud security experience.', 'of whom', ['of which', 'of that', 'of who'],
     "Quantifier + preposition modifying people: 'two of whom'.", "Adaylar insan olduğu için 'two of whom' (ikisi bulut güvenliği tecrübesine sahip) kullanılır.",
     {'of which': 'Nesneler içindir.', 'of that': "Edattan sonra 'that' gelemez.", 'of who': "Edat nesne hali 'whom' ister."}),
    ('He presented four innovative architectural models, all ___ were approved by the client.', 'of which', ['of whom', 'of that', 'of what'],
     "Quantifier + preposition modifying models: 'all of which'.", "Modeller nesne olduğu için 'all of which' (hepsi müşteri tarafından onaylanan) kullanılır.",
     {'of whom': 'İnsanlar içindir.', 'of that': "Edattan sonra 'that' gelemez.", 'of what': "'What' ilgi zamiri olarak bu bağlama uymaz."}),
    ('The lead investigator, ___ we entrusted the forensic audit, delivered an exhaustive report.', 'to whom', ['to who', 'to that', 'to which'],
     "Preposition + relative pronoun referring to a person: 'to whom we entrusted'.", "Birine emanet etmek ('entrust to') yapısında insan için 'to whom' kullanılır.",
     {'to who': "Edattan sonra 'whom' şarttır.", 'to that': "Edattan sonra 'that' gelemez.", 'to which': "İnsanlar için 'which' kullanılmaz."}),
    ('The European venture capital fund, ___ the startup secured funding, praised the prototype.', 'from which', ['from that', 'from whom', 'from where'],
     "Source preposition modifying an institution/fund: 'from which'.", "Şirket/fon kurumları için 'from which' kullanılır.",
     {'from that': "Edattan sonra 'that' gelemez.", 'from whom': "Fon tüzel varlıktır, kişiler için 'whom' kullanılır.", 'from where': "'From which' kurum nitelemede standarttır."}),
    ('She outlined twenty proposed regulatory changes, none ___ would affect our operations.', 'of which', ['of whom', 'of that', 'of whose'],
     "Modifying proposed changes: 'none of which'.", "Önerilen yasa değişiklikleri cansızdır; 'none of which' (hiçbiri operasyonlarımızı etkilemeyecek) denir.",
     {'of whom': 'İnsanlar içindir.', 'of that': "Edattan sonra 'that' gelemez.", 'of whose': 'Sahiplik zamiridir.'}),
    ('The international keynote speakers, ___ travel arrangements had been finalized, arrived on time.', 'for whom', ['for who', 'for that', 'for which'],
     "Beneficiary preposition modifying speakers: 'for whom'.", "Konuşmacılar insan olduğu için 'for whom' (kendileri için seyahat planı yapılan) kullanılır.",
     {'for who': "Edattan sonra 'whom' kullanılır.", 'for that': "Edatla 'that' gelemez.", 'for which': "İnsanlara 'which' denmez."}),
    ('This is the groundbreaking research paper, ___ our core product hypothesis was based.', 'on which', ['on that', 'on whom', 'on where'],
     "Collocation 'based on': 'on which our hypothesis was based'.", "'Base on' (dayanmak) kalıbı sebebiyle makaleyi nitelerken 'on which' kullanılır.",
     {'on that': "Edattan sonra 'that' gelemez.", 'on whom': 'Makale insan değildir.', 'on where': "Mekan bildiren 'where' makale için uygun değildir."}),
    ('They analyzed seven potential acquisition targets, three ___ were located in Scandinavia.', 'of which', ['of whom', 'of that', 'of whose'],
     "Modifying companies/targets: 'three of which'.", "Hedef şirketler için 'three of which' kullanılır.",
     {'of whom': 'İnsanlar içindir.', 'of that': "Edattan sonra 'that' gelemez.", 'of whose': 'Sahiplik zamiridir.'}),
    ('The legal arbitrator, ___ both companies had agreed, issued a binding resolution.', 'on whom', ['on who', 'on that', 'on which'],
     "Preposition referring to an agreed arbitrator: 'on whom'.", "Hakem insan olduğu için 'on whom' kullanılır.",
     {'on who': "Edattan sonra 'whom' gerekir.", 'on that': "Edatla 'that' kullanılmaz.", 'on which': 'Kişiler için kullanılmaz.'}),
    ('We tested five database configurations, the fastest ___ achieved sub-millisecond latency.', 'of which', ['of whom', 'of that', 'of what'],
     "Superlative + preposition modifying configurations: 'the fastest of which'.", "Veri tabanı yapılandırmaları için 'the fastest of which' kullanılır.",
     {'of whom': 'İnsanlar içindir.', 'of that': "Edatla 'that' kullanılmaz.", 'of what': 'Hatalı yapıdır.'}),
    ('The international consortium, ___ our company belongs, promotes ethical AI standards.', 'to which', ['to that', 'to whom', 'to where'],
     "Collocation 'belong to': 'to which our company belongs'.", "'Belong to' (ait olmak) kalıbıyla konsorsiyumu nitelerken 'to which' kullanılır.",
     {'to that': "Edatla 'that' gelmez.", 'to whom': "Kurumlar için 'which' tercih edilir.", 'to where': 'Mekan değildir.'}),
    ('She collaborated with several distinguished historians, many ___ have published seminal books.', 'of whom', ['of which', 'of that', 'of whose'],
     "Quantifier modifying historians: 'many of whom'.", "Tarihçiler insan olduğu için 'many of whom' (birçoğu çığır açan kitaplar yayımlamış) denir.",
     {'of which': 'Nesneler içindir.', 'of that': "Edatla 'that' kullanılmaz.", 'of whose': 'Sahiplik zamiridir.'}),
    ('The operational crisis, ___ the management team was unprepared, caused significant churn.', 'for which', ['for that', 'for whom', 'for what'],
     "Collocation 'unprepared for': 'for which the team was unprepared'.", "'Unprepared for' (hazırlıksız) kalıbı sebebiyle kriz için 'for which' kullanılır.",
     {'for that': "Edatla 'that' kullanılmaz.", 'for whom': 'Kriz insan değildir.', 'for what': 'Hatalı yapıdır.'}),
    ('The symposium hosted eighty delegates, thirty ___ represented overseas universities.', 'of whom', ['of which', 'of that', 'of who'],
     "Delegates are people: 'thirty of whom'.", "Delegeler insan olduğu için 'thirty of whom' kullanılır.",
     {'of which': 'Nesneler içindir.', 'of that': "Edatla 'that' kullanılmaz.", 'of who': "Edattan sonra 'whom' gerekir."}),
    ('The platform operates on cloud microservices, through ___ all transactions are routed.', 'which', ['whom', 'that', 'what'],
     "Preposition 'through' + relative pronoun 'which'.", "Mikroservisler nesne olduğu için 'through which' (aracılığıyla tüm işlemlerin yönlendirildiği) denir.",
     {'whom': 'İnsanlar içindir.', 'that': "Edattan sonra 'that' gelemez.", 'what': 'Hatalı yapıdır.'}),
    ('The mentor, ___ guidance he owed his promotion, retired last week.', 'to whose', ['to whom', 'to which', 'to who'],
     "Preposition + possessive relative: 'to whose guidance'.", "Rehberliği sayesinde yükseldiği akıl hocası ('to whose guidance').",
     {'to whom': "Sahiplik bildiren 'guidance' ismini bağlayamaz.", 'to which': 'İnsan için kullanılmaz.', 'to who': 'Hatalı zamirdir.'}),
    ('They proposed twelve cost-cutting measures, only two ___ were deemed feasible.', 'of which', ['of whom', 'of that', 'of whose'],
     "Measures are concepts: 'only two of which'.", "Maddeler/önlemler için 'only two of which' kullanılır.",
     {'of whom': 'İnsanlar içindir.', 'of that': "Edatla 'that' kullanılmaz.", 'of whose': 'Sahiplik bildirir.'}),
], 'Choose the correct relative pronoun and preposition combination:', 'Edatlı ve ek bilgi veren ilgi cümleciklerinde (preposition + which/whom) doğru yapıyı seçiniz.')

# grammar.b2.verbs-changing-meaning-gerund-infinitive
add_lesson("grammar.b2.verbs-changing-meaning-gerund-infinitive", "verb-mean-ger-inf", [
    ('I distinctly remember ___ the front door before leaving the office.', 'locking', ['to lock', 'lock', 'locked'],
     "'Remember + gerund' refers to recalling a past action that has already happened.", "'Remember + V-ing', geçmişte yapılmış olan bir eylemi hafızada hatırlamayı ifade eder.",
     {'to lock': "'Remember to lock' gelecekte yapılması gereken bir görevi unutmamak anlamına gelir.", 'lock': 'Yalın fiil gelemez.', 'locked': 'Geçmiş zaman kipi gelemez.'}),
    ('Please remember ___ the server backup before you log off tonight.', 'to run', ['running', 'run', 'ran'],
     "'Remember + infinitive' means not forgetting to do a required future task.", "'Remember to run', yapılması gereken bir görevi yapmayı unutmamak anlamına gelir.",
     {'running': 'Geçmişte çalıştırdığını hatırlamak anlamına gelir.', 'run': "'To' eksiktir.", 'ran': 'Geçmiş zaman kipi gelemez.'}),
    ('On their long drive across Anatolia, they stopped ___ coffee at a roadside diner.', 'to drink', ['drinking', 'drink', 'drank'],
     "'Stop + infinitive' expresses interrupting an activity in order to do something else.", "'Stop to drink', başka bir eylemi yapmak amacıyla duraklamak/mola vermek demektir.",
     {'drinking': 'Kahve içme alışkanlığını tamamen bırakmak anlamına gelir.', 'drink': "'To' eksiktir.", 'drank': 'Geçmiş zaman kipi gelemez.'}),
    ('His doctor advised him that he must stop ___ sugary energy drinks.', 'consuming', ['to consume', 'consume', 'consumed'],
     "'Stop + gerund' means to permanently quit or cease an ongoing habit.", "'Stop + V-ing', bir alışkanlığı veya eylemi tamamen sonlandırmak/bırakmak demektir.",
     {'to consume': 'Tüketmek amacıyla durmak anlamına gelir ki tavsiyeyle çelişir.', 'consume': 'Yalın fiil gelemez.', 'consumed': 'Geçmiş zaman kipi gelemez.'}),
    ('I will never forget ___ our first customer contract in that small cafe.', 'signing', ['to sign', 'sign', 'signed'],
     "'Forget + gerund' refers to losing the memory of a past event.", "'Forget + V-ing', geçmişte yaşanmış bir anıyı unutmak demektir.",
     {'to sign': 'İmzalamayı unutmak (görevi atlamak) anlamına gelir.', 'sign': 'Yalın fiil gelemez.', 'signed': 'Geçmiş zaman kipi gelemez.'}),
    ("Don't forget ___ the client after the meeting to confirm next steps.", 'to email', ['emailing', 'email', 'emailed'],
     "'Forget + infinitive' means neglecting to perform an intended task.", "'Don't forget to email', yapılması gereken bir görevi unutma demektir.",
     {'emailing': 'E-posta attığını unutma anlamına gelir.', 'email': "'To' eksiktir.", 'emailed': 'Geçmiş zaman kipi gelemez.'}),
    ('We regret ___ you that your job application was not successful.', 'to inform', ['informing', 'inform', 'informed'],
     "'Regret + infinitive' is a formal expression used to deliver unfortunate news.", "'We regret to inform you...', resmi olarak üzücü bir haberi bildirirken kullanılan standart kalıptır.",
     {'informing': 'Geçmişte bilgilendirmiş olmaktan pişmanlık duymak anlamına gelir.', 'inform': "'To' eksiktir.", 'informed': 'Geçmiş zaman kipi gelemez.'}),
    ('He deeply regrets ___ his temper during the executive board meeting.', 'losing', ['to lose', 'lose', 'lost'],
     "'Regret + gerund' expresses sorrow or remorse about a past action.", "'Regret + V-ing', geçmişte yapılan bir hareketten dolayı pişmanlık duymaktır.",
     {'to lose': 'Geleceğe yönelik üzücü haber vermede kullanılır.', 'lose': 'Yalın fiil gelemez.', 'lost': 'Geçmiş zaman kipi gelemez.'}),
    ('If your laptop is freezing, try ___ the system cache first.', 'clearing', ['to clear', 'clear', 'cleared'],
     "'Try + gerund' means experimenting with a method to see if it solves a problem.", "'Try + V-ing', bir çözüm yolu olarak denemek/test etmek anlamına gelir.",
     {'to clear': 'Zor bir eylemi başarmak için çabalamak anlamına gelir.', 'clear': 'Yalın fiil gelemez.', 'cleared': 'Geçmiş zaman kipi gelemez.'}),
    ('She tried ___ the heavy safe by herself, but it was bolted to the floor.', 'to lift', ['lifting', 'lift', 'lifted'],
     "'Try + infinitive' means making an effort or attempt to achieve something difficult.", "'Try to lift', fiziksel olarak zor bir şeyi kaldırmaya çabalamak/gayret etmektir.",
     {'lifting': 'Yöntem olarak kaldırmayı denemek anlamına gelir.', 'lift': "'To' eksiktir.", 'lifted': 'Geçmiş zaman kipi gelemez.'}),
    ('After discussing the financial audit, the committee went on ___ marketing strategies.', 'to discuss', ['discussing', 'discuss', 'discussed'],
     "'Go on + infinitive' means shifting to a new topic or starting a subsequent activity.", "'Go on to discuss', bir konuyu bitirip yeni bir konuya geçmek demektir.",
     {'discussing': 'Aynı konuyu ara vermeden tartışmaya devam etmek anlamına gelir.', 'discuss': "'To' eksiktir.", 'discussed': 'Geçmiş zaman kipi gelemez.'}),
    ('Despite the noise in the hallway, she went on ___ her research paper.', 'writing', ['to write', 'write', 'wrote'],
     "'Go on + gerund' means continuing the same ongoing activity without stopping.", "'Go on writing', aynı eylemi yapmaya kesintisiz devam etmek demektir.",
     {'to write': 'Yeni bir konuya/eyleme geçmek anlamına gelir.', 'write': "'To' eksiktir.", 'wrote': 'Geçmiş zaman kipi gelemez.'}),
    ('I mean ___ the certification exam before the end of the second quarter.', 'to pass', ['passing', 'pass', 'passed'],
     "'Mean + infinitive' signifies intention or purpose ('intend to').", "'Mean to pass', 'geçmeyi niyet etmek/amaçlamak' anlamına gelir.",
     {'passing': "'Mean + V-ing' 'anlamına gelmek/gerektirmek' demektir.", 'pass': "'To' eksiktir.", 'passed': 'Geçmiş zaman kipi gelemez.'}),
    ('Accepting the leadership role will mean ___ fifty hours a week.', 'working', ['to work', 'work', 'worked'],
     "'Mean + gerund' expresses consequence or requirement ('involves').", "'Mean + V-ing', bir sonucun bunu gerektirmesi anlamına gelir.",
     {'to work': 'Kişisel niyet bildirir, role uygun düşmez.', 'work': 'Yalın fiil gelemez.', 'worked': 'Geçmiş zaman kipi gelemez.'}),
    ('He stopped ___ for the startup when he realized their ethics were questionable.', 'working', ['to work', 'work', 'worked'],
     "'Stop + gerund' means permanently quitting employment.", "Şirket için çalışmayı tamamen bıraktı ('stopped working').",
     {'to work': 'Çalışmak amacıyla durdu anlamına gelir.', 'work': "'To' eksiktir.", 'worked': 'Geçmiş zaman kipi gelemez.'}),
    ('She stopped at the bakery ___ some fresh sourdough bread.', 'to buy', ['buying', 'buy', 'bought'],
     "'Stop + infinitive' expresses the purpose of stopping.", "Taze ekmek almak amacıyla fırında durdu ('stopped to buy').",
     {'buying': 'Ekmek almayı bıraktı anlamına gelir.', 'buy': "'To' eksiktir.", 'bought': 'Geçmiş zaman kipi gelemez.'}),
    ('I regret ___ that our department cannot sponsor your conference trip.', 'to state', ['stating', 'state', 'stated'],
     'Formal notification of unfortunate decision.', "Departmanımızın geziye sponsor olamayacağını üzülerek belirtirim ('regret to state').",
     {'stating': 'Belirtmiş olmaktan pişmanlık duyarım anlamına gelir.', 'state': "'To' eksiktir.", 'stated': 'Geçmiş zaman kipi gelemez.'}),
    ('Try ___ chamomile tea if you are having difficulty falling asleep.', 'drinking', ['to drink', 'drink', 'drank'],
     "'Try + gerund' suggests experimenting with a remedy.", 'Uyumakta zorlanıyorsan papatya çayı içmeyi dene (çözüm yöntemi olarak denemek).',
     {'to drink': 'İçmek için zorlu çaba harcamak anlamına gelir.', 'drink': 'Yalın fiildir.', 'drank': 'Geçmiş zamandır.'}),
    ('Did you remember ___ off the conference room projector?', 'to switch', ['switching', 'switch', 'switched'],
     'Checking whether a task was remembered and performed.', 'Projektörü kapatmayı hatırladın mı (görevi yaptın mı)?',
     {'switching': 'Kapatmış olduğunu hatırladın mı anlamına gelir.', 'switch': "'To' eksiktir.", 'switched': 'Geçmiş zamandır.'}),
    ('I remember ___ that famous author speak at our university auditorium.', 'hearing', ['to hear', 'hear', 'heard'],
     'Recalling a cherished past experience.', 'O ünlü yazarın üniversite amfisinde konuşmasını dinlediğimi hatırlıyorum (geçmiş anı).',
     {'to hear': 'Gelecek görevi hatırlamak anlamına gelir.', 'hear': 'Yalın fiildir.', 'heard': 'Geçmiş zamandır.'}),
], 'Choose between gerund (-ing) and infinitive (to + verb) based on meaning change:', 'Anlamı değişen fiillerde (remember, stop, forget, regret, try) doğru yapıyı (gerund vs infinitive) seçiniz.')

# grammar.b2.causative-make-let-have-get
add_lesson("grammar.b2.causative-make-let-have-get", "causative-patterns", [
    ('The manager made all team members ___ the emergency security protocol.', 'review', ['to review', 'reviewing', 'reviewed'],
     "'Make + person + base verb' expresses compelling or requiring someone to do something.", "'Make' ettirgen fiili ardından kişi geldiğinde yalın fiil ('review') alır; 'to' almaz.",
     {'to review': "'Make' ettirgeninde etken fiil 'to' alamaz.", 'reviewing': 'Ulaç kullanılamaz.', 'reviewed': 'Geçmiş zaman kipi etken yapıda gelemez.'}),
    ('Our director let the engineers ___ on personal open-source projects on Fridays.', 'work', ['to work', 'working', 'worked'],
     "'Let + person + base verb' expresses granting permission.", "'Let' (izin vermek) ettirgen fiili de yalın fiil ('work') alır.",
     {'to work': "'Let' ardından mastar 'to' almaz.", 'working': 'Ulaç almaz.', 'worked': 'Geçmiş zaman kipi almaz.'}),
    ('We had our corporate security policy ___ by an external cybersecurity firm.', 'audited', ['audit', 'to audit', 'auditing'],
     "'Have + object + past participle' expresses arranging for a service to be done.", "'Have something done' kalıbında nesneden sonra fiilin 3. hali ('audited') gelir.",
     {'audit': 'Politika kendi kendini denetleyemez; edilgen V3 gereklidir.', 'to audit': 'Mastar bu yapıda kullanılmaz.', 'auditing': 'Ulaç edilgen anlama uymaz.'}),
    ('She finally got the IT helpdesk ___ her access credentials before the demo.', 'to reset', ['reset', 'resetting', 'resetted'],
     "'Get + person + infinitive with to' means persuading or convincing someone to act.", "'Get + kişi' ettirgen yapısı ardından 'to + yalın fiil' ('to reset') alır.",
     {'reset': "'Get' fiili kişi nesnesinden sonra 'to' gerektirir; yalın bırakılamaz.", 'resetting': 'Ulaç bu kalıba uymaz.', 'resetted': "'Reset' fiilinin 3. hali de 'reset'tir."}),
    ('The strict compliance regulation made the bank ___ their onboarding workflow.', 'overhaul', ['to overhaul', 'overhauling', 'overhauled'],
     "'Make + object + base verb'.", "'Make' zorlama/gereklilik bildirdiğinde yalın fiil alır.",
     {'to overhaul': "'Make' 'to' almaz.", 'overhauling': 'Ulaç almaz.', 'overhauled': 'Geçmiş kipi almaz.'}),
    ('The company will not let employees ___ unapproved third-party USB drives.', 'connect', ['to connect', 'connecting', 'connected'],
     "'Let + person + base verb'.", "'Let' izin vermeme durumunda yalın fiil gerektirir.",
     {'to connect': "'Let' 'to' almaz.", 'connecting': 'Ulaç almaz.', 'connected': 'Geçmiş zaman almaz.'}),
    ('I need to get my company laptop ___ before traveling to the conference.', 'repaired', ['repair', 'to repair', 'repairing'],
     "'Get + object + past participle' (passive causative).", "'Get something repaired' kalıbı (bilgisayarı tamir ettirmek).",
     {'repair': 'Laptop kendi kendini tamir edemez.', 'to repair': "Edilgen kalıpta 'to' kullanılmaz.", 'repairing': 'Ulaç kullanılmaz.'}),
    ('The team lead had a junior developer ___ the API documentation.', 'update', ['to update', 'updating', 'updated'],
     "'Have + person + base verb' (assigning a task to someone).", "'Have + kişi' ettirgen yapısında kişi görevlendirildiğinde yalın fiil ('update') alır.",
     {'to update': "'Have' ettirgeni 'to' almaz.", 'updating': 'Ulaç almaz.', 'updated': 'Geliştirici güncellenmez, geliştirici günceller.'}),
    ('Can you get the facilities team ___ the broken air conditioning unit?', 'to fix', ['fix', 'fixing', 'fixed'],
     "'Get + person + to + base verb'.", "'Get' birini bir işi yapmaya ikna etmekte 'to fix' alır.",
     {'fix': "'Have' olsaydı yalın olurdu; 'get' 'to' ister.", 'fixing': 'Ulaç almaz.', 'fixed': 'Ekip tamir edilmez.'}),
    ('She had her presentation slides ___ by a professional graphic designer.', 'designed', ['design', 'to design', 'designing'],
     "'Have + thing + past participle'.", "Slaytlarını profesyonel tasarımcıya tasarlattı ('had her slides designed').",
     {'design': 'Slaytlar kendi kendini tasarlayamaz.', 'to design': 'Hatalı yapıdır.', 'designing': 'Ulaç kullanılmaz.'}),
    ('The airline made all passengers ___ their carry-on luggage inside the sizer.', 'place', ['to place', 'placing', 'placed'],
     "'Make + person + base verb'.", 'Havayolu tüm yolculara çantalarını ölçüm kutusuna koydurttu.',
     {'to place': "'Make' 'to' almaz.", 'placing': 'Ulaç almaz.', 'placed': 'Geçmiş kipi almaz.'}),
    ('Our supervisor let us ___ thirty minutes early ahead of the national holiday.', 'leave', ['to leave', 'leaving', 'left'],
     "'Let + person + base verb'.", 'Yöneticimiz tatil öncesi 30 dakika erken çıkmamıza izin verdi.',
     {'to leave': "'Let' 'to' almaz.", 'leaving': 'Ulaç almaz.', 'left': 'Geçmiş kipi almaz.'}),
    ('We must get the legal contract ___ by outside counsel before Monday.', 'reviewed', ['review', 'to review', 'reviewing'],
     "'Get + object + past participle'.", 'Sözleşmeyi pazartesiden önce dış danışmanlara inceletmeliyiz.',
     {'review': 'Sözleşme inceleme yapamaz.', 'to review': 'Edilgen causativede kullanılmaz.', 'reviewing': 'Ulaç almaz.'}),
    ('The professor had each student ___ a five-minute summary of their thesis.', 'give', ['to give', 'giving', 'given'],
     "'Have + person + base verb'.", 'Profesör her öğrenciye tezinin 5 dakikalık özetini sundurttu.',
     {'to give': "'Have' 'to' almaz.", 'giving': 'Ulaç almaz.', 'given': 'Öğrenci sunulmaz, sunar.'}),
    ('How did you get the procurement department ___ the purchase order so fast?', 'to approve', ['approve', 'approving', 'approved'],
     "'Get + person + to + base verb'.", 'Satın alma departmanına siparişi bu kadar hızlı onaylatmayı nasıl başardın?',
     {'approve': "'Get' 'to' gerektirir.", 'approving': 'Ulaç almaz.', 'approved': 'Departman onaylanmaz.'}),
    ('They had the entire office floor ___ over the weekend.', 'painted', ['paint', 'to paint', 'painting'],
     "'Have + object + past participle'.", 'Hafta sonu tüm ofis katını boyattılar.',
     {'paint': 'Ofis kendi kendini boyayamaz.', 'to paint': 'Hatalı yapıdır.', 'painting': 'Ulaç almaz.'}),
    ('The sudden power cut made the factory machines ___ abruptly.', 'halt', ['to halt', 'halting', 'halted'],
     "'Make + object + base verb'.", 'Ani elektrik kesintisi fabrika makinelerini aniden durdurdu.',
     {'to halt': "'Make' 'to' almaz.", 'halting': 'Ulaç almaz.', 'halted': 'Geçmiş kipi almaz.'}),
    ('Will the security guards let visitors ___ photos inside the research gallery?', 'take', ['to take', 'taking', 'taken'],
     "'Let + person + base verb'.", 'Güvenlik ziyaretçilerin fotoğraf çekmesine izin verecek mi?',
     {'to take': "'Let' 'to' almaz.", 'taking': 'Ulaç almaz.', 'taken': 'Geçmiş kipi almaz.'}),
    ('I had the tailor ___ the sleeves of my corporate suit jacket.', 'shorten', ['to shorten', 'shortening', 'shortened'],
     "'Have + person + base verb'.", 'Terziye ceketimin kollarını kısalttırdım.',
     {'to shorten': "'Have' 'to' almaz.", 'shortening': 'Ulaç almaz.', 'shortened': 'Terzi kısaltılmaz.'}),
    ('We need to get our tax returns ___ by a certified public accountant.', 'prepared', ['prepare', 'to prepare', 'preparing'],
     "'Get + object + past participle'.", 'Vergi beyannamelerimizi yeminli mali müşavire hazırlatmamız gerekiyor.',
     {'prepare': 'Beyanname kendi kendini hazırlayamaz.', 'to prepare': 'Edilgen causativede kullanılmaz.', 'preparing': 'Ulaç almaz.'}),
], 'Choose the correct causative structure (make, let, have, get):', 'Ettirgen çatılarda (make + base, let + base, have + base/V3, get + to/V3) doğru kullanımı seçiniz.')

# grammar.b2.wishes-and-regrets-unreal-past
add_lesson("grammar.b2.wishes-and-regrets-unreal-past", "wish-regret-past", [
    ('I wish our team ___ more time to conduct thorough penetration testing.', 'had', ['has', 'would have', 'will have'],
     "'Wish + Past Simple' expresses a desire for a different present situation.", "Şu anki durumun farklı olmasını dilemek için 'wish + Past Simple' ('had') kullanılır.",
     {'has': "Geniş zaman kipi 'wish' sonrasında gerçek dışı istek kuramaz.", 'would have': "Kişinin elinde olmayan durumlarda 'would have' kullanılmaz.", 'will have': "Gelecek zaman kipi 'wish' ardına gelemez."}),
    ('If only we ___ that backup system before the database drive corrupted!', 'had installed', ['installed', 'install', 'would install'],
     "'If only + Past Perfect' expresses deep regret about a past failure or inaction.", "Geçmişte yapılmamış bir eylemden duyulan derin pişmanlık 'if only + Past Perfect' ('had installed') ile verilir.",
     {'installed': 'Past Simple kipi şu anki isteği ifade eder, geçmişteki bozulmadan öncesini vermez.', 'install': 'Geniş zamandır.', 'would install': 'Geleceğe yönelik şikayettir.'}),
    ('I wish you ___ interrupting me while I am delivering the client presentation.', 'would stop', ['stopped', 'stop', 'had stopped'],
     "'Wish + would + base verb' expresses annoyance or a wish for someone to change their behavior.", "Birinin rahatsız edici davranışını değiştirmesini istemek için 'wish + would stop' kullanılır.",
     {'stopped': 'Kişisel bir alışkanlığın mevcut durumunu ifade eder, anlık davranış şikayetini vermez.', 'stop': "Yalın fiil 'wish' sonrasına gelemez.", 'had stopped': 'Geçmişte durmuş olsaydı anlamına gelir.'}),
    ('She wishes she ___ the senior engineering role in Singapore when she had the chance.', 'had accepted', ['accepted', 'accepts', 'would accept'],
     'Regret about a missed past opportunity requires Past Perfect.', "Geçmişte kaçırılmış bir teklife duyulan pişmanlık 'had accepted' gerektirir.",
     {'accepted': 'Şu anki durumu ima eder.', 'accepts': 'Geniş zamandır.', 'would accept': 'Şikayet bildirir.'}),
    ('If only our company ___ located closer to the central tech hub.', 'were', ['is', 'will be', 'would be'],
     "Hypothetical present desire with 'be' prefers subjunctive 'were'.", "Şirketin şu anki konumuna yönelik dilek 'were' (veya 'was') ile kurulur.",
     {'is': 'Gerçekliği bildirir.', 'will be': 'Gelecek zamandır.', 'would be': "'Would be' durum isteklerinde tercih edilmez."}),
    ('I wish I ___ German when I lived in Munich for three years.', 'had learned', ['learned', 'learn', 'would learn'],
     "Past regret tied to a finished period in the past ('when I lived in Munich').", "Münih'te yaşarken Almanca öğrenmiş olmayı dilemek geçmişe aittir ('had learned').",
     {'learned': 'Şu anki dileği ima eder.', 'learn': 'Geniş zamandır.', 'would learn': 'Geleceğe yöneliktir.'}),
    ('The developers wish management ___ changing the sprint requirements mid-cycle.', 'would stop', ['stopped', 'stops', 'had stopped'],
     "Frustration with an external party's annoying recurring behavior.", "Yönetimin gereksinimleri sürekli değiştirmesine duyulan tepki ('would stop').",
     {'stopped': 'Şu anki statik durumu anlatır.', 'stops': 'Geniş zamandır.', 'had stopped': 'Geçmişte durmuş olsaydı anlamı verir.'}),
    ("If only I ___ more attention to the financial auditor's warnings last year!", 'had paid', ['paid', 'pay', 'would pay'],
     "Past regret with explicit past time marker ('last year').", "Geçen yılki uyarılara dikkat etmiş olmayı dilemek ('had paid').",
     {'paid': 'Şu anki durumu ifade eder.', 'pay': 'Geniş zamandır.', 'would pay': 'Şikayet bildirir.'}),
    ('I wish our apartment ___ a balcony overlooking the Bosphorus.', 'had', ['has', 'would have', 'will have'],
     'Present unattainable wish about property.', "Evimizin Boğaz'a bakan bir balkonu olmasını dilemek (mevcut arzu: had).",
     {'has': 'Gerçek zamandır.', 'would have': 'Yapay istektir.', 'will have': 'Gelecek zamandır.'}),
    ('He wishes he ___ so much money on speculative cryptocurrency investments.', "hadn't spent", ["didn't spend", "doesn't spend", "won't spend"],
     'Past financial regret with negative Past Perfect.', "Kripto paralara bu kadar çok para harcamamış olmayı dilemek ('hadn't spent').",
     {"didn't spend": 'Şu anki harcama alışkanlığını ima eder.', "doesn't spend": 'Geniş zamandır.', "won't spend": 'Gelecektir.'}),
    ('If only the weather ___ better today so we could hold the team offsite outdoors.', 'were', ['is', 'will be', 'had been'],
     "Present weather wish affecting today's plans.", "Bugün hava daha güzel olsaydı ('were').",
     {'is': 'Gerçek durumu söyler.', 'will be': 'Gelecek zamandır.', 'had been': 'Dünkü havayı kasteder.'}),
    ('I wish our stakeholders ___ answer emails within twenty-four hours.', 'would', ['did', 'will', 'had'],
     'Wish for someone else to change their responsive behavior.', "Paydaşların e-postalara 24 saat içinde yanıt vermesini istemek ('would answer').",
     {'did': 'Geniş zaman arzusunu karşılamaz.', 'will': "'Wish' ardına 'will' gelmez.", 'had': 'Geçmişe ait olurdu.'}),
    ('She wishes she ___ to that rude customer so angrily yesterday.', "hadn't spoken", ["didn't speak", "doesn't speak", "wouldn't speak"],
     'Past behavioral regret.', "Dün müşteriye o kadar öfkeli konuşmamış olmayı dilemek ('hadn't spoken').",
     {"didn't speak": 'Şu anki alışkanlığı ima eder.', "doesn't speak": 'Geniş zamandır.', "wouldn't speak": 'Gelecek şikayetidir.'}),
    ('If only I ___ how to configure Kubernetes clusters competently!', 'knew', ['know', 'will know', 'had known'],
     'Present skill deficit wish.', "Kubernetes yapılandırmayı yetkin şekilde biliyor olmayı dilemek ('knew').",
     {'know': 'Geniş zamandır.', 'will know': 'Gelecektir.', 'had known': 'Eskiden bilmiş olmayı kasteder.'}),
    ('The product lead wishes the engineering team ___ more realistic estimations.', 'provided', ['provides', 'will provide', 'is providing'],
     'Wish regarding present team performance.', "Mühendislik ekibinin daha gerçekçi tahminler sunmasını dilemek ('provided').",
     {'provides': 'Geniş zamandır.', 'will provide': 'Gelecektir.', 'is providing': 'Şimdiki zamandır.'}),
    ('I wish it ___ stop raining so we can walk to the conference hall.', 'would', ['did', 'will', 'had'],
     'Wish for an impersonal force/weather to stop annoying.', "Yağmurun artık durmasını dilemek ('would stop raining').",
     {'did': "Doğa olayında şikayet 'would' ile kurulur.", 'will': "'Wish' ile 'will' gelmez.", 'had': 'Geçmiş durumdur.'}),
    ('If only we ___ that senior architect before our competitor hired him!', 'had recruited', ['recruited', 'recruit', 'would recruit'],
     'Past lost recruitment opportunity.', "Rakip işe almadan önce o baş mimarı işe almış olmayı dilemek ('had recruited').",
     {'recruited': 'Şu anki durumu ima eder.', 'recruit': 'Geniş zamandır.', 'would recruit': 'Gelecek arzusudur.'}),
    ('I wish I ___ so exhausted after every single client sprint.', "weren't", ['am not', 'will not be', "hadn't been"],
     'Wish about current recurring physical state.', "Her sprint sonrası bu kadar yorgun hissetmiyor olmayı dilemek ('weren't').",
     {'am not': 'Gerçekliği söyler.', 'will not be': 'Gelecektir.', "hadn't been": 'Geçmişteki yorgunluğu kasteder.'}),
    ('They wish they ___ more attention to cybersecurity compliance before the audit.', 'had paid', ['paid', 'pay', 'would pay'],
     'Past compliance regret.', "Denetim öncesinde siber güvenliğe daha fazla dikkat etmiş olmayı dilemek ('had paid').",
     {'paid': 'Şu anki durumu ima eder.', 'pay': 'Geniş zamandır.', 'would pay': 'Şikayet bildirir.'}),
    ('If only I ___ afford to live in a modern apartment downtown.', 'could', ['can', 'will', 'would can'],
     "Present modal wish for ability: 'could afford'.", "Şehir merkezinde modern bir dairede yaşamaya maddi gücüm yetebilseydi ('could afford').",
     {'can': 'Gerçekliği söyler.', 'will': 'Gelecektir.', 'would can': 'Hatalı kalıptır.'}),
], 'Choose the correct structure for wishes and regrets (wish / if only):', 'Şu anki istekler (wish + past) ve geçmişteki pişmanlıklar (wish + had V3) için doğru kipi seçiniz.')

# grammar.b2.future-perfect-and-continuous
add_lesson("grammar.b2.future-perfect-and-continuous", "fut-perf-cont", [
    ('By the end of this quarter, our team ___ the entire cloud migration.', 'will have completed', ['will be completing', 'completes', 'will complete'],
     "'By + future time marker' indicates completion before a deadline, requiring Future Perfect.", "'By the end of this quarter' (bu çeyreğin sonuna kadar) bir son tarihten önce tamamlanmışlığı anlatır ve Future Perfect ('will have completed') gerektirir.",
     {'will be completing': 'O anda tamamlamakta olacağımızı söyler, bitmişlik sonucunu vermez.', 'completes': 'Geniş zamandır.', 'will complete': 'Son tarihe kadar bitmiş olma vurgusunu zayıf bırakır.'}),
    ('This time next week, I ___ on a Mediterranean beach in Antalya.', 'will be relaxing', ['will have relaxed', 'relax', 'am relaxed'],
     "'This time next week' indicates an action in progress at a specific future moment.", "'This time next week' (gelecek hafta bu saatlerde) gelecekteki bir anda devam etmekte olacak eylemi (Future Continuous) bildirir.",
     {'will have relaxed': 'Gelecek hafta dinlenmiş olup bitireceğimi söyler.', 'relax': 'Geniş zamandır.', 'am relaxed': 'Mevcut durumdur.'}),
    ('By 2030, scientists estimate that humanity ___ commercial fusion power.', 'will have harnessed', ['will be harnessing', 'harnesses', 'harnessed'],
     'Achievement before a milestone year requires Future Perfect.', '2030 yılına kadar füzyon enerjisinin kontrol altına alınmış olacağı öngörüsü.',
     {'will be harnessing': 'O anda kontrol altına almakla meşgul olunacağını ima eder.', 'harnesses': 'Geniş zamandır.', 'harnessed': 'Geçmiş zamandır.'}),
    ("Don't phone him at 8 PM; he ___ dinner with key European investors.", 'will be having', ['will have had', 'has', 'had'],
     'Action in progress at a specific evening hour.', "Akşam saat 8'de yatırımcılarla yemekte (yemek yiyor) olacaktır.",
     {'will have had': 'Yemeği yemiş bitirmiş olacağını söyler.', 'has': 'Geniş zamandır.', 'had': 'Geçmiş zamandır.'}),
    ("In five years' time, how many active users ___ on our SaaS platform?", 'will be subscribing', ['will have subscribed', 'will subscribe', 'subscribe'],
     'Inquiring about ongoing user engagement in the future.', 'Beş yıl sonra platformumuza kaç aktif kullanıcının abone olarak devam ediyor olacağı.',
     {'will have subscribed': 'Toplam abone olmuş kişileri sorar.', 'will subscribe': 'Genel tahmindir.', 'subscribe': 'Geniş zamandır.'}),
    ('By the time the keynote begins, all attendees ___ their registration badges.', 'will have collected', ['will be collecting', 'collect', 'collected'],
     "'By the time + Present Simple' clause triggers Future Perfect in the main clause.", "'By the time' yan cümleciği ana cümlede Future Perfect ('will have collected') gerektirir.",
     {'will be collecting': 'Konuşma başladığında hala toplamakta olacaklarını söyler.', 'collect': 'Geniş zamandır.', 'collected': 'Geçmiş zamandır.'}),
    ('Next Monday morning, the auditors ___ our financial ledger records.', 'will be reviewing', ['will have reviewed', 'review', 'reviewed'],
     'Scheduled activity in progress next week.', 'Gelecek pazartesi sabahı denetçiler kayıtlarımızı incelemekte olacaklar.',
     {'will have reviewed': 'Pazartesi sabahı incelemeyi bitirmiş olacaklarını söyler.', 'review': 'Geniş zamandır.', 'reviewed': 'Geçmiş zamandır.'}),
    ('By midnight, our automated pipeline ___ over two million transaction records.', 'will have processed', ['will be processing', 'processes', 'processed'],
     'Volume processed before a specific time milestone.', 'Gece yarısına kadar 2 milyondan fazla kayıt işlenmiş olacaktır.',
     {'will be processing': 'Gece yarısı işlemekte olacağını söyler.', 'processes': 'Geniş zamandır.', 'processed': 'Geçmiş zamandır.'}),
    ('During the scheduled maintenance window, our engineers ___ the server firmware.', 'will be upgrading', ['will have upgraded', 'upgrade', 'upgraded'],
     'Action in progress throughout the maintenance window.', 'Bakım penceresi boyunca mühendislerimiz donanım yazılımını yükseltiyor olacaklar.',
     {'will have upgraded': 'Pencere boyunca bitmişliği değil süreci anlatır.', 'upgrade': 'Geniş zamandır.', 'upgraded': 'Geçmiş zamandır.'}),
    ('By next June, she ___ at this corporate law firm for a full decade.', 'will have been working', ['will work', 'works', 'is working'],
     'Future Perfect Continuous for completed duration up to a future point.', 'Gelecek haziranda bu hukuk bürosunda tam 10 yıldır çalışıyor olacak.',
     {'will work': 'Gelecek 10 yıllık süreci vermez.', 'works': 'Geniş zamandır.', 'is working': 'Şu anı anlatır.'}),
    ("Don't worry; by tomorrow morning, the technical team ___ a hotfix.", 'will have deployed', ['will be deploying', 'deploys', 'deployed'],
     'Completion guaranteed before the morning.', 'Yarın sabaha kadar teknik ekip acil yamayı canlıya almış olacaktır.',
     {'will be deploying': 'Sabah canlıya almakta olacaklarını söyler.', 'deploys': 'Geniş zamandır.', 'deployed': 'Geçmiş zamandır.'}),
    ('At 10 AM tomorrow, our CEO ___ live on national television.', 'will be speaking', ['will have spoken', 'speaks', 'spoke'],
     'Specific time in the future with continuous action.', "Yarın saat 10'da CEO televizyonda canlı yayında konuşuyor olacak.",
     {'will have spoken': 'Konuşup bitirmiş olacağını söyler.', 'speaks': 'Geniş zamandır.', 'spoke': 'Geçmiş zamandır.'}),
    ('By the time you finish your coffee, the software installation ___ .', 'will have finished', ['will be finishing', 'finishes', 'finished'],
     'Completion before the coffee is finished.', 'Kahveni bitirene kadar yazılım kurulumu tamamlanmış olacaktır.',
     {'will be finishing': 'Tamamlanmakta olacak anlamına gelir.', 'finishes': 'Geniş zamandır.', 'finished': 'Geçmiş zamandır.'}),
    ('We ___ in the main auditorium all afternoon, so look for us there.', 'will be rehearsing', ['will have rehearsed', 'rehearse', 'rehearsed'],
     'Ongoing activity throughout the afternoon.', 'Bütün öğleden sonra ana salonda prova yapıyor olacağız.',
     {'will have rehearsed': 'Öğleden sonra provayı bitirmiş olacağımızı söyler.', 'rehearse': 'Geniş zamandır.', 'rehearsed': 'Geçmiş zamandır.'}),
    ('By the end of his sabbatical, the professor ___ two new academic textbooks.', 'will have authored', ['will be authoring', 'authors', 'authored'],
     'Completed books by the end of leave.', 'İzin döneminin sonuna kadar profesör iki yeni ders kitabı yazmış olacaktır.',
     {'will be authoring': 'O anda yazmakta olacağını söyler.', 'authors': 'Geniş zamandır.', 'authored': 'Geçmiş zamandır.'}),
    ('Will you ___ the car this evening, or can I borrow it?', 'be using', ['have used', 'use', 'used'],
     "Polite inquiry about someone's future plans.", 'Bu akşam arabayı kullanıyor olacak mısın (planın var mı)?',
     {'have used': 'Kullanıp bitirmiş olacak mısın diye sorar.', 'use': 'Geniş zamandır.', 'used': 'Geçmiş zamandır.'}),
    ('By Friday evening, the sales team ___ their ambitious quarterly quota.', 'will have reached', ['will be reaching', 'reaches', 'reached'],
     'Quota attained before Friday night.', 'Cuma akşamına kadar satış ekibi iddialı çeyreklik hedefine ulaşmış olacaktır.',
     {'will be reaching': 'Ulaşmakta olacağını söyler.', 'reaches': 'Geniş zamandır.', 'reached': 'Geçmiş zamandır.'}),
    ('Next semester, she ___ advanced machine learning at ETH Zurich.', 'will be studying', ['will have studied', 'studies', 'studied'],
     'Ongoing future academic engagement.', "Gelecek dönem Zürih'te ileri makine öğrenimi okuyor olacak.",
     {'will have studied': 'Gelecek dönem okumayı bitirmiş olacağını söyler.', 'studies': 'Geniş zamandır.', 'studied': 'Geçmiş zamandır.'}),
    ('By the time the project wraps up, we ___ over five hundred pull requests.', 'will have merged', ['will be merging', 'merge', 'merged'],
     'Cumulative merged requests by project end.', "Proje bittiğinde 500'den fazla pull request birleştirilmiş olacaktır.",
     {'will be merging': 'Birleştirmekte olacağımızı söyler.', 'merge': 'Geniş zamandır.', 'merged': 'Geçmiş zamandır.'}),
    ('At this rate, the global temperature ___ by two degrees Celsius before 2050.', 'will have risen', ['will be rising', 'rises', 'rose'],
     'Cumulative environmental threshold reached before a year.', "Bu gidişle küresel sıcaklık 2050'den önce 2 derece artmış olacaktır.",
     {'will be rising': 'Artmakta olacağını söyler.', 'rises': 'Geniş zamandır.', 'rose': 'Geçmiş zamandır.'}),
], 'Choose between Future Continuous (will be doing) and Future Perfect (will have done):', 'Gelecekte devam edecek eylemler (Future Continuous) ile gelecekte tamamlanmış olacak hedefler (Future Perfect) arasında seçim yapınız.')

# grammar.b2.discourse-markers-concession-contrast
add_lesson("grammar.b2.discourse-markers-concession-contrast", "disc-mark-concess", [
    ('___ the economic recession, the tech firm posted record annual revenues.', 'Despite', ['Although', 'Whereas', 'Even though'],
     "'Despite' (or 'In spite of') is strictly followed by a noun phrase or gerund.", "'Despite' ardından doğrudan isim öbeği ('the economic recession') veya ulaç alır; cümle almaz.",
     {'Although': "'Although' tam bir cümle (özne + fiil) gerektirir.", 'Whereas': 'İki durumu kıyaslarken tam cümle ile kullanılır.', 'Even though': 'Tam bir cümle gerektirir.'}),
    ('The prototype was highly innovative; ___ , the production costs were prohibitive.', 'however', ['although', 'despite', 'whereas'],
     "'However' is a conjunctive adverb connecting two independent clauses, often preceded by a semicolon.", "'However' (ancak/yine de) noktalı virgül veya nokta sonrası bağımsız cümleyi bağlar.",
     {'although': 'Yan cümle bağlacıdır; noktalı virgül ardına bu şekilde tek başına gelmez.', 'despite': 'Ardından isim öbeği gerektirir.', 'whereas': 'Kıyaslama bağlacıdır.'}),
    ('___ she had prepared thoroughly, she felt nervous before the board presentation.', 'Although', ['Despite', 'In spite of', 'Nevertheless'],
     "'Although' connects a subordinate clause with subject and verb ('she had prepared').", "'Although' (her ne kadar ... ise de) özne ve fiil içeren tam yan cümleyi bağlar.",
     {'Despite': 'İsim öbeği ister, tam cümle alamaz.', 'In spite of': 'İsim öbeği gerektirir.', 'Nevertheless': 'Bağımsız geçiş zarfıdır, yan cümle başlatamaz.'}),
    ('Our desktop application is written in C++, ___ our web interface runs on React.', 'whereas', ['despite', 'in spite of', 'nevertheless'],
     "'Whereas' expresses a direct contrast between two parallel facts.", "'Whereas' (oysa ki / buna karşın) iki farklı olguyu paralel şekilde kıyaslar.",
     {'despite': 'İsim öbeği gerektirir.', 'in spite of': 'İsim öbeği gerektirir.', 'nevertheless': 'Geçiş zarfıdır, virgülle iki cümleyi bağlamaz.'}),
    ('The team faced immense supply chain hurdles. ___ , they met the delivery deadline.', 'Nevertheless', ['Although', 'Even though', 'Despite'],
     "'Nevertheless' stands at the beginning of an independent sentence to indicate concession.", "'Nevertheless' (buna rağmen / yine de) bağımsız cümlenin başında ödün/zıtlık bildirir.",
     {'Although': 'Yan cümle bağlacıdır, bağımsız cümleyi tek başına başlatmaz.', 'Even though': 'Yan cümle bağlacıdır.', 'Despite': 'Ardından isim öbeği gerektirir.'}),
    ('___ facing severe regulatory scrutiny, the fintech company launched its crypto card.', 'Despite', ['Although', 'However', 'Whereas'],
     "'Despite' followed by a gerund clause ('facing...').", "'Despite' ardından ulaç ('facing') alarak kullanılır.",
     {'Although': "Genellikle özne + fiil ister ('Although it faced...').", 'However': 'Geçiş zarfıdır.', 'Whereas': 'Kıyaslama bağlacıdır.'}),
    ('The startup was operating at a loss; ___ , venture capitalists continued funding it.', 'nonetheless', ['although', 'in spite', 'while'],
     "'Nonetheless' functions as an adverbial connector of concession.", "'Nonetheless' (yine de) noktalı virgülden sonra zıtlık bildiren geçiş zarfıdır.",
     {'although': 'Yan cümle bağlacıdır.', 'in spite': "'Of' eksiktir.", 'while': 'Yan cümle bağlacıdır.'}),
    ('Online retail surged during the quarter, ___ brick-and-mortar foot traffic declined.', 'while', ['despite', 'in spite of', 'nevertheless'],
     "'While' used to contrast two contemporaneous trends.", "'While' (oysa / iken) zıt iki eğilimi kıyaslamak için kullanılır.",
     {'despite': 'İsim öbeği ister.', 'in spite of': 'İsim öbeği ister.', 'nevertheless': 'Geçiş zarfıdır.'}),
    ('___ the fact that the code was thoroughly tested, an edge-case bug appeared in production.', 'Despite', ['Although', 'However', 'Whereas'],
     "'Despite the fact that...' is the standard prepositional phrase followed by a full clause.", "'Despite the fact that...' kalıbı arkasından tam cümle alabilir.",
     {'Although': "'The fact that' yapısına ihtiyaç duymaz, doğrudan 'Although the code...' denir.", 'However': 'Geçiş zarfıdır.', 'Whereas': 'Kıyaslama bağlacıdır.'}),
    ('He decided to invest in the venture, ___ knowing the substantial market risks.', 'despite', ['although', 'however', 'whereas'],
     "'Despite' + gerund ('knowing...').", "'Despite knowing...' (bilmesine rağmen).",
     {'although': "'Although he knew' şeklinde özne-fiil ister.", 'however': 'Geçiş zarfıdır.', 'whereas': 'Kıyaslama bağlacıdır.'}),
    ('The server cluster remained stable ___ high traffic spikes throughout the sale.', 'in spite of', ['although', 'even though', 'whereas'],
     "'In spite of' + noun phrase.", "'In spite of' ardından isim öbeği ('high traffic spikes') alır.",
     {'although': 'Tam cümle ister.', 'even though': 'Tam cümle ister.', 'whereas': 'Kıyaslama bağlacıdır.'}),
    ('The marketing budget was slashed; ___ , customer acquisition grew by 15%.', 'even so', ['although', 'despite', 'whereas'],
     "'Even so' indicates surprise at a positive outcome despite adversity.", "'Even so' (öyle olsa bile / yine de) önceki duruma rağmen gerçekleşen şaşırtıcı sonucu bağlar.",
     {'although': 'Yan cümle bağlacıdır.', 'despite': 'İsim öbeği ister.', 'whereas': 'Kıyaslama bağlacıdır.'}),
    ('___ being the youngest candidate in the pool, she had the strongest cloud portfolio.', 'Despite', ['Although', 'However', 'While'],
     "'Despite being...' gerund construction.", "Aday havuzundaki en genç kişi olmasına rağmen ('Despite being...').",
     {'Although': "'Although she was...' şeklinde tam cümle ister.", 'However': 'Geçiş zarfıdır.', 'While': "'While' gerund ile bu zıtlıkta tercih edilmez."}),
    ('The user interface is visually stunning, ___ the backend architecture requires significant optimization.', 'yet', ['despite', 'in spite of', 'nevertheless'],
     "Coordinating conjunction 'yet' joining two contrasting clauses.", "İki zıt ana cümleyi bağlayan 'yet' (ama yine de).",
     {'despite': 'İsim öbeği ister.', 'in spite of': 'İsim öbeği ister.', 'nevertheless': 'Noktalı virgül veya nokta gerektirir.'}),
    ('___ the team worked tirelessly over the weekend, the release was delayed by two days.', 'Even though', ['In spite of', 'Despite', 'However'],
     "'Even though' emphasizes strong concession with full subject and verb.", "'Even though' (özveriyle çalışmalarına rağmen) tam cümleyle güçlü ödün bildirir.",
     {'In spite of': 'İsim öbeği ister.', 'Despite': 'İsim öbeği ister.', 'However': 'Geçiş zarfıdır.'}),
    ('Traditional banks are closing regional branches, ___ digital banks are acquiring millions of new users.', 'whereas', ['despite', 'in spite of', 'nonetheless'],
     'Contrasting two distinct organizational strategies.', "Geleneksel bankalar şube kapatırken dijital bankaların büyümesini kıyaslar ('whereas').",
     {'despite': 'İsim öbeği ister.', 'in spite of': 'İsim öbeği ister.', 'nonetheless': 'Geçiş zarfıdır.'}),
    ('The company expanded into Latin America ___ advice from external economic consultants.', 'against', ['despite of', 'although', 'whereas'],
     "Idiomatic preposition 'against advice'.", "Danışmanların tavsiyesine karşı / rağmen ('against advice').",
     {'despite of': "'Despite' 'of' almaz.", 'although': 'Tam cümle ister.', 'whereas': 'Kıyaslama bağlacıdır.'}),
    ('She was exhausted from the international flight; ___ , she insisted on attending the strategy dinner.', 'still', ['although', 'despite', 'whereas'],
     'Adverbial transition of persistence.', "Yine de / buna rağmen akşam yemeğine katılmakta ısrar etti ('still').",
     {'although': 'Yan cümle bağlacıdır.', 'despite': 'İsim öbeği ister.', 'whereas': 'Kıyaslama bağlacıdır.'}),
    ('___ having little previous experience in mobile design, his prototype won first prize.', 'In spite of', ['Although', 'However', 'Whereas'],
     "'In spite of' + gerund phrase.", "Mobil tasarımda çok az deneyimi olmasına rağmen ('In spite of having...').",
     {'Although': "'Although he had...' şeklinde tam cümle ister.", 'However': 'Geçiş zarfıdır.', 'Whereas': 'Kıyaslama bağlacıdır.'}),
    ('The code was mathematically proven correct; ___ , real-world network latency introduced unexpected race conditions.', 'on the other hand', ['despite', 'in spite of', 'although'],
     'Discourse marker balancing theoretical correctness with practical reality.', "Öte yandan gerçek dünya ağ gecikmesi beklenmeyen sorunlar doğurdu ('on the other hand').",
     {'despite': 'İsim öbeği ister.', 'in spite of': 'İsim öbeği ister.', 'although': 'Yan cümle bağlacıdır.'}),
], 'Choose the appropriate discourse marker for concession or contrast:', 'Zıtlık ve ödün bildiren söylem belirteçlerini (although, despite, however, whereas, nevertheless) doğru seçiniz.')

