#!/usr/bin/env python3
"""
Comprehensive Exercise Generator for B1 Grammar.
Generates exactly 20 exercises for each of the 10 B1 grammar lessons = 200 exercises.
"""
from mcq_balancer import McqBalancer

balancer = McqBalancer(seed=702)

def make_ex(ex_id, target_id, level, prompt_en, prompt_tr, stem, correct, distractors, exp_en, exp_tr, dist_exps, diff="standard"):
    options, idx = balancer.balance_options(correct, distractors)
    return {
        "id": ex_id,
        "target_content_id": target_id,
        "cefr_level": level,
        "skill_domain": "grammar",
        "exercise_type": "multiple_choice",
        "prompt_en": prompt_en,
        "prompt_tr_hint": prompt_tr,
        "stem": stem,
        "options": options,
        "correct_answer": correct,
        "explanation_en": exp_en,
        "explanation_tr": exp_tr,
        "distractor_explanations": dist_exps,
        "difficulty": diff,
        "status": "APPROVED",
        "version": 1
    }

B1_EXERCISES = []

def add_lesson(lesson_id, short_id, items, prompt_en, prompt_tr):
    for i, data in enumerate(items, 1):
        stem, corr, dists, en_exp, tr_exp, d_exps = data
        B1_EXERCISES.append(make_ex(f"exercise.b1.{short_id}-{i:02d}", lesson_id, "B1",
                                    prompt_en, prompt_tr, stem, corr, dists, en_exp, tr_exp, d_exps))

# grammar.present-perfect-vs-past-simple
add_lesson("grammar.present-perfect-vs-past-simple", "pres-perf-past", [
    ('We ___ the quarterly audit yesterday afternoon.', 'finished', ['have finished', 'finish', 'had finished'],
     "'Yesterday' is a finished past time marker requiring Past Simple.", "'Yesterday' kapalı geçmiş zaman zarfıdır ve Past Simple gerektirir.",
     {'have finished': "Present Perfect 'yesterday' gibi net geçmiş zaman zarflarıyla kullanılamaz.", 'finish': 'Geniş zaman dün tamamlanan bir eylemi ifade edemez.', 'had finished': 'Past Perfect geçmişte kıyaslanan ikinci bir eylem yoksa tek başına kullanılmaz.'}),
    ('She ___ at this company since October 2021.', 'has worked', ['worked', 'works', 'is working'],
     "'Since' indicates an action starting in the past and continuing to the present.", "'Since' geçmişte başlayıp günümüze kadar devam eden süreçleri Present Perfect ile bağlar.",
     {'worked': 'Past Simple eylemin geçmişte kalıp bittiğini bildirir, günümüzle bağ kurmaz.', 'works': "Geniş zaman başlangıç noktasını 'since' ile belirtirken uygun değildir.", 'is working': "Şimdiki zaman 'since' ile süreklilik başlangıcı için standart kabul edilmez."}),
    ('They ___ the contract yet, so we cannot proceed.', "haven't signed", ["didn't sign", "don't sign", "hadn't signed"],
     "'Yet' in negative statements requires Present Perfect.", "Olumsuz cümlelerde 'yet' (henüz) Present Perfect ile kullanılır.",
     {"didn't sign": "Past Simple kapalı geçmiş zamanı anlatır, güncel beklentiyi gösteren 'yet' ile uyumsuzdur.", "don't sign": 'Geniş zaman rutinleri anlatır.', "hadn't signed": 'Past Perfect geçmişten önceki geçmiş için referans gerektirir.'}),
    ('Our product manager ___ to London three times this year.', 'has traveled', ['traveled', 'travels', 'is traveling'],
     "'This year' is an unfinished time period requiring Present Perfect.", "'This year' henüz tamamlanmamış bir zaman dilimi olduğundan Present Perfect gerektirir.",
     {'traveled': 'Past Simple kapalı ve bitmiş zaman dilimlerinde kullanılır.', 'travels': 'Geniş zaman deneyim sayısını vermez.', 'is traveling': 'Şimdiki zaman geçmişteki seyahat deneyim sayılarını belirtmez.'}),
    ('When ___ your team submit the sprint deliverables?', 'did', ['have', 'has', 'were'],
     "Questions with 'When' ask for a specific point in time, requiring Past Simple.", "'When' ile sorulan sorular geçmişteki belirli bir anı sorguladığı için Past Simple ('did') gerektirir.",
     {'have': "'When' sorusu belirli bir zamanı sorduğundan Present Perfect ile kullanılmaz.", 'has': "Present Perfect 'when' soru sözcüğü ile zaman sormada kullanılmaz.", 'were': "'Submit' eylem fiili yalın haldeyken 'were' yardımcı fiil olarak soru yapamaz."}),
    ('I ___ my keys! Now I cannot enter the building.', 'have lost', ['lost', 'lose', 'am losing'],
     'A past action with an immediate present result requires Present Perfect.', 'Geçmişte yaşanmış ancak etkisi şu an devam eden sonuçlar için Present Perfect kullanılır.',
     {'lost': 'Past Simple eylemin geçmişte kaldığını söyler; kapıda kalma anlık sonucunu vurgulamaz.', 'lose': 'Geniş zaman anlık kayıp durumunu ifade edemez.', 'am losing': 'Şimdiki zaman anahtarın şu an kaybedilmekte olduğu gibi anlamsız bir durum yaratır.'}),
    ('In 2018, the startup ___ its first round of seed funding.', 'secured', ['has secured', 'secures', 'had secured'],
     'A definite finished year in the past strictly requires Past Simple.', "Geçmişte kalmış kesin bir yıl ('In 2018') sadece Past Simple gerektirir.",
     {'has secured': "Present Perfect belirli geçmiş tarihlerle ('in 2018') asla kullanılamaz.", 'secures': 'Geniş zaman geçmiş olayları anlatmaz.', 'had secured': 'Başka bir geçmiş olayla sıralama yapılmadığında Past Perfect gereksizdir.'}),
    ('How long ___ in your current managerial role?', 'have you been', ['were you', 'are you', 'did you be'],
     "'How long' asking about ongoing duration up to now requires Present Perfect.", "Günümüze kadar süren görev süresini sormak için Present Perfect ('have you been') kullanılır.",
     {'were you': 'Geçmişte tamamen sona ermiş bir görevin süresini sorar.', 'are you': "Genel durumu sorar ama süreci ('how long') kapsamaz.", 'did you be': "İngilizcede 'be' fiili soru yaparken 'did' almaz."}),
    ('The deployment failed because someone ___ an unmerged branch.', 'pushed', ['has pushed', 'pushes', 'is pushing'],
     "The context is a past incident ('failed'), requiring Past Simple for the root cause.", "Cümlenin ana fiili geçmiş zamanda ('failed') olduğu için sebep bildiren eylem de geçmiştedir.",
     {'has pushed': 'Geçmişte olan ve biten hatayı anlatırken Present Perfect zaman uyuşmazlığı yaratır.', 'pushes': 'Geniş zaman geçmişteki arızayı açıklamaz.', 'is pushing': 'Şimdiki zaman geçmiş arızanın sebebi olamaz.'}),
    ('We ___ already resolved twelve customer tickets today.', 'have', ['did', 'had', 'are'],
     "'Already' with an unfinished period ('today') takes Present Perfect auxiliary 'have'.", "'Already' ve tamamlanmamış 'today' zarfı ile Present Perfect yardımcı fiili 'have' kullanılır.",
     {'did': "Did ana fiil olarak 'resolved' ile birlikte yardımcı fiil olamaz.", 'had': 'Past Perfect geçmişte ikinci bir olaya referans gerektirir.', 'are': "'Are resolved' edilgen yapı oluşturur, 'we' öznesiyle bilet çözen etken özneye uymaz."}),
    ('Last Friday, our server ___ down for forty minutes.', 'went', ['has gone', 'goes', 'is going'],
     "'Last Friday' is a finished past time marker.", "'Last Friday' geçmişte kalmış kesin bir zamandır ve Past Simple gerektirir.",
     {'has gone': "Present Perfect 'last' ile başlayan bitmiş zaman ifadeleriyle kullanılmaz.", 'goes': 'Geniş zaman geçmiş olayı anlatamaz.', 'is going': 'Şimdiki zaman geçmişe uygulanamaz.'}),
    ('I ___ the client three times, but there is still no reply.', 'have called', ['called', 'call', 'was calling'],
     'Repeated attempts leading up to the present situation require Present Perfect.', 'Şu ana kadar tekrarlanan ve sonucu henüz alınamamış çabalar Present Perfect gerektirir.',
     {'called': 'Geçmişte kalmış tekil bir anı vurgular, güncel yanıtsızlıkla doğrudan bağ kurmaz.', 'call': 'Geniş zaman geçmiş aramaları bildirmez.', 'was calling': 'Geçmişte devam eden süreci anlatır, toplam sayıyı değil.'}),
    ('Two months ago, she ___ a promotion to senior engineer.', 'received', ['has received', 'receives', 'is receiving'],
     "'Ago' indicates a specific time elapsed in the past, demanding Past Simple.", "'Ago' geçmişte belirli bir süreyi işaret eder ve kesinlikle Past Simple gerektirir.",
     {'has received': "'Ago' kelimesiyle Present Perfect kesinlikle kullanılamaz.", 'receives': 'Geniş zaman geçmiş olayı ifade edemez.', 'is receiving': 'Şimdiki zaman geçmiş olaya uymaz.'}),
    ('So far, our department ___ ten new candidates this quarter.', 'has interviewed', ['interviewed', 'interviews', 'had interviewed'],
     "'So far' (şu ana kadar) strictly connects to the present, requiring Present Perfect.", "'So far' (şu ana dek) günümüze kadarki birikimi anlattığı için Present Perfect gerektirir.",
     {'interviewed': 'Geçmişte bitmiş ve kapalı bir dönemi ima eder.', 'interviews': 'Geniş zaman genel alışkanlıkları bildirir.', 'had interviewed': 'Geçmişteki başka bir noktadan önceyi anlatır.'}),
    ('Did you see the news release that ___ out this morning?', 'came', ['has come', 'comes', 'is coming'],
     "Within a Past Simple question ('Did you see'), the dependent clause matches past reference.", "'Did you see' geçmiş zaman bağlamında sabah çıkan bülten de Past Simple ('came') ile ifade edilir.",
     {'has come': "Geçmiş zaman çerçevesinde 'this morning' bittiyse Past Simple tercih edilir.", 'comes': 'Geniş zaman geçmişte yayımlanan habere uymaz.', 'is coming': 'Şimdiki zaman çıkmış bir haberi ifade etmez.'}),
    ('The engineering team ___ the database migration successfully.', 'has completed', ['completed yesterday', 'completes', 'was completing'],
     'An announcement of recent achievement without a specific past time marker uses Present Perfect.', 'Zaman belirtilmeden duyurulan taze başarılar ve tamamlanmış projeler Present Perfect ile verilir.',
     {'completed yesterday': "'Yesterday' olmadan tek başına şıkta yer alması yapıyı bozar.", 'completes': 'Geniş zaman projenin bittiğini değil her zaman bittiğini söyler.', 'was completing': 'Sürecin yarım kaldığını ima eder.'}),
    ('He ___ the meeting early because he had a doctor appointment.', 'left', ['has left', 'leaves', 'is leaving'],
     "The explanation provides a specific past reason ('had'), calling for Past Simple.", "Yan cümle geçmiş zamandadır ('had a doctor appointment'), bu yüzden ana eylem de Past Simple olmalıdır.",
     {'has left': 'Geçmiş gerekçeyle Present Perfect zaman uyumu bozar.', 'leaves': 'Geniş zaman geçmişte ayrılışı açıklayamaz.', 'is leaving': 'Şimdiki zaman geçmişe uymaz.'}),
    ('Ever since they founded the company, they ___ open communication.', 'have encouraged', ['encouraged', 'encourage', 'are encouraging'],
     "'Ever since' clause triggers Present Perfect in the main clause.", "'Ever since' ile başlayan yan cümle ana cümlede Present Perfect gerektirir.",
     {'encouraged': 'Past Simple sürecin kesilip bittiğini ima eder.', 'encourage': "Geniş zaman 'ever since' ile başlayan süreci karşılamaz.", 'are encouraging': 'Şimdiki zaman uzun süreli kurumsal ilkeyi tam vermez.'}),
    ('What ___ during your previous internship at the bank?', 'did you do', ['have you done', 'do you do', 'had you done'],
     "'Previous' points to a completed period in the past.", "'Previous' bitmiş geçmiş bir dönemi gösterdiğinden Past Simple ('did you do') gerektirir.",
     {'have you done': 'Present Perfect bitmiş staj dönemi için kullanılmaz.', 'do you do': 'Geniş zaman şu anki stajı sorar.', 'had you done': 'Kıyaslanan ikinci bir geçmiş olay yoktur.'}),
    ('This is the most challenging bug I ___ ever encountered.', 'have', ['did', 'was', 'had'],
     "Superlative expressions ('the most...') take Present Perfect ('have ever').", "'The most...' gibi üstünlük bildiren yapılardan sonra deneyim için Present Perfect ('have ever') kullanılır.",
     {'did': "'Did ever' deneyim kalıbı olarak kullanılmaz.", 'was': "Was yardımcı fiili 'encountered' ile etken deneyim yapamaz.", 'had': 'Past Perfect geçmişte belirli bir döneme kadar olan tecrübeler içindir.'}),
], 'Choose the correct tense (Present Perfect vs Past Simple) for the context:', 'Cümledeki zaman ipucuna ve eylemin tamamlanma durumuna göre doğru kipi seçiniz.')

# grammar.b1.present-perfect-continuous-duration
add_lesson("grammar.b1.present-perfect-continuous-duration", "pres-perf-cont", [
    ('She is exhausted because she ___ code for six straight hours.', 'has been writing', ['has written', 'wrote', 'is writing'],
     'Present Perfect Continuous highlights the ongoing duration of an activity leading to a present result.', 'Şu anki yorgunluğun sebebini kesintisiz devam eden süreçle açıklamak için Present Perfect Continuous kullanılır.',
     {'has written': 'Present Perfect Simple tamamlanma ve sonuca odaklanır, sürecin yorgunluğuna değil.', 'wrote': 'Geçmiş zaman eylemin şu anki durumla bağını zayıflatır.', 'is writing': 'Şu anki süreci belirtir ama 6 saatlik geçmiş süreyi kapsamaz.'}),
    ('How long ___ on this optimization algorithm?', 'have you been working', ['do you work', 'did you work', 'are you working'],
     "'How long' combined with an ongoing action requires Present Perfect Continuous.", "'How long' sorusu devam eden bir sürecin süresini öğrenmek için Present Perfect Continuous ister.",
     {'do you work': 'Geniş zaman süreci değil alışkanlığı sorar.', 'did you work': 'Bitmiş bir işin süresini sorar.', 'are you working': "Şimdiki zaman 'how long' ile süre sormada standart değildir."}),
    ('They ___ with suppliers since early this morning.', 'have been negotiating', ['negotiate', 'are negotiating', 'negotiated'],
     "'Since' with an active, continuous process takes Present Perfect Continuous.", "'Since' ile başlayan ve sabahtan beri süren aktif pazarlık için Present Perfect Continuous uygundur.",
     {'negotiate': 'Geniş zaman sabahtan beri süren eylemi anlatamaz.', 'are negotiating': 'Şu anı anlatır ama sabahtan başlayan süreci vermez.', 'negotiated': 'Geçmiş zaman eylemin bittiğini söyler.'}),
    ('The DevOps team ___ the server metrics all afternoon.', 'has been monitoring', ['has monitored', 'monitored', 'monitors'],
     "'All afternoon' indicates continuous, unbroken activity.", "'All afternoon' kesintisiz bir aktiviteyi vurgular.",
     {'has monitored': 'Tamamlanmışlık hissi verir.', 'monitored': 'Sadece geçmişte kaldığını söyler.', 'monitors': 'Genel rutini ifade eder.'}),
    ('Why are your hands dirty? I ___ the office bicycles.', 'have been repairing', ['have repaired', 'repaired', 'repair'],
     "Visible present evidence ('hands dirty') points to a recently ongoing physical activity.", 'Gözle görülür fiziki kanıt az önce devam eden aktivitenin Present Perfect Continuous ile verilmesini gerektirir.',
     {'have repaired': 'Bitmiş olma sonucuna odaklanır, kirli eller sürecin kanıtıdır.', 'repaired': 'Geçmişte kalmış eylemdir.', 'repair': 'Geniş zamandır.'}),
    ('It ___ continuously since midnight, causing local flooding.', 'has been raining', ['is raining', 'rained', 'rains'],
     "'Since midnight' requires Present Perfect Continuous for weather phenomena.", "'Since midnight' gece yarısından beri devam eden yağışı bu zamanla anlatır.",
     {'is raining': 'Şu anı anlatır ama gece yarısından beri olan süreci vermez.', 'rained': 'Yağmurun dindiğini ima eder.', 'rains': 'Genel iklim özelliğidir.'}),
    ('We ___ to contact their support desk for two hours without success.', 'have been trying', ['tried', 'try', 'are trying'],
     'Emphasizing prolonged, frustrating effort over a duration of time.', 'İki saattir devam eden ısrarlı ve sonuçsuz çaba sürecini vurgular.',
     {'tried': 'Geçmişte denenip bırakıldığını ima eder.', 'try': 'Geniş zamandır.', 'are trying': "Süreyi ('for two hours') geçmişten bugüne bağlamaz."}),
    ('The engineers ___ the crash logs, but the root cause remains elusive.', 'have been analyzing', ['analyzed', 'analyze', 'are analyzing'],
     'The ongoing effort is contrasted with an unresolved current outcome.', 'Süren analiz çabası henüz çözülememiş durumla karşılaştırılmaktadır.',
     {'analyzed': 'Analizin bittiğini ima eder.', 'analyze': 'Genel rutindir.', 'are analyzing': 'Sürecin geçmişten gelen derinliğini vermez.'}),
    ('He ___ Spanish lessons for three months and can now hold a conversation.', 'has been taking', ['took', 'takes', 'is taking'],
     "'For three months' indicates an ongoing learning journey up to the present.", 'Üç aydır süregelen ve devam eden ders süreci Present Perfect Continuous ile verilir.',
     {'took': 'Derslerin bittiğini gösterir.', 'takes': 'Genel alışkanlıktır.', 'is taking': 'Süreç başlangıcını geçmişe bağlamada eksik kalır.'}),
    ('Our client ___ about delivery delays throughout the week.', 'has been complaining', ['complained', 'complains', 'is complaining'],
     'Repeated, irritating actions occurring throughout a period take this continuous form.', 'Hafta boyunca tekrarlanan şikayetler bu zaman kipiyle aktarılır.',
     {'complained': 'Haftanın bittiğini ve şikayetin kesildiğini ima eder.', 'complains': 'Genel karakter özelliğine dönüştürür.', 'is complaining': 'Şu anki tekil şikayete odaklar.'}),
    ('I ___ on this spreadsheet for forty minutes; my eyes hurt.', 'have been staring', ['have stared', 'stared', 'am staring'],
     'Physical strain resulting from continuous focus.', 'Kesintisiz odaklanmanın getirdiği göz yorgunluğunu anlatan süreçtir.',
     {'have stared': 'Tamamlanmış eylemdir.', 'stared': 'Geçmiş zamandır.', 'am staring': '40 dakikalık birikimi yansıtmaz.'}),
    ('How long ___ to that business podcast?', 'have you been listening', ['did you listen', 'do you listen', 'are you listening'],
     "'Listen' is dynamic and takes continuous for ongoing duration.", "'Listen' dinamik fiildir ve süren eylem için continuous alır.",
     {'did you listen': 'Dinlemenin bittiğini söyler.', 'do you listen': 'Genel alışkanlığı sorar.', 'are you listening': 'Süreyi geçmişten bugüne bağlamaz.'}),
    ('The team ___ user feedback to refine the user interface.', 'has been gathering', ['gathered', 'gathers', 'is gathered'],
     'Ongoing data collection leading toward future release.', 'Arayüzü geliştirmek için devam eden veri toplama süreci.',
     {'gathered': 'Toplama işinin bittiğini gösterir.', 'gathers': 'Geniş zamandır.', 'is gathered': 'Edilgen yapıdır, etken özneye uymaz.'}),
    ('She ___ for a suitable flight deal all morning.', 'has been searching', ['searched', 'searches', 'is searching'],
     "'All morning' combined with ongoing effort.", 'Tüm sabah süren arayış.',
     {'searched': 'Aramanın bittiğini ima eder.', 'searches': 'Rutin bildirir.', 'is searching': 'Tüm sabahın süresini bağlamaz.'}),
    ('We ___ with this legacy system for far too long.', 'have been struggling', ['struggled', 'struggle', 'are struggling'],
     'Emphasizing long-term ongoing frustration.', 'Uzun süredir devam eden kurumsal zorlanmayı anlatır.',
     {'struggled': 'Zorlanmanın bittiğini ima eder.', 'struggle': 'Geniş zamandır.', 'are struggling': 'Geçmişten gelen birikimi eksik bırakır.'}),
    ('The marketing department ___ new campaign ideas since Monday.', 'has been brainstorming', ['brainstormed', 'brainstorms', 'is brainstorming'],
     "'Since Monday' with an active team effort.", 'Pazartesiden beri süregelen fikir fırtınası.',
     {'brainstormed': 'Geçmişte kalmış tekil toplantıdır.', 'brainstorms': 'Rutin bildirir.', 'is brainstorming': 'Pazartesi başlangıç noktasını bağlamaz.'}),
    ('He is sweaty because he ___ in the gym.', 'has been running', ['ran', 'runs', 'is running'],
     'Present physical state (sweaty) resulting from recent vigorous activity.', 'Terli olma fiziksel durumu yeni bitmiş veya süren koşu aktivitesinin sonucudur.',
     {'ran': 'Geçmişte kalmış eylemdir.', 'runs': 'Genel rutindir.', 'is running': 'Şu an salonda koştuğunu söyler, ama konuşmacı karşımızdadır.'}),
    ('They ___ the bridge for eighteen months, and it opens next month.', 'have been building', ['built', 'build', 'were building'],
     '18 months of ongoing construction leading to an upcoming opening.', 'Gelecek ay açılacak köprünün 18 aydır süren yapım aşaması.',
     {'built': 'Köprünün zaten bittiğini söyler.', 'build': 'Geniş zamandır.', 'were building': 'Geçmişte kalmış yarım eylemi ima eder.'}),
    ('I ___ about changing my career path recently.', 'have been thinking', ['thought', 'think', 'am thought'],
     "'Recently' with continuous deliberation.", 'Son zamanlarda devam eden kariyer düşüncesi.',
     {'thought': 'Düşüncenin geçmişte kalıp bittiğini ima eder.', 'think': 'Genel kanaattir.', 'am thought': 'Edilgen yapıdır.'}),
    ('How long ___ English with FluentAI?', 'have you been learning', ['did you learn', 'do you learn', 'had you learned'],
     "A natural question for a language learner's ongoing journey.", 'Dil öğrenme yolculuğunun süresini soran standart kalıp.',
     {'did you learn': 'Öğrenmenin bittiğini ima eder.', 'do you learn': 'Süreç sormaz.', 'had you learned': 'Geçmişte bir noktadan önceki geçmişi sorar.'}),
], 'Choose the correct form of Present Perfect Continuous for duration:', 'Eylemin süresini ve kesintisiz devam ettiğini anlatan doğru yapıyı seçiniz.')

# grammar.b1.past-continuous-interrupted-actions
add_lesson("grammar.b1.past-continuous-interrupted-actions", "past-cont-inter", [
    ('While we ___ the security update, the power went out.', 'were installing', ['installed', 'are installing', 'had installed'],
     "'While' sets up the continuous background action interrupted by a sudden event.", "'While' geçmişte devam eden arka plan sürecini (Past Continuous) kurar.",
     {'installed': 'Past Simple anlık eylemler içindir, arka plan sürecini vermez.', 'are installing': 'Şimdiki zaman geçmişteki elektrik kesintisine bağlanamaz.', 'had installed': 'Past Perfect kesintiden önce kurulumun bittiğini söyler.'}),
    ('She was giving a presentation when the fire alarm ___ .', 'rang', ['was ringing', 'rings', 'has rung'],
     "The interrupting action in the 'when' clause takes Past Simple.", "'When' ile gelen ve devam eden sunumu bölen anlık eylem Past Simple ('rang') alır.",
     {'was ringing': 'İki eylemin aynı anda uzun süre devam ettiğini ima eder.', 'rings': 'Geniş zaman geçmiş sunumla uyumsuzdur.', 'has rung': 'Present Perfect geçmiş zaman bağlamında kullanılamaz.'}),
    ('What ___ when the system alert was triggered?', 'were you doing', ['did you do', 'are you doing', 'have you done'],
     'Asking about the ongoing activity at the precise moment of an interruption.', 'Uyarı verildiği anda kişinin ne yapmakta olduğunu sorar.',
     {'did you do': 'Uyarının ardından ne yaptığını sorar, o andaki eylemi değil.', 'are you doing': 'Şu anı sorar.', 'have you done': 'Present Perfect geçmişteki anlık kesintiye uymaz.'}),
    ('I ___ down the street when I ran into our former CTO.', 'was walking', ['walked', 'am walking', 'have walked'],
     'Continuous background action interrupted by a chance encounter.', 'Eski CTO ile karşılaşma anında devam eden yürüme eylemi.',
     {'walked': 'Yürümenin anlık bir eylem gibi algılanmasına yol açar.', 'am walking': 'Şimdiki zamandır.', 'have walked': 'Present Perfect geçmiş karşılaşmayla bağlanmaz.'}),
    ('While the developers ___ code, the QA team prepared test suites.', 'were writing', ['wrote', 'are writing', 'have written'],
     'Two parallel actions occurring simultaneously in the past.', 'Geçmişte aynı anda paralel devam eden eylemlerden biri.',
     {'wrote': 'Süreci Past Continuous kadar canlı vermez.', 'are writing': 'Şimdiki zaman geçmişe uymaz.', 'have written': 'Present Perfect geçmişle bağdaşmaz.'}),
    ('He was driving to the conference when a tyre ___ .', 'punctured', ['was puncturing', 'punctures', 'has punctured'],
     'A sudden interruption during a journey.', 'Yolculuk sırasında aniden gerçekleşen lastik patlaması Past Simple gerektirir.',
     {'was puncturing': 'Lastik patlamasının uzun sürdüğünü ima eder.', 'punctures': 'Geniş zamandır.', 'has punctured': 'Present Perfect geçmiş hikayeye uymaz.'}),
    ('At 3 PM yesterday, the design team ___ new mockups.', 'was reviewing', ['reviewed', 'reviews', 'has reviewed'],
     "A specific point in time in the past ('at 3 PM yesterday') with an action in progress.", "Dün saat 3'te tam o anda devam etmekte olan inceleme eylemi.",
     {'reviewed': "Eylemin saat 3'te bittiğini ima eder.", 'reviews': 'Geniş zamandır.', 'has reviewed': 'Present Perfect kesin geçmiş saatle kullanılmaz.'}),
    ('The phone rang three times while I ___ a shower.', 'was taking', ['took', 'am taking', 'have taken'],
     "'While' clause with a continuous personal activity.", 'Duş alma sürecinde telefonun çalması.',
     {'took': 'While ile süreç yerine anlık hareket bildirir.', 'am taking': 'Şimdiki zamandır.', 'have taken': 'Present Perfect geçmişle uyumsuzdur.'}),
    ('They ___ an intense debate when the moderator stepped in.', 'were having', ['had', 'are having', 'have had'],
     'Interrupted ongoing debate.', 'Moderatörün araya girmesiyle bölünen tartışma.',
     {'had': 'Tartışmanın bittiğini ima eder.', 'are having': 'Şu anı anlatır.', 'have had': 'Present Perfect geçmiş olaya uymaz.'}),
    ('It ___ heavily when the flight finally landed in Berlin.', 'was snowing', ['snowed', 'snows', 'has snowed'],
     'Weather setting the scene at the moment of landing.', 'Uçağın iniş anında hava durumunun arka plan tasviri.',
     {'snowed': 'İnişle aynı anda başlayıp bittiği izlenimi verir.', 'snows': 'Geniş zamandır.', 'has snowed': 'Present Perfect geçmişe uymaz.'}),
    ('While you ___ the email, did you notice the spelling error?', 'were drafting', ['drafted', 'are drafting', 'have drafted'],
     'Continuous activity during which a discovery was made.', 'E-posta taslağını hazırlama sürecinde hatanın fark edilip edilmediği.',
     {'drafted': 'Süreci arka plan olarak vurgulamaz.', 'are drafting': 'Şimdiki zamandır.', 'have drafted': 'Did sorusuyla uyumsuzdur.'}),
    ('The server crashed while our DevOps engineer ___ the backup script.', 'was running', ['ran', 'runs', 'has run'],
     'An error occurring right in the middle of executing a script.', 'Yedekleme betiği çalışırken sunucunun çökmesi.',
     {'ran': 'Betiğin çalıştırılıp bittiği izlenimi doğurur.', 'runs': 'Geniş zamandır.', 'has run': 'Present Perfect geçmiş çökmeyle uyumsuzdur.'}),
    ('Nobody ___ attention when the director announced the schedule change.', 'was paying', ['paid', 'pays', 'has paid'],
     'Ongoing state of inattention when an event occurred.', 'Duyuru yapıldığı anda kimsenin dikkat etmiyor oluşu.',
     {'paid': 'Anlık bir eylem gibi kalır, o anki genel dikkatsizlik atmosferini vermez.', 'pays': 'Geniş zamandır.', 'has paid': 'Present Perfect geçmişle uyumsuzdur.'}),
    ('I ___ for the bus when the rain suddenly stopped.', 'was waiting', ['waited', 'am waiting', 'have waited'],
     'Waiting was interrupted or superseded by the rain stopping.', 'Yağmurun durduğu anda durakta beklemekte olma hali.',
     {'waited': 'Süreç hissi vermez.', 'am waiting': 'Şu anı anlatır.', 'have waited': 'Present Perfect geçmişle uyumsuzdur.'}),
    ('While we ___ dinner, the courier delivered the parcel.', 'were eating', ['ate', 'are eating', 'have eaten'],
     'Meal in progress interrupted by a delivery.', 'Yemek yeme sürecinde kuryenin paketi getirmesi.',
     {'ate': 'Yemek yeme anlık bir hareket değildir.', 'are eating': 'Şimdiki zamandır.', 'have eaten': 'Present Perfect geçmişle uyumsuzdur.'}),
    ('What were they discussing when you ___ the conference room?', 'entered', ['were entering', 'enter', 'have entered'],
     'The sudden event of entering interrupting their discussion.', 'Odaya girme anlık eylemi Past Simple gerektirir.',
     {'were entering': 'Odaya girme sürecinin çok uzun sürdüğünü ima eder.', 'enter': 'Geniş zamandır.', 'have entered': 'Past Continuous sorusunda yan cümleye uymaz.'}),
    ('The light went off while she ___ the contract terms.', 'was reviewing', ['reviewed', 'reviews', 'is reviewing'],
     'Continuous contract review interrupted by blackout.', 'Işıkların gittiği esnada devam eden sözleşme incelemesi.',
     {'reviewed': 'İncelemenin anlık olduğu hissini verir.', 'reviews': 'Geniş zamandır.', 'is reviewing': 'Şimdiki zaman geçmişe uymaz.'}),
    ('He hurt his back while he ___ the server rack into place.', 'was lifting', ['lifted', 'lifts', 'has lifted'],
     'Physical action in progress when injury occurred.', 'Sunucu dolabını kaldırırken belini incitmesi.',
     {'lifted': 'Kaldırma işinin hemen bittiğini ima eder.', 'lifts': 'Geniş zamandır.', 'has lifted': 'Geçmiş sakatlanmaya uymaz.'}),
    ('The customer was shouting while the support agent ___ calm.', 'was remaining', ['remained', 'remains', 'is remaining'],
     'Two simultaneous continuous states in the past.', 'Müşteri bağırırken destek temsilcisinin sakin kalmaya devam etmesi.',
     {'remained': 'Anlık bir tepki gibi kalır.', 'remains': 'Geniş zamandır.', 'is remaining': 'Şimdiki zamandır.'}),
    ('As the sun ___ , the hikers reached the summit shelter.', 'was setting', ['set', 'sets', 'has set'],
     'Background natural phenomenon as an event concluded.', 'Güneş batarken dağcıların zirveye ulaşması.',
     {'set': 'Güneşin bir anda battığı izlenimini verir.', 'sets': 'Geniş zamandır.', 'has set': 'Geçmiş hikayeye uymaz.'}),
], 'Choose the correct past form for background actions and interruptions:', 'Geçmişte devam eden arka plan eylemleri ve onları bölen anlık olaylar için doğru kipi seçiniz.')

# grammar.b1.used-to-vs-be-used-to
add_lesson("grammar.b1.used-to-vs-be-used-to", "used-to-vs-be", [
    ('I ___ work in a traditional bank, but now I work for a fintech startup.', 'used to', ['am used to', 'use to', 'was used to'],
     "'Used to + base verb' describes a past state or habit that is no longer true.", "Geçmişte var olan ancak artık geçerli olmayan durumlar için 'used to + yalın fiil' kullanılır.",
     {'am used to': "'Am used to' ardından fiilin -ing almasını gerektirir ve alışkın olmayı ifade eder.", 'use to': "Geçmiş zaman için 'd' harfi eksiktir.", 'was used to': "'Was used to' geçmişte alışkın olmayı ifade eder, geçmişteki mesleği değil."}),
    ('She lives in London now, so she ___ on the left side of the road.', 'is used to driving', ['used to drive', 'used to driving', 'uses to drive'],
     "'Be used to + -ing' expresses being accustomed to something in the present.", "Şu anki bir duruma alışkın olmayı anlatmak için 'is used to + V-ing' kullanılır.",
     {'used to drive': 'Geçmişte sürerdi ama artık sürmüyor anlamına gelir.', 'used to driving': "'Used to' geçmiş alışkanlık kipinde fiil -ing alamaz.", 'uses to drive': "İngilizcede geniş zamanda 'uses to' kalıbı yoktur."}),
    ('Did you ___ live near the main university campus?', 'use to', ['used to', 'used', 'be used to'],
     "In questions with 'Did', the auxiliary takes the past tense, leaving 'use to'.", "'Did' ile yapılan sorularda geçmiş zaman eki yardımcı fiile geçtiğinden 'use to' kullanılır.",
     {'used to': "Soru cümlesinde 'did' varken fiil yalın kalmalıdır ('use to').", 'used': "'To' eksiktir.", 'be used to': 'Alışkın olma anlamı katıp sorunun bağlamına uymaz.'}),
    ('Working late hours is tough, but our operations team ___ it.', 'is used to', ['used to', 'use to', 'used to be'],
     "'Be used to + noun/pronoun' means accustomed to a condition.", "'Be used to' bir duruma veya zorluğa alışkın olmayı ifade eder.",
     {'used to': "Ardından yalın fiil gerektirir, zamir ('it') ile tek başına bitmez.", 'use to': 'Yalın haldedir.', 'used to be': 'Geçmişte öyleydi anlamına gelir.'}),
    ('He ___ smoke twenty cigarettes a day before quitting last year.', 'used to', ['is used to', 'used to smoking', 'was used to'],
     'Past discontinued habit.', "Geçmişte bırakılmış alışkanlık 'used to + yalın fiil' ile anlatılır.",
     {'is used to': 'Şu an alışkın olmayı anlatır.', 'used to smoking': 'Geçmiş alışkanlık yapısında fiil -ing almaz.', 'was used to': 'Alışkın olduğunu söyler, eylemi yaptığını değil.'}),
    ('They are still not ___ the new corporate communication software.', 'used to using', ['used to use', 'use to use', 'used to'],
     "Negative 'be used to' requiring gerund for unfamiliarity.", "Yeni yazılımı kullanmaya henüz alışamadıklarını anlatan 'not used to + V-ing' yapısı.",
     {'used to use': 'Eskiden kullanırlardı ama artık kullanmıyorlar anlamına gelir.', 'use to use': 'Dilbilgisel olarak hatalıdır.', 'used to': 'Fiil olmadan eksik kalır.'}),
    ('We ___ have weekly team lunches before the pandemic started.', 'used to', ['are used to', 'used to having', 'use to'],
     'Discontinued group habit before a past event.', 'Pandemi öncesi yapılan eski alışkanlık.',
     {'are used to': 'Şu an alışkın olmayı anlatır.', 'used to having': 'Geçmiş alışkanlık yapısında -ing kullanılmaz.', 'use to': 'Geçmiş zaman ekini almamıştır.'}),
    ('It took him three months to ___ waking up at 6 AM every day.', 'get used to', ['used to', 'use to', 'be used'],
     "'Get used to + -ing' expresses the process of becoming accustomed to something.", "'Get used to' bir duruma alışma sürecini anlatır.",
     {'used to': "Süreç bildiren 'get' fiili olmadan süreç anlamı kurulamaz.", 'use to': 'Yalın haldedir.', 'be used': 'Edilgen anlam taşır.'}),
    ('There ___ be an old cinema on this corner of the street.', 'used to', ['is used to', 'was used to', 'used to being'],
     "'There used to be' is the standard pattern for past existence.", "Geçmişte var olan mekanlar için 'There used to be' kalıbı kullanılır.",
     {'is used to': 'Mekan alışkanlık kazanamaz.', 'was used to': 'Hatalı yapıdır.', 'used to being': 'Gereksiz gerund kullanımıdır.'}),
    ('Are you ___ with such large, cross-functional teams?', 'used to collaborating', ['used to collaborate', 'use to collaborate', 'used to collaboration of'],
     "Question form of 'be used to + -ing'.", "'Böyle büyük ekiplerle çalışmaya alışkın mısınız?' sorusunda 'used to + V-ing' gerekir.",
     {'used to collaborate': "'Are you' ile başlarken geçmiş alışkanlık kalıbı kurulamaz.", 'use to collaborate': 'Dilbilgisi hatasıdır.', 'used to collaboration of': 'Hatalı edat kullanımıdır.'}),
    ("She didn't ___ like spicy food, but now she loves it.", 'use to', ['used to', 'using to', 'be used to'],
     "Negative past habit with 'didn't' requires base form 'use to'.", "'Didn't' ile olumsuz geçmiş alışkanlık yaparken 'use to' kullanılır.",
     {'used to': "'Didn't' varken 'used' yazılamaz.", 'using to': 'Hatalı formdur.', 'be used to': 'Alışkın olmak anlamına gelir.'}),
    ('After years in customer service, he ___ rude clients calmly.', 'is used to handling', ['used to handle', 'use to handle', 'used to handling'],
     'Present professional tolerance and habituation.', 'Yılların tecrübesiyle kaba müşterileri yönetmeye alışkın olma durumu.',
     {'used to handle': 'Eskiden yönetirdi ama artık yönetmiyor anlamına gelir.', 'use to handle': 'Hatalı formdur.', 'used to handling': "'Be' fiili eksiktir."}),
    ('Our company ___ offer remote work, but now everyone works from home.', 'never used to', ['is never used to', 'used never to being', 'never use to'],
     'Past negation of habit.', 'Eskiden uzaktan çalışma sunulmadığını anlatan geçmiş durum.',
     {'is never used to': 'Şirketin alışkın olmadığını söyler.', 'used never to being': 'Hatalı dizilimdir.', 'never use to': 'Geçmiş zaman eki eksiktir.'}),
    ('I will never ___ the freezing temperatures of Montreal winters.', 'get used to', ['used to', 'use to', 'be use to'],
     "'Get used to + noun' with future modal 'will'.", "Gelecekte alışma sürecini ifade eden 'get used to'.",
     {'used to': "'Will' sonrasında 'used' geçmiş kipi gelemez.", 'use to': 'Tek başına alışma sürecini vermez.', 'be use to': 'Hatalı yapı.'}),
    ('He ___ ride a bicycle to work every single day.', 'used to', ['is used to', 'uses to', 'used to riding'],
     'Simple past routine.', 'Eskiden her gün işe bisikletle giderdi.',
     {'is used to': 'Şu an alışkın olduğunu söyler.', 'uses to': 'İngilizcede geniş zamanda kullanılmaz.', 'used to riding': "'Used to' sonrasında yalın fiil gerekir."}),
    ('Are you getting ___ the new agile sprint cadence?', 'used to', ['use to', 'used', 'to used'],
     "'Get used to' pattern with ongoing aspect.", 'Yeni sprint temposuna alışıyor musunuz?',
     {'use to': "'Getting used to' kalıbında 'd' düşmez.", 'used': "'To' edatı eksiktir.", 'to used': 'Hatalı kelime sırasıdır.'}),
    ('My grandfather ___ tell fascinating stories about maritime trade.', 'used to', ['is used to', 'was used to', 'use to'],
     'Past recurring habit of an individual.', 'Dedemin eskiden anlattığı deniz ticareti hikayeleri.',
     {'is used to': 'Şu an alışkın olduğunu söyler.', 'was used to': 'Hikaye anlatmaya alışkındı anlamına gelir.', 'use to': 'Geçmiş zaman eki eksiktir.'}),
    ("She couldn't ___ the noise in the open-plan office.", 'get used to', ['used to', 'be used', 'use to'],
     'Inability to adapt to a situation.', 'Açık ofis gürültüsüne bir türlü alışamadı.',
     {'used to': "'Could not' sonrasında yalın 'get used to' gerekir.", 'be used': 'Edilgen kalır.', 'use to': 'Alışma sürecini vermez.'}),
    ('I ___ drink green tea, but now I prefer it over coffee.', "didn't use to", ["didn't used to", "wasn't used to", 'used to not'],
     'Standard negative form in modern English.', 'Eskiden yeşil çay içmezdim.',
     {"didn't used to": "'Didn't' sonrasında 'd' yazılmaz.", "wasn't used to": 'Alışkın değildim anlamına gelir.', 'used to not': 'Standart olmayan biçimdir.'}),
    ('Because of his night shifts, he ___ sleeping during the daytime.', 'is used to', ['used to', 'use to', 'uses to'],
     'Current adaptation to sleeping by day.', 'Gece vardiyaları sebebiyle gündüz uyumaya alışkındır.',
     {'used to': 'Eskiden gündüz uyurdu ama artık uyumuyor anlamına gelir.', 'use to': 'Yalın haldedir.', 'uses to': 'Böyle bir geniş zaman kipi yoktur.'}),
], "Choose between 'used to + base verb' (past habit) and 'be used to + -ing' (accustomed to):", "Geçmişteki alışkanlıklar ('used to') ile alışkın olma durumunu ('be used to + -ing') ayırt ediniz.")

# grammar.b1.future-arrangements-present-continuous
add_lesson("grammar.b1.future-arrangements-present-continuous", "fut-arrang", [
    ('I ___ the regional sales director tomorrow at 10 AM in the boardroom.', 'am meeting', ['meet', 'will meet', 'am met'],
     'A confirmed arrangement with a specific time and location uses Present Continuous.', 'Yeri ve saati kesinleşmiş randevular için Present Continuous kullanılır.',
     {'meet': 'Geniş zaman resmi tarifeler içindir, kişisel randevularda kullanılmaz.', 'will meet': 'Konuşma anında verilen ani kararları veya tahminleri anlatır.', 'am met': 'Edilgen yapıdır, kişiyle buluşulacağını değil karşılanacağını söyler.'}),
    ('Our team ___ to Berlin next Tuesday for the tech summit.', 'is flying', ['flies', 'will fly', 'has flown'],
     'A planned future travel arrangement with tickets already booked.', 'Biletleri alınmış ve planlanmış seyahatler için Present Continuous tercih edilir.',
     {'flies': "Uçuş tarifesini belirtseydi olurdu, ekibin seyahat planı için 'is flying' standarttır.", 'will fly': 'Gelecek tahmini gibi kalır, planlanmış organizasyonu yansıtmaz.', 'has flown': 'Geçmişte uçtuğunu söyler.'}),
    ("What ___ this Friday evening? We're organizing a farewell dinner.", 'are you doing', ['do you do', 'will you do', 'did you do'],
     "Asking about someone's existing plans or arrangements for a specific future evening.", 'Cuma akşamı için kesinleşmiş bir planın olup olmadığını sorar.',
     {'do you do': 'Genel olarak her cuma ne yapıldığını sorar.', 'will you do': 'Gelecekte ne yapmaya karar vereceğini sorar.', 'did you do': 'Geçmişi sorar.'}),
    ('She ___ a new product demo to key investors on Thursday afternoon.', 'is presenting', ['presents', 'will present', 'presented'],
     'Scheduled professional presentation.', 'Perşembe öğleden sonra yatırımcılara yapılacak planlı sunum.',
     {'presents': 'Genel rutini söyler.', 'will present': 'Daha ziyade tahmin bildirir.', 'presented': 'Geçmiş zamandır.'}),
    ('We ___ the new mobile release tonight at midnight.', 'are deploying', ['deploy', 'will deploy', 'deployed'],
     'A fixed operational deployment schedule.', 'Bu gece yarısı için kararlaştırılmış canlıya alma planı.',
     {'deploy': 'Geniş zamandır.', 'will deploy': 'Anlık karar veya niyet bildirir.', 'deployed': 'Geçmiş zamandır.'}),
    ('The CEO ___ the Istanbul branch next Monday.', 'is visiting', ['visits', 'will visit', 'visited'],
     'Executive calendar schedule.', "CEO'nun pazartesi günkü kesinleşmiş şube ziyareti.",
     {'visits': 'Rutin ziyarettir.', 'will visit': 'Ziyaret edeceğini öngörür.', 'visited': 'Geçmiş zamandır.'}),
    ('They ___ married in Cappadocia next September.', 'are getting', ['get', 'will get', 'got'],
     'Major personal milestone with planned date and venue.', 'Tarihi ve yeri belli düğün planı.',
     {'get': 'Geniş zamandır.', 'will get': 'Tahminidir.', 'got': 'Geçmişte evlendiklerini söyler.'}),
    ('I ___ the dentist this afternoon for my annual checkup.', 'am seeing', ['see', 'will see', 'saw'],
     'Confirmed personal medical appointment.', 'Bugün öğleden sonraki diş randevusu.',
     {'see': "Geniş zamanda 'görmek' durum fiilidir; randevu için 'am seeing' kullanılır.", 'will see': 'Randevu planını vermez.', 'saw': 'Geçmiş zamandır.'}),
    ('Which hotel ___ at during your stay in Amsterdam?', 'are you staying', ['do you stay', 'will you stay', 'did you stay'],
     'Inquiring about booked accommodation.', 'Rezervasyonu yapılmış oteli sormak için Present Continuous kullanılır.',
     {'do you stay': 'Her gittiğinde nerede kaldığını sorar.', 'will you stay': 'O anda karar vermesini ister.', 'did you stay': 'Geçmiş konaklamayı sorar.'}),
    ('Our department ___ a retrospective workshop tomorrow morning.', 'is holding', ['holds', 'will hold', 'held'],
     'Calendar-scheduled internal team session.', 'Yarın sabah yapılacak planlı retrospektif çalıştayı.',
     {'holds': 'Geniş zamandır.', 'will hold': 'Tahminidir.', 'held': 'Geçmiş zamandır.'}),
    ('He ___ dinner for his colleagues tonight.', 'is cooking', ['cooks', 'will cook', 'cooked'],
     'Prearranged evening hosting plan.', 'Bu akşam meslektaşları için yemek yapma planı.',
     {'cooks': 'Genel yemek yapma alışkanlığıdır.', 'will cook': 'Konuşma anında verilmiş karardır.', 'cooked': 'Geçmiş zamandır.'}),
    ('We ___ lunch with the client at that Italian bistro at 1 PM.', 'are having', ['have', 'will have', 'had'],
     'Time and place confirmed lunch date.', "Saat 1'deki planlı müşteri yemeği.",
     {'have': 'Geniş zamandır.', 'will have': 'Anlık teklif veya tahmindir.', 'had': 'Geçmiş zamandır.'}),
    ('She ___ the company at the end of this month to pursue her MBA.', 'is leaving', ['leaves', 'will leave', 'left'],
     'Formal departure date officially arranged.', 'Ay sonunda şirketten ayrılacağı kesinleşmiş plan.',
     {'leaves': "Resmi tarife dili dışında kişisel ayrılış planında 'is leaving' standarttır.", 'will leave': 'Ayrılacağını tahmin eder.', 'left': 'Zaten ayrıldığını söyler.'}),
    ('The contractors ___ the office refurbishment on Saturday.', 'are starting', ['start', 'will start', 'started'],
     'Scheduled weekend project start.', 'Cumartesi günü başlayacak ofis yenileme planı.',
     {'start': 'Geniş zamandır.', 'will start': 'Başlayacaklarını tahmin eder.', 'started': 'Geçmiş zamandır.'}),
    ('I ___ tennis with Alex tomorrow after work.', 'am playing', ['play', 'will play', 'played'],
     'Social arrangement between two people.', 'Mesai sonrası tenis oynama sözleşmesi.',
     {'play': 'Rutin spordur.', 'will play': 'O anki karardır.', 'played': 'Geçmiş maçtır.'}),
    ('Who ___ the keynote address tomorrow morning?', 'is delivering', ['delivers', 'will deliver', 'delivered'],
     'Programmed event schedule inquiry.', 'Yarın sabahki ana konuşmayı yapacak kişi programda bellidir.',
     {'delivers': 'Geniş zamandır.', 'will deliver': 'Tahmin sorar.', 'delivered': 'Geçmiş sunumdur.'}),
    ('We ___ not ___ any new projects until Q3.', 'are / onboarding', ['will / onboard', 'do / onboard', 'have / onboarded'],
     'Agreed management decision and schedule.', '3. çeyreğe kadar yeni proje almama yönündeki kesin plan.',
     {'will / onboard': 'Gelecek niyetidir.', 'do / onboard': 'Geniş zamandır.', 'have / onboarded': 'Geçmiş durumdur.'}),
    ('My manager ___ to Frankfurt on Friday for the supplier audit.', 'is traveling', ['travels', 'will travel', 'traveled'],
     'Corporate travel itinerary.', 'Müdürün cuma günkü planlı seyahati.',
     {'travels': 'Geniş zamandır.', 'will travel': 'Tahmindir.', 'traveled': 'Geçmiş seyahattir.'}),
    ('Are you ___ with us to the team offsite next week?', 'coming', ['come', 'will come', 'came'],
     'Invitation checking participation in an upcoming arranged trip.', 'Gelecek haftaki planlı şirket kampına gelip gelmeyeceğini sorar.',
     {'come': 'Are you ile yalın fiil kullanılamaz.', 'will come': 'Gelecek misin diye anlık niyet sorar.', 'came': 'Geçmiş zamandır.'}),
    ('The auditors ___ tomorrow at 9 AM to inspect the facility.', 'are arriving', ['arrive', 'will arrive', 'arrived'],
     'Scheduled professional inspection.', "Denetçilerin yarın sabah 9'daki planlı gelişi.",
     {'arrive': 'Genel tarife dışında kişilerin gelişi için Present Continuous yaygındır.', 'will arrive': 'Gelecek tahmini yapar.', 'arrived': 'Geçmiş zamandır.'}),
], 'Choose Present Continuous for confirmed future arrangements:', 'Kesinleşmiş gelecek planları ve randevuları için Present Continuous yapısını seçiniz.')

# grammar.b1.first-second-conditional
add_lesson("grammar.b1.first-second-conditional", "first-sec-cond", [
    ('If our budget ___ approved next week, we will hire three developers.', 'is', ['was', 'were', 'will be'],
     "First conditional 'if' clause takes Present Simple for realistic future conditions.", "First conditional yapısında 'if' cümleciği gerçekçi gelecek durumlar için Present Simple alır.",
     {'was': "Second conditional için geçmiş zaman kipidir; ana cümlede 'will' varken uyumsuzdur.", 'were': 'İkinci tip şart cümlesinde kullanılır.', 'will be': "'If' cümleciği içine 'will' doğrudan konulmaz."}),
    ('If I ___ the company CEO, I would implement a four-day workweek.', 'were', ['am', 'will be', 'would be'],
     "Second conditional hypothetical state requires 'were' (or 'was') in the 'if' clause.", "Gerçek dışı/hayali durumlarda 'if' cümleciğinde 'were' kullanılır.",
     {'am': 'Gerçek bir olasılık sunar; konuşmacı CEO olmadığı için Second Conditional gereklidir.', 'will be': "'If' cümleciğinde 'will' kullanılmaz.", 'would be': "'Would' ana cümlede yer alır, 'if' cümlesinde değil."}),
    ('What ___ you do if you won the grand lottery jackpot?', 'would', ['will', 'do', 'did'],
     "Second conditional main clause uses 'would + base verb' for hypothetical scenarios.", "İkinci tip şart cümlelerinin soru kısmında 'would + yalın fiil' kullanılır.",
     {'will': 'Birinci tip şart cümlesinde gerçekçi durumlar için kullanılır.', 'do': 'Geniş zaman gerçek durumları sorar.', 'did': 'Geçmiş zaman sorusu yapar.'}),
    ('If it rains this evening, we ___ the rooftop celebration inside.', 'will move', ['would move', 'moved', 'move'],
     "Realistic future condition (First Conditional) takes 'will + base verb' in the main clause.", "Birinci tip şart cümlesinin ana cümlesi 'will + yalın fiil' alır.",
     {'would move': 'İkinci tip şart cümlesi için hayali durumlarda kullanılır.', 'moved': 'Geçmiş zamandır.', 'move': 'Geniş zamandır.'}),
    ("If they ___ more careful with testing, they wouldn't have so many production bugs.", 'were', ['are', 'will be', 'would be'],
     'Second conditional describing an unreal present situation and its consequence.', 'Şu anki gerçekliğin aksini varsayan ikinci tip şart cümlesi.',
     {'are': "Birinci tip şart cümlesidir; ana cümlede 'wouldn't' olduğu için uyumsuzdur.", 'will be': "'If' cümlesine 'will' girmez.", 'would be': "'Would' 'if' cümleciğinde kullanılmaz."}),
    ('Unless the client ___ the proposal by Friday, the launch will be delayed.', 'signs', ['will sign', 'signed', 'would sign'],
     "'Unless' means 'if not' and takes Present Simple in first conditional.", "'Unless' (olmadıkça) birinci tip şart yapısında Present Simple alır.",
     {'will sign': "'Unless' cümleciğinde 'will' kullanılmaz.", 'signed': "Geçmiş zamandır, ana cümledeki 'will' ile uyumsuzdur.", 'would sign': 'İkinci tip şart kipidir.'}),
    ('If I had more free time, I ___ another foreign language.', 'would learn', ['will learn', 'learn', 'learned'],
     "Second conditional main clause with hypothetical present condition ('had').", "Mevcut durumun aksine ('daha çok vaktim olsa') hayali sonuç bildiren 'would learn'.",
     {'will learn': 'Gerçekçi birinci tip şart için kullanılır.', 'learn': 'Geniş zamandır.', 'learned': 'Geçmiş zamandır.'}),
    ('If you ___ the shortcut key Ctrl+S, the application saves the draft immediately.', 'press', ['will press', 'would press', 'pressed'],
     'Zero/first conditional for factual/direct functional consequence.', 'Klavye kısayoluna basınca uygulamanın kaydetmesi genel/doğrudan şarttır.',
     {'will press': "'If' cümleciğinde 'will' yer almaz.", 'would press': 'Hayali durum değildir.', 'pressed': 'Geçmiş zaman değildir.'}),
    ('If we offered you a 20% equity stake, ___ you consider joining our startup?', 'would', ['will', 'do', 'did'],
     'Polite hypothetical negotiation using Second Conditional.', "Müzakerelerde varsayımsal teklif sunarken Second Conditional ('would') kullanılır.",
     {'will': "Fazla doğrudan ve kesin gelebilir; varsayımsal müzakerede 'would' tercih edilir.", 'do': 'Geniş zamandır.', 'did': 'Geçmiş zamandır.'}),
    ('If the train is delayed, I ___ you a text message.', 'will send', ['would send', 'sent', 'send'],
     'First conditional realistic arrangement.', 'Tren gecikirse mesaj atarım (gerçekçi gelecek ihtimali).',
     {'would send': 'İkinci tip şart kipi ana cümleye uymaz.', 'sent': 'Geçmiş zamandır.', 'send': 'Geniş zamandır.'}),
    ('Where would you travel if you ___ anywhere in the world right now?', 'could go', ['can go', 'will go', 'go'],
     "Second conditional 'could' in the 'if' clause for hypothetical ability.", 'Şu an dünyada herhangi bir yere gidebilecek olsan nereye giderdin?',
     {'can go': "Birinci tip şart kipidir; 'would you travel' ile uyumsuzdur.", 'will go': "'If' cümlesine uymaz.", 'go': 'Geniş zamandır.'}),
    ("If you don't wear a warm coat today, you ___ catch a cold.", 'might', ['would', 'could have', 'did'],
     "First conditional with modal of possibility ('might').", 'Sıkı giyinmezsen üşütebilirsin (gerçekçi ihtimal).',
     {'would': 'İkinci tip şart kipi anlamı taşır.', 'could have': 'Geçmiş kaçırılmış ihtimaldir.', 'did': 'Geçmiş zamandır.'}),
    ('If she ___ how to program in Python, she could automate this report.', 'knew', ['knows', 'will know', 'would know'],
     'Second conditional hypothetical present state.', 'Python bilseydi bu raporu otomatize edebilirdi (ama bilmiyor).',
     {'knows': "Birinci tip şart kipidir; ana cümledeki 'could' ile uyumsuzdur.", 'will know': "'If' cümlesine girmez.", 'would know': "'Would' if cümleciğine girmez."}),
    ('We will miss the project deadline if we ___ work overtime this weekend.', "don't", ["didn't", "won't", "wouldn't"],
     'First conditional negative condition in Present Simple.', 'Bu hafta sonu fazla mesai yapmazsak teslim tarihini kaçıracağız.',
     {"didn't": "İkinci tip şart kipi ana cümledeki 'will' ile uyumsuzdur.", "won't": "'If' cümlesine 'won't' girmez.", "wouldn't": "'If' cümlesine girmez."}),
    ('If I were in your position, I ___ accept the job offer in Zurich.', 'would', ['will', 'can', 'shall'],
     "Giving advice with Second Conditional ('If I were you, I would...').", "Tavsiye verirken 'senin yerinde olsaydım kabul ederdim' kalıbı.",
     {'will': 'Gerçek durumu ima eder; başkasının pozisyonunda olmak hayalidir.', 'can': 'Yetenek bildirir.', 'shall': 'Resmi gelecek kuralıdır.'}),
    ('If the internet connection drops, the backup cellular router ___ kick in.', 'will', ['would', 'did', 'was'],
     'Technical first conditional for automated system response.', 'İnternet koparsa yedek hücresel yönlendirici devreye girecektir.',
     {'would': 'Sistemin hayali çalıştığını ima eder.', 'did': 'Geçmiş zamandır.', 'was': 'Geçmiş zamandır.'}),
    ("What will happen if we ___ the client's custom request?", 'reject', ['rejected', 'will reject', 'would reject'],
     'First conditional question stem.', 'Müşterinin özel isteğini reddedersek ne olacak?',
     {'rejected': "İkinci tip şart kipidir; 'will happen' ile uyumsuzdur.", 'will reject': "'If' içine 'will' girmez.", 'would reject': "'If' içine girmez."}),
    ('If money ___ no object, which luxury car would you purchase?', 'were', ['is', 'will be', 'has been'],
     "Idiomatic second conditional expression 'if money were no object'.", "'Para sorun olmasaydı' hayali deyimsel kalıbı.",
     {'is': 'Paranın sorun olmadığı gerçeğini ima eder.', 'will be': "'If' içine girmez.", 'has been': 'Present Perfect bu kalıba uymaz.'}),
    ('If the server temperature exceeds 80 degrees, the cooling fans ___ automatically.', 'accelerate', ['will accelerate', 'accelerated', 'would accelerate'],
     'Zero/first conditional for automatic engineering rules.', 'Sunucu sıcaklığı 80 dereceyi aşarsa fanlar otomatik hızlanır.',
     {'will accelerate': 'Gelecek zaman da mümkündür ancak doğrudan kural için Present Simple standarttır.', 'accelerated': 'Geçmiş zamandır.', 'would accelerate': 'Hayali durum değildir.'}),
    ('If you practiced speaking English every day, you ___ fluent much faster.', 'would become', ['will become', 'become', 'became'],
     'Second conditional encouraging hypothetical daily discipline.', 'Her gün pratik yapsaydın çok daha hızlı akıcı olurdun.',
     {'will become': "Birinci tip şart için kullanılır; 'practiced' geçmiş kipiyle uyumsuzdur.", 'become': 'Geniş zamandır.', 'became': 'Geçmiş zamandır.'}),
], 'Choose between First Conditional (real/likely) and Second Conditional (unreal/hypothetical):', 'Gerçekçi gelecek olasılıkları (First Conditional) ile varsayımsal/hayali durumları (Second Conditional) ayırt ediniz.')

# grammar.b1.passive-voice-foundations
add_lesson("grammar.b1.passive-voice-foundations", "passive-found", [
    ('The confidential documents ___ in a secure safe every evening.', 'are kept', ['keep', 'are keeping', 'were keeping'],
     'Present Simple passive: object receives the action on a regular basis.', 'Belgeler her akşam kasada saklanır (Present Simple Passive: are + V3).',
     {'keep': 'Belgeler kendi kendini saklayamaz; etken yapı anlamsızdır.', 'are keeping': 'Belgelerin saklamakta olduğunu söyler.', 'were keeping': 'Geçmişte saklamakta olduğunu söyler.'}),
    ('The new flagship smartphone ___ by our CEO last night.', 'was unveiled', ['unveiled', 'is unveiled', 'has unveiled'],
     "Past Simple passive: 'was/were + past participle' with a finished time marker ('last night').", 'Akıllı telefon dün gece CEO tarafından tanıtıldı (Past Simple Passive).',
     {'unveiled': 'Telefonun kendisinin tanıtım yaptığını ima eder.', 'is unveiled': "Şu an tanıtıldığını söyler, 'last night' ile uyumsuzdur.", 'has unveiled': "Etken Present Perfect'tir."}),
    ('English ___ in international business transactions worldwide.', 'is spoken', ['speaks', 'is speaking', 'spoke'],
     'General truth in Present Simple passive.', 'İngilizce dünya çapında iş dünyasında konuşulur.',
     {'speaks': 'İngilizcenin kendisi konuşamaz.', 'is speaking': 'Şu an konuştuğunu söyler.', 'spoke': 'Geçmişte konuşulup bittiğini ima eder.'}),
    ('The software bug ___ by the QA team before the release.', 'was discovered', ['discovered', 'discovers', 'was discovering'],
     'Past passive emphasizing the discovery of the issue.', 'Yazılım hatası yayından önce test ekibi tarafından keşfedildi.',
     {'discovered': 'Hatanın bir şeyi keşfettiğini ima eder.', 'discovers': 'Geniş zaman etkendir.', 'was discovering': 'Hatanın keşfetmekte olduğunu söyler.'}),
    ('Millions of online payments ___ securely every single day.', 'are processed', ['process', 'are processing', 'processed'],
     'Habitual/routine passive action.', 'Milyonlarca ödeme her gün güvenle işlenir.',
     {'process': 'Ödemelerin bizzat işlem yaptığını söyler.', 'are processing': 'Ödemeler işlem yapmaktadır anlamına gelir.', 'processed': 'Geçmiş zamandır.'}),
    ('This bridge ___ by a famous Turkish architect in 1973.', 'was built', ['built', 'has built', 'is built'],
     'Completed past passive construction with historical date.', 'Bu köprü 1973 yılında ünlü bir mimar tarafından inşa edildi.',
     {'built': 'Köprünün bir şey inşa ettiğini ima eder.', 'has built': 'Etken zamandır.', 'is built': 'Bugün inşa edildiğini söyler.'}),
    ('All incoming packages ___ thoroughly at the security gate.', 'are inspected', ['inspect', 'are inspecting', 'inspected'],
     'Standard operational passive procedure.', 'Gelen tüm paketler güvenlik kapısında titizlikle denetlenir.',
     {'inspect': 'Paketlerin denetim yaptığını ima eder.', 'are inspecting': 'Paketler denetleme yapmaktadır anlamına gelir.', 'inspected': 'Geçmiş zaman etkendir.'}),
    ('The system architecture ___ to accommodate five million active users.', 'was redesigned', ['redesigned', 'redesigns', 'is redesigning'],
     'Past completed passive redesign.', 'Sistem mimarisi 5 milyon kullanıcıyı kaldıracak şekilde yeniden tasarlandı.',
     {'redesigned': 'Mimarinin kendisinin tasarım yaptığını ima eder.', 'redesigns': 'Geniş zamandır.', 'is redesigning': 'Mimarinin tasarım yapmakta olduğunu söyler.'}),
    ('Tea ___ with fresh mint in many Mediterranean cafes.', 'is served', ['serves', 'is serving', 'served'],
     'Cultural food preparation passive.', 'Çay birçok Akdeniz kafesinde taze naneyle servis edilir.',
     {'serves': 'Çayın servis yaptığını söyler.', 'is serving': 'Çay servis yapmaktadır anlamına gelir.', 'served': 'Geçmişte servis edildi bitti anlamı verir.'}),
    ('Our customer support tickets ___ within twenty-four hours.', 'are answered', ['answer', 'are answering', 'answered'],
     'SLA guarantee in passive voice.', 'Müşteri destek biletleri 24 saat içinde yanıtlanır.',
     {'answer': 'Biletlerin cevap verdiğini söyler.', 'are answering': 'Biletler cevap vermektedir anlamına gelir.', 'answered': 'Geçmiş zamandır.'}),
    ('The stolen laptop ___ in the cafe by a cleaner yesterday.', 'was found', ['found', 'finds', 'was finding'],
     'Past passive recovery event.', 'Çalınan dizüstü bilgisayar dün kafede temizlikçi tarafından bulundu.',
     {'found': 'Bilgisayarın bir şey bulduğunu söyler.', 'finds': 'Geniş zamandır.', 'was finding': 'Bilgisayarın bir şey bulmakta olduğunu söyler.'}),
    ('Important announcements ___ on the intranet bulletin board.', 'are posted', ['post', 'are posting', 'posted'],
     'Corporate communication routine.', 'Önemli duyurular intranet panosuna asılır/yüklenir.',
     {'post': 'Duyuruların paylaşım yaptığını söyler.', 'are posting': 'Duyuruların paylaşmakta olduğunu söyler.', 'posted': 'Geçmiş zamandır.'}),
    ('The annual financial report ___ to all stakeholders next Monday.', 'will be sent', ['will send', 'is sending', 'sends'],
     "Future passive form: 'will be + past participle'.", 'Yıllık mali rapor gelecek pazartesi tüm paydaşlara gönderilecek.',
     {'will send': 'Raporun bir şey göndereceğini söyler.', 'is sending': 'Raporun göndermekte olduğunu söyler.', 'sends': 'Geniş zamandır.'}),
    ('A lot of renewable energy ___ from offshore wind farms.', 'is generated', ['generates', 'is generating', 'generated'],
     'Environmental factual passive.', 'Açık deniz rüzgar çiftliklerinden büyük miktarda yenilenebilir enerji üretilir.',
     {'generates': 'Enerjinin kendisinin üretim yaptığını söyler.', 'is generating': 'Enerji üretmektedir anlamına gelir.', 'generated': 'Geçmiş zamandır.'}),
    ('The conference ___ due to heavy snowstorm warnings.', 'was canceled', ['canceled', 'cancels', 'was canceling'],
     'Event cancellation passive.', 'Konferans yoğun kar fırtınası uyarıları nedeniyle iptal edildi.',
     {'canceled': 'Konferansın bir şeyi iptal ettiğini söyler.', 'cancels': 'Geniş zamandır.', 'was canceling': 'Konferansın iptal etmekte olduğunu söyler.'}),
    ('Credit cards ___ at all automated checkout counters.', 'are accepted', ['accept', 'are accepting', 'accepted'],
     'Commercial policy passive.', 'Otomatik kasalarda kredi kartları kabul edilir.',
     {'accept': 'Kartların kabul ettiğini söyler.', 'are accepting': 'Kartlar kabul etmektedir anlamına gelir.', 'accepted': 'Geçmiş zamandır.'}),
    ('The prototype ___ by a third-party cybersecurity agency.', 'was audited', ['audited', 'audits', 'was auditing'],
     'Security evaluation passive.', 'Prototip üçüncü taraf bir siber güvenlik ajansı tarafından denetlendi.',
     {'audited': 'Prototipin denetim yaptığını söyler.', 'audits': 'Geniş zamandır.', 'was auditing': 'Prototipin denetlemekte olduğunu söyler.'}),
    ('Where ___ this traditional Turkish ceramic produced?', 'is', ['does', 'are', 'did'],
     'Question form in Present Simple passive for singular subject.', "Bu geleneksel seramik nerede üretilir? ('ceramic' tekildir).",
     {'does': "Etken soru yardımcı fiilidir, edilgende 'is' gerekir.", 'are': "Tekil özne 'ceramic' için 'are' kullanılamaz.", 'did': 'Geçmiş zaman etken yardımcı fiildir.'}),
    ('The winner of the hackathon ___ tomorrow evening.', 'will be announced', ['will announce', 'announces', 'is announcing'],
     'Future passive result announcement.', 'Hackathon kazananı yarın akşam duyurulacak.',
     {'will announce': 'Kazananın duyuru yapacağını söyler.', 'announces': 'Geniş zamandır.', 'is announcing': 'Şu an duyurmaktadır anlamına gelir.'}),
    ('Safety goggles must ___ inside the chemical laboratory at all times.', 'be worn', ['wear', 'worn', 'be wearing'],
     "Modal passive: 'modal + be + past participle'.", 'Laboratuvarda her zaman koruyucu gözlük takılmalıdır (must be + V3).',
     {'wear': 'Gözlüğün bir şey takacağını söyler.', 'worn': "'Be' olmadan modal ardına past participle gelemez.", 'be wearing': 'Gözlüğün takmakta olduğunu söyler.'}),
], 'Choose the correct form of Passive Voice (be + past participle):', "Eylemi yapan yerine eylemden etkileneni ve 'be + V3' yapısını doğru kurunuz.")

# grammar.b1.reported-speech-statements
add_lesson("grammar.b1.reported-speech-statements", "rep-speech", [
    ("He said, 'I work remotely.' -> He said that he ___ remotely.", 'worked', ['works', 'is working', 'had worked'],
     'Present Simple shifts back to Past Simple in reported speech.', "Aktarma fiili geçmişte ('said') olduğunda Present Simple, Past Simple'a kayar.",
     {'works': 'Zaman geriye kaydırılmamıştır.', 'is working': 'Şimdiki zamana dönüştürülemez.', 'had worked': 'Past Perfect ancak Past Simple aktarılırken gelir.'}),
    ("She told me, 'I am preparing the financial presentation.' -> She told me that she ___ the presentation.", 'was preparing', ['is preparing', 'prepared', 'had prepared'],
     'Present Continuous shifts back to Past Continuous.', "Present Continuous dolaylı aktarımda Past Continuous ('was preparing') olur.",
     {'is preparing': 'Zaman geriye kaydırılmamıştır.', 'prepared': 'Süreç bilgisi kaybolmuştur.', 'had prepared': 'Past Perfect Continuous olması gerekirdi.'}),
    ("They said, 'We have completed the user testing.' -> They said that they ___ the user testing.", 'had completed', ['have completed', 'completed', 'were completing'],
     'Present Perfect shifts back to Past Perfect.', "Present Perfect dolaylı aktarımda Past Perfect ('had completed') haline gelir.",
     {'have completed': 'Zaman geriye kaydırılmamıştır.', 'completed': "Past Simple Present Perfect'in aktarımı değildir.", 'were completing': 'Sürekli zamana dönüştürülemez.'}),
    ("Alex said, 'I will call you tomorrow.' -> Alex said that he ___ call me the next day.", 'would', ['will', 'can', 'shall'],
     "'Will' shifts to 'would' in reported speech.", "'Will' dolaylı aktarımda 'would' haline dönüşür.",
     {'will': 'Zaman geriye kaydırılmamıştır.', 'can': 'Anlam değişikliğine yol açar.', 'shall': 'Geçmiş aktarım kuralına uymaz.'}),
    ("She said, 'I don't understand the algorithm.' -> She said that she ___ the algorithm.", "didn't understand", ["doesn't understand", "hadn't understood", 'not understood'],
     'Negative Present Simple shifts to negative Past Simple.', "Olumsuz Present Simple ('don't') dolaylı anlatımda 'didn't' olur.",
     {"doesn't understand": 'Zaman geriye kaydırılmamıştır.', "hadn't understood": 'Gereksiz Past Perfect kullanımıdır.', 'not understood': 'Yardımcı fiilsiz hatalı kullanımdır.'}),
    ("The engineer explained, 'The server crashed yesterday.' -> He explained that the server ___ the day before.", 'had crashed', ['crashed', 'crashes', 'has crashed'],
     'Past Simple shifts back to Past Perfect.', "Past Simple dolaylı anlatımda Past Perfect ('had crashed') haline gelir.",
     {'crashed': 'Zaman geriye kaydırılmamıştır.', 'crashes': 'Geniş zamana dönüştürülemez.', 'has crashed': "Present Perfect'e dönüştürülemez."}),
    ("He told the manager, 'I can fix the issue quickly.' -> He told the manager that he ___ fix the issue quickly.", 'could', ['can', 'would can', 'could have'],
     "Modal 'can' shifts to 'could' in reported speech.", "'Can' kipi dolaylı anlatımda 'could' haline gelir.",
     {'can': 'Zaman geriye kaydırılmamıştır.', 'would can': 'İngilizcede böyle bir yapı yoktur.', 'could have': 'Geçmiş kaçırılmış fırsat anlamı katar.'}),
    ("The recruiter said, 'We are looking for a senior DevOps lead.' -> She said that they ___ for a senior DevOps lead.", 'were looking', ['are looking', 'looked', 'have looked'],
     'Present Continuous shifts to Past Continuous with plural subject.', "Çoğul özneyle Present Continuous, Past Continuous ('were looking') olur.",
     {'are looking': 'Zaman geriye kaydırılmamıştır.', 'looked': 'Süreç vurgusu kaybolmuştur.', 'have looked': "Present Perfect'e çevrilemez."}),
    ("She told us, 'I must finish this report tonight.' -> She told us that she ___ finish the report that night.", 'had to', ['must', 'would must', 'should'],
     "'Must' expressing necessity shifts to 'had to' in reported speech.", "Zorunluluk bildiren 'must', dolaylı anlatımda 'had to' olur.",
     {'must': "Resmi kural dışında geçmiş aktarımda 'had to' tercih edilir.", 'would must': 'Böyle bir modal birleşimi yoktur.', 'should': 'Tavsiye anlamına kayar.'}),
    ("Mark said, 'I have been working here for two years.' -> Mark said that he ___ working there for two years.", 'had been', ['has been', 'was', 'were'],
     'Present Perfect Continuous shifts to Past Perfect Continuous.', "Present Perfect Continuous dolaylı aktarımda Past Perfect Continuous ('had been') olur.",
     {'has been': 'Zaman geriye kaydırılmamıştır.', 'was': 'Süreç bildiren perfect yapıyı bozar.', 'were': "Tekil özne 'he' ile uyumsuzdur."}),
    ("The vendor announced, 'We may increase prices next quarter.' -> The vendor announced that they ___ increase prices.", 'might', ['may', 'could have', 'will'],
     "Modal 'may' of possibility shifts to 'might'.", "Olasılık bildiren 'may' dolaylı aktarımda 'might' olur.",
     {'may': 'Zaman geriye kaydırılmamıştır.', 'could have': 'Geçmiş kaçırılmış ihtimaldir.', 'will': 'Kesinlik katar, orijinal anlamı bozar.'}),
    ("He said, 'I didn't receive your email.' -> He said that he ___ my email.", "hadn't received", ["didn't receive", "hasn't received", "doesn't receive"],
     'Negative Past Simple shifts to negative Past Perfect.', "Olumsuz Past Simple, dolaylı anlatımda Past Perfect ('hadn't received') olur.",
     {"didn't receive": 'Zaman geriye kaydırılmamıştır.', "hasn't received": "Present Perfect'e dönüştürülemez.", "doesn't receive": 'Geniş zamana dönüştürülemez.'}),
    ("The CEO said, 'The company is growing rapidly.' -> The CEO said that the company ___ rapidly.", 'was growing', ['is growing', 'grew', 'had grown'],
     'Present Continuous backshift.', "Şirketin hızla büyümekte olduğunu geçmişe aktarırken 'was growing' kullanılır.",
     {'is growing': 'Zaman geriye kaydırılmamıştır.', 'grew': 'Süreç bilgisi kaybolmuştur.', 'had grown': 'Past Perfect büyümenin bittiğini ima eder.'}),
    ("She stated, 'I bought the tickets online.' -> She stated that she ___ the tickets online.", 'had bought', ['bought', 'buys', 'has bought'],
     'Past Simple shifts to Past Perfect.', "Geçmişte bilet aldığını aktarırken 'had bought' kullanılır.",
     {'bought': 'Zaman geriye kaydırılmamıştır.', 'buys': 'Geniş zamandır.', 'has bought': "Present Perfect'e kaymaz."}),
    ("They said to me, 'You are our top candidate.' -> They told me that I ___ their top candidate.", 'was', ['am', 'were', 'had been'],
     "Pronoun and tense shift ('you are' -> 'I was').", "Zamir ve zaman uyumu ('you are' -> 'I was').",
     {'am': 'Zaman geriye kaydırılmamıştır.', 'were': "'I' öznesi ile 'were' kullanılmaz.", 'had been': "Gereksiz Past Perfect'tir."}),
    ("He said, 'I will be traveling next week.' -> He said that he ___ traveling the following week.", 'would be', ['will be', 'is', 'was'],
     "Future Continuous shifts to conditional continuous ('would be').", "Gelecekte devam edecek eylem aktarılırken 'would be' olur.",
     {'will be': 'Zaman geriye kaydırılmamıştır.', 'is': 'Şimdiki zamandır.', 'was': 'Gelecek boyutunu siler.'}),
    ("The architect said, 'The design needs minor adjustments.' -> The architect said that the design ___ minor adjustments.", 'needed', ['needs', 'had needed', 'is needing'],
     'Present Simple shifts to Past Simple.', "Tasarımın düzeltmeye ihtiyacı olduğunu aktarırken 'needed' kullanılır.",
     {'needs': 'Zaman geriye kaydırılmamıştır.', 'had needed': "Gereksiz Past Perfect'tir.", 'is needing': "'Need' durum fiilidir, continuous almaz."}),
    ("She told him, 'I cannot attend the scrum meeting.' -> She told him that she ___ attend the scrum meeting.", 'could not', ['cannot', 'would not can', 'must not'],
     "Negative 'cannot' shifts to 'could not'.", "'Cannot' dolaylı anlatımda 'could not' haline gelir.",
     {'cannot': 'Zaman geriye kaydırılmamıştır.', 'would not can': 'Hatalı birleşik modaldır.', 'must not': 'Yasaklama anlamına kayar.'}),
    ("The team lead said, 'We are ready for deployment.' -> The team lead said that they ___ ready for deployment.", 'were', ['are', 'had been', 'will be'],
     "Present Simple of 'be' shifts to Past Simple 'were'.", "Ekibin hazır olduğunu aktarırken 'they were' kullanılır.",
     {'are': 'Zaman geriye kaydırılmamıştır.', 'had been': 'Hazırlığın geçmişte kaldığını ima eder.', 'will be': 'Gelecek zamandır.'}),
    ("He admitted, 'I made a mistake in the calculation.' -> He admitted that he ___ a mistake in the calculation.", 'had made', ['made', 'makes', 'has made'],
     'Reporting a past admission shifts to Past Perfect.', "Geçmişte hata yaptığını itiraf ederken Past Perfect ('had made') kullanılır.",
     {'made': 'Zaman geriye kaydırılmamıştır.', 'makes': 'Geniş zamandır.', 'has made': "Present Perfect'e dönüştürülemez."}),
], 'Choose the correct tense/pronoun shifts in Reported Speech:', 'Dolaylı anlatımda (Reported Speech) zaman kaymalarını ve zamir uyumunu doğru seçiniz.')

# grammar.b1.modals-deduction-present
add_lesson("grammar.b1.modals-deduction-present", "mod-deduct-pres", [
    ('The office lights are off and the doors are locked. Everyone ___ gone home.', 'must have', ["can't have", 'might have', 'should have'],
     "'Must have' expresses a logical certainty based on strong evidence.", "Işıklar kapalı ve kapılar kilitliyse güçlü kanıta dayalı mantıksal kesinlik 'must have' ile kurulur.",
     {"can't have": 'İmkansızlık bildirir; kanıt tam tersini göstermektedir.', 'might have': 'Sadece zayıf bir ihtimal belirtir.', 'should have': 'Tavsiye veya beklenen eylem bildirir.'}),
    ('He only started learning coding last month; he ___ build a full banking backend yet.', "can't", ['must', 'might', 'should'],
     "'Can't' expresses logical impossibility based on knowledge.", "Yazılıma yeni başlayan birinin karmaşık bankacılık sistemini kurması mantıksal olarak imkansızdır ('can't').",
     {'must': 'Kesinlikle kurabilir anlamına gelir ki mantıksızdır.', 'might': 'Zayıf ihtimaldir ama bağlam imkansızlığı vurgular.', 'should': 'Kurması gerekir anlamına gelir.'}),
    ("I'm not completely sure, but the error ___ be related to database indexing.", 'might', ['must', "can't", 'will'],
     "'Might' expresses uncertainty or possibility.", "'I'm not completely sure' ifadesi kesin olmadığını gösterir, bu yüzden 'might' kullanılır.",
     {'must': 'Yüksek kesinlik bildirir, cümledeki belirsizlikle çelişir.', "can't": 'İmkansızlık bildirir.', 'will': 'Gelecekte kesinlik bildirir.'}),
    ('Look at her calendar; she has meetings all day, so she ___ be very busy.', 'must', ["can't", 'might not', "couldn't"],
     'Strong logical conclusion from evidence.', "Bütün gün toplantısı varsa çok yoğun olduğu mantıksal bir kesinliktir ('must').",
     {"can't": 'Yoğun olamaz anlamına gelir ki kanıtla çelişir.', 'might not': 'Yoğun olmayabilir anlamına gelir.', "couldn't": 'İmkansızlık bildirir.'}),
    ("That car ___ belong to Sarah; she doesn't even have a driver's license!", "can't", ['must', 'could', 'might'],
     'Logical impossibility.', "Ehliyeti dahi olmayan birinin arabası olamaz mantıksal imkansızlığı ('can't').",
     {'must': 'Kesinlikle onun arabasıdır anlamına gelir.', 'could': 'Onun olabilir anlamına gelir.', 'might': 'Onun olabilir anlamına gelir.'}),
    ('Where is David? He ___ be in the kitchen making coffee, but check the lab too.', 'could', ['must', "can't", "won't"],
     'A plausible possibility among alternatives.', 'Kahve yapıyor olabilir (ihtimal), ama laboratuvara da bak.',
     {'must': 'Kesin oradadır anlamına gelir, laboratuvara bakmaya gerek bırakmaz.', "can't": 'Orada olamaz anlamına gelir.', "won't": 'Orada olmayacak anlamına gelir.'}),
    ('This code compiles without warnings and passes all 50 tests. It ___ be working properly.', 'must', ["can't", 'might not', "shouldn't"],
     'Strong technical evidence leading to logical deduction.', "Tüm testleri geçiyorsa düzgün çalışıyor olmalıdır ('must').",
     {"can't": 'Düzgün çalışıyor olamaz anlamına gelir.', 'might not': 'Çalışmayabilir anlamına gelir.', "shouldn't": 'Çalışmaması gerekir anlamına gelir.'}),
    ('They have been traveling in South America for six months; they ___ have so many interesting stories.', 'must', ["can't", 'might not', "wouldn't"],
     'High probability deduction from life experience.', 'Altı aydır seyahat ediyorlarsa kesinlikle anlatacak çok hikayeleri vardır.',
     {"can't": 'Hikayeleri olamaz anlamına gelir.', 'might not': 'Hikayeleri olmayabilir anlamına gelir.', "wouldn't": 'Olmazdı anlamına gelir.'}),
    ("You haven't eaten anything since breakfast; you ___ be starving!", 'must', ["can't", 'might', "couldn't"],
     'Colloquial deduction based on obvious physical circumstance.', "Sabahtan beri bir şey yemediysen kesinlikle açlıktan ölüyorsundur ('must').",
     {"can't": 'Aç olamazsın anlamına gelir.', 'might': 'Aç olabilirsin diye zayıf bırakır.', "couldn't": 'Aç olamazdın anlamına gelir.'}),
    ('He is wearing shorts and a T-shirt in the snow; he ___ be freezing!', 'must', ["can't", 'might not', "couldn't"],
     'Obvious physical deduction.', 'Karda şortla duruyorsa kesinlikle donuyordur.',
     {"can't": 'Üşüyor olamaz anlamına gelir.', 'might not': 'Üşümüyor olabilir anlamına gelir.', "couldn't": 'İmkansızlık bildirir.'}),
    ('The phone keeps ringing with no answer. She ___ be away from her desk.', 'must', ["can't", "couldn't", "shouldn't"],
     'Reasonable certainty from observation.', 'Telefon çalıp açılmıyorsa masasında olmadığı çıkarımı yapılır.',
     {"can't": 'Masasından uzakta olamaz anlamına gelir.', "couldn't": 'Olamazdı anlamına gelir.', "shouldn't": 'Olmaması gerekir anlamına gelir.'}),
    ('Take an umbrella with you; the dark clouds suggest it ___ rain later.', 'might', ['must', "can't", "couldn't"],
     'Weather forecast deduction of possibility.', 'Havadaki kara bulutlar yağmur yağabileceğine (ihtimal) işaret eder.',
     {'must': 'Kesinlikle yağacak anlamına gelir, havada garanti yoktur.', "can't": 'Yağamaz anlamına gelir.', "couldn't": 'Yağamazdı anlamına gelir.'}),
    ('This antique rug is in pristine condition; it ___ be genuinely three hundred years old.', "can't", ['must', 'might', 'could'],
     'Skeptical logical deduction of impossibility.', "Halı yepyeni duruyorsa gerçekten 300 yaşında olamaz ('can't').",
     {'must': 'Kesinlikle 300 yaşındadır anlamına gelir.', 'might': 'Olabilir anlamına gelir.', 'could': 'Olabilir anlamına gelir.'}),
    ("Our lead architect hasn't replied to any messages; he ___ be in an executive strategy meeting.", 'could', ["can't", "mustn't", "wouldn't"],
     'Plausible explanation for silence.', 'Mesajlara dönmüyorsa strateji toplantısında olabilir (ihtimal).',
     {"can't": 'Toplantıda olamaz anlamına gelir.', "mustn't": 'Yasaklama katar.', "wouldn't": 'Toplantıda olmazdı anlamına gelir.'}),
    ('The package arrived in just one day from Japan; the seller ___ used express air courier.', 'must have', ["can't have", 'might not have', "shouldn't have"],
     'Past deduction from speed of delivery.', "Japonya'dan bir günde geldiyse kesinlikle hızlı kargo kullanmış olmalıdırlar.",
     {"can't have": 'Kullanmış olamazlar anlamına gelir.', 'might not have': 'Kullanmamış olabilirler anlamına gelir.', "shouldn't have": 'Kullanmamaları gerekirdi anlamına gelir.'}),
    ('She speaks four languages with native fluency; she ___ studied linguistics or lived abroad.', 'must have', ["can't have", 'might not have', "shouldn't have"],
     'Deduction explaining extraordinary skill.', 'Dört dili anadili gibi konuşuyorsa kesinlikle yurtdışında yaşamış veya dilbilim okumuş olmalıdır.',
     {"can't have": 'Okumuş olamaz anlamına gelir.', 'might not have': 'Okumamış olabilir anlamına gelir.', "shouldn't have": 'Okumamış olmalıydı anlamına gelir.'}),
    ('The file size is only 2 kilobytes; it ___ contain high-resolution video.', "can't", ['must', 'might', 'could'],
     'Technical deduction of impossibility.', "Dosya 2 kilobayt ise yüksek çözünürlüklü video içermesi imkansızdır ('can't').",
     {'must': 'Kesinlikle video içerir anlamına gelir.', 'might': 'İçerebilir anlamına gelir.', 'could': 'İçerebilir anlamına gelir.'}),
    ("Don't throw away that old computer part; it ___ be worth something to a collector.", 'might', ['must', "can't", "couldn't"],
     'Potential future value possibility.', 'Eski parçayı atma, bir koleksiyoncu için değerli olabilir.',
     {'must': 'Kesinlikle değerlidir anlamına gelir.', "can't": 'Değerli olamaz anlamına gelir.', "couldn't": 'Değerli olamazdı anlamına gelir.'}),
    ('He is wearing a stethoscope and white coat in the corridor; he ___ be a doctor.', 'must', ["can't", 'might not', "wouldn't"],
     'Visual deduction of identity.', 'Stetoskop ve beyaz önlük taşıyorsa doktor olmalıdır.',
     {"can't": 'Doktor olamaz anlamına gelir.', 'might not': 'Doktor olmayabilir anlamına gelir.', "wouldn't": 'Doktor olmazdı anlamına gelir.'}),
    ("I can't find my wallet anywhere in my bag; I ___ left it on the train.", 'might have', ["mustn't have", 'can have', 'should have'],
     'Hypothesizing past location of loss.', 'Cüzdan çantada yoksa trende bırakmış olabilirim (ihtimal).',
     {"mustn't have": 'Yasaklama katar, çıkarım yapmaz.', 'can have': "İngilizcede geçmiş olumlu çıkarımda 'can have' kullanılmaz.", 'should have': 'Bırakmalıydım anlamına gelir.'}),
], "Choose the correct modal of deduction (must, can't, might/could):", "Şimdiki zamana dair mantıksal çıkarımlarda kesinlik (must), imkansızlık (can't) ve olasılık (might/could) kiplerini seçiniz.")

# grammar.b1.gerunds-after-prepositions-verbs
add_lesson("grammar.b1.gerunds-after-prepositions-verbs", "ger-prep-verb", [
    ('She is extremely good at ___ complex architectural diagrams.', 'designing', ['to design', 'design', 'designed'],
     "Prepositions ('at', 'in', 'on', 'about', 'for') are strictly followed by gerunds (-ing).", "İngilizcede edatlardan ('at', 'in', 'on', 'about' vb.) sonra gelen fiiller daima '-ing' (gerund) alır.",
     {'to design': "Edatlardan sonra mastar ('to + fiil') gelemez.", 'design': 'Edattan sonra yalın fiil kullanılamaz.', 'designed': 'Geçmiş zaman kipi edattan sonra gelmez.'}),
    ('We are looking forward to ___ you at the upcoming tech conference.', 'meeting', ['meet', 'to meet', 'met'],
     "In 'look forward to', 'to' is a preposition, strictly requiring a gerund.", "'Look forward to' deyimindeki 'to' bir edattır; bu yüzden ardından mutlaka '-ing' gelir.",
     {'meet': "Türk öğrenicilerin 'to' görünce yalın fiil seçmesi en yaygın hatadır; buradaki 'to' edattır.", 'to meet': "Çift 'to' kullanımı hatalıdır.", 'met': 'Geçmiş zaman kipi gelemez.'}),
    ('The engineering team decided ___ the production deployment until next Tuesday.', 'to postpone', ['postponing', 'postpone', 'postponed'],
     "The verb 'decide' takes an infinitive with 'to'.", "'Decide' fiili ardından daima 'to + yalın fiil' (infinitive) alır.",
     {'postponing': "'Decide' fiili gerund ile kullanılmaz.", 'postpone': "'To' olmadan yalın fiil gelemez.", 'postponed': 'Geçmiş zaman eki alamaz.'}),
    ('He apologized for ___ late to the executive board meeting.', 'being', ['to be', 'be', 'been'],
     "Preposition 'for' requires a gerund.", "'Apologize for' edatından sonra 'being' (gerund) gelir.",
     {'to be': 'Edattan sonra mastar gelemez.', 'be': 'Yalın fiil edatın nesnesi olamaz.', 'been': 'Yardımcı fiilsiz kullanılamaz.'}),
    ('They avoided ___ sensitive client data over unencrypted email channels.', 'sending', ['to send', 'send', 'sent'],
     "The verb 'avoid' is strictly followed by a gerund.", "'Avoid' (kaçınmak) fiili daima gerund (-ing) ile kullanılır.",
     {'to send': "'Avoid' fiili 'to + infinitive' almaz.", 'send': 'Yalın fiil gelemez.', 'sent': 'Geçmiş zaman kipi gelemez.'}),
    ('I managed ___ the critical production issue before midnight.', 'to resolve', ['resolving', 'resolve', 'resolved'],
     "The verb 'manage' requires an infinitive with 'to'.", "'Manage' (başarmak/üstesinden gelmek) fiili 'to + infinitive' alır.",
     {'resolving': "'Manage' gerund ile kullanılmaz.", 'resolve': "'To' eksiktir.", 'resolved': 'Geçmiş zaman kipi peş peşe gelemez.'}),
    ('Are you interested in ___ our new mobile design sprint?', 'joining', ['to join', 'join', 'joined'],
     "Preposition 'in' requires a gerund.", "'Interested in' edatından sonra fiil '-ing' alır.",
     {'to join': "Edattan sonra 'to' gelemez.", 'join': 'Yalın fiil kullanılamaz.', 'joined': 'Geçmiş zaman kipi gelemez.'}),
    ('He suggested ___ the automated unit tests before opening the pull request.', 'running', ['to run', 'run', 'ran'],
     "The verb 'suggest' takes a gerund when followed directly by a verb.", "'Suggest' fiili doğrudan fiille devam ettiğinde gerund alır ('suggest doing').",
     {'to run': "'Suggest to do' İngilizcede dilbilgisel hatadır.", 'run': 'Yalın fiil gelemez.', 'ran': 'Geçmiş zaman kipi gelemez.'}),
    ('We cannot afford ___ our focus during this critical quarter.', 'to lose', ['losing', 'lose', 'lost'],
     "The verb 'afford' takes an infinitive with 'to'.", "'Afford' fiili daima 'to + infinitive' alır.",
     {'losing': "'Afford' fiili gerund almaz.", 'lose': "'To' eksiktir.", 'lost': 'Geçmiş zaman kipi gelemez.'}),
    ('She succeeded in ___ first place at the national hackathon.', 'winning', ['to win', 'win', 'won'],
     "Preposition 'in' in 'succeed in' takes a gerund.", "'Succeed in' edatından sonra gerund ('winning') kullanılır.",
     {'to win': 'Edattan sonra mastar gelemez.', 'win': 'Yalın fiil gelemez.', 'won': 'Geçmiş zaman kipi gelemez.'}),
    ('Our product team enjoys ___ new features with real beta testers.', 'testing', ['to test', 'test', 'tested'],
     "The verb 'enjoy' strictly takes a gerund.", "'Enjoy' fiili ardından daima gerund (-ing) alır.",
     {'to test': "'Enjoy to do' İngilizcede kullanılmaz.", 'test': 'Yalın fiil gelemez.', 'tested': 'Geçmiş zaman kipi gelemez.'}),
    ('The director promised ___ our feedback into consideration.', 'to take', ['taking', 'take', 'taken'],
     "The verb 'promise' takes an infinitive with 'to'.", "'Promise' fiili 'to + infinitive' alır.",
     {'taking': "'Promise' gerund ile kullanılmaz.", 'take': "'To' eksiktir.", 'taken': 'Geçmiş zaman kipi gelemez.'}),
    ('You should avoid ___ assumptions without looking at the raw logs.', 'making', ['to make', 'make', 'made'],
     "'Avoid' takes a gerund.", "'Avoid' gerund gerektirir.",
     {'to make': "'Avoid to do' yanlıştır.", 'make': 'Yalın fiil gelemez.', 'made': 'Geçmiş zaman kipi gelemez.'}),
    ('He thanked his mentor for ___ him prepare for the technical interview.', 'helping', ['to help', 'help', 'helped'],
     "Preposition 'for' takes a gerund.", "'Thank for' ardından gerund gelir.",
     {'to help': "Edattan sonra 'to' gelemez.", 'help': 'Yalın fiil gelemez.', 'helped': 'Geçmiş zaman kipi gelemez.'}),
    ('We plan ___ the new customer portal by early next month.', 'to launch', ['launching', 'launch', 'launched'],
     "The verb 'plan' takes an infinitive with 'to'.", "'Plan' fiili 'to + infinitive' alır.",
     {'launching': "'Plan launching' yerine standart kullanım 'plan to launch'tur.", 'launch': "'To' eksiktir.", 'launched': 'Geçmiş zaman kipi gelemez.'}),
    ('They are thinking about ___ their headquarters to another city.', 'relocating', ['to relocate', 'relocate', 'relocated'],
     "Preposition 'about' takes a gerund.", "'Think about' edatından sonra gerund gelir.",
     {'to relocate': "Edattan sonra 'to' gelemez.", 'relocate': 'Yalın fiil gelemez.', 'relocated': 'Geçmiş zaman kipi gelemez.'}),
    ('I refuse ___ low-quality code without thorough code reviews.', 'to accept', ['accepting', 'accept', 'accepted'],
     "The verb 'refuse' takes an infinitive with 'to'.", "'Refuse' fiili daima 'to + infinitive' alır.",
     {'accepting': "'Refuse' gerund almaz.", 'accept': "'To' eksiktir.", 'accepted': 'Geçmiş zaman kipi gelemez.'}),
    ('She finished ___ the summary report just before the 5 PM deadline.', 'writing', ['to write', 'write', 'wrote'],
     "The verb 'finish' strictly takes a gerund.", "'Finish' fiili daima gerund (-ing) alır.",
     {'to write': "'Finish to do' İngilizcede yanlıştır.", 'write': 'Yalın fiil gelemez.', 'wrote': 'Geçmiş zaman kipi gelemez.'}),
    ('We agreed ___ the terms of the revised vendor contract.', 'to sign', ['signing', 'sign', 'signed'],
     "The verb 'agree' takes an infinitive with 'to'.", "'Agree' fiili 'to + infinitive' alır.",
     {'signing': "'Agree signing' kullanılmaz.", 'sign': "'To' eksiktir.", 'signed': 'Geçmiş zaman kipi gelemez.'}),
    ('He insisted on ___ the entire database backup manually.', 'verifying', ['to verify', 'verify', 'verified'],
     "Preposition 'on' in 'insist on' strictly takes a gerund.", "'Insist on' edatından sonra gerund ('verifying') gelir.",
     {'to verify': "Edattan sonra 'to' gelemez.", 'verify': 'Yalın fiil gelemez.', 'verified': 'Geçmiş zaman kipi gelemez.'}),
], 'Choose between gerund (-ing) and infinitive (to + verb):', 'Edatlardan sonra ve belirli fiillerin ardından gelen ulaç (-ing) ve mastar (to + V) yapılarını seçiniz.')

