#!/usr/bin/env python3
"""
Comprehensive Exercise Generator for A2 Grammar.
Generates exactly 20 exercises for each of the 10 A2 grammar lessons = 200 exercises.
"""
from mcq_balancer import McqBalancer

balancer = McqBalancer(seed=701)

def make_ex(ex_id, target_id, level, prompt_en, prompt_tr, stem, correct, distractors, exp_en, exp_tr, dist_exps, diff="standard"):
    options, idx = balancer.balance_options(correct, distractors)
    return {
        "id": ex_id,
        "target_content_id": target_id,
        "cefr_level": level,
        "skill_domain": "grammar",
        "exercise_type": "multiple_choice",
        "prompt_en": prompt_en,
        "prompt_tr_hint": prompt_tr,
        "stem": stem,
        "options": options,
        "correct_answer": correct,
        "explanation_en": exp_en,
        "explanation_tr": exp_tr,
        "distractor_explanations": dist_exps,
        "difficulty": diff,
        "status": "APPROVED",
        "version": 1
    }

A2_EXERCISES = []

# Helper to add batches of 20
def add_lesson(lesson_id, short_id, items, prompt_en, prompt_tr):
    for i, data in enumerate(items, 1):
        stem, corr, dists, en_exp, tr_exp, d_exps = data
        A2_EXERCISES.append(make_ex(f"exercise.a2.{short_id}-{i:02d}", lesson_id, "A2",
                                    prompt_en, prompt_tr, stem, corr, dists, en_exp, tr_exp, d_exps))

# 1. Present Simple vs Continuous
add_lesson("grammar.a2.present-simple-vs-continuous", "pres-simp-cont", [
    ("He usually ___ emails in the morning, but right now he is in a meeting.", "answers", ["is answering", "answer", "answered"],
     "Routine actions require Present Simple with 3rd person singular '-s'.", "Genel rutinler için Present Simple ve he/she/it öznesinde '-s' takısı gereklidir.",
     {"is answering": "Şu an devam eden anlık eylemler içindir, 'usually' rutinine uymaz.", "answer": "Üçüncü tekil şahıs öznesi 'he' için fiil yalın kalamaz.", "answered": "Geçmiş zaman geçmişte tamamlanmış olaylar içindir."}),
    ("Look! The engineering lead ___ the new design prototype on the whiteboard.", "is drawing", ["draws", "draw", "drew"],
     "'Look!' signals an action happening right at the moment of speech.", "'Look!' ifadesi konuşma anında devam eden bir eylemi bildirir.",
     {"draws": "Geniş zaman alışkanlıkları anlatır, konuşma anını değil.", "draw": "Tekil özneyle fiil yalın kullanılamaz.", "drew": "Geçmiş zaman bu anlık bağlama uymaz."}),
    ("Our team ___ weekly progress reports every Friday afternoon.", "submits", ["is submitting", "submit", "submitted"],
     "'Every Friday' denotes a habitual action requiring Present Simple.", "'Every Friday' düzenli tekrar eden bir rutini gösterir.",
     {"is submitting": "Sürekli tekrarlanan genel alışkanlıklarda şimdiki zaman tercih edilmez.", "submit": "Tekil 'our team' öznesi için fiil '-s' almalıdır.", "submitted": "Geçmiş zaman rutin bildiren 'every' ile uyumsuzdur."}),
    ("Listen! The servers ___ an unusual high-pitched noise.", "are making", ["make", "makes", "made"],
     "'Listen!' indicates an event occurring at the present moment.", "'Listen!' konuşma anında gerçekleşen olayı işaret eder.",
     {"make": "Geniş zaman anlık sesler için kullanılmaz.", "makes": "Çoğul özne 'servers' tekil fiil alamaz.", "made": "Geçmiş zaman şimdiki anı anlatmaz."}),
    ("I usually work remotely, but this week I ___ from the Istanbul office.", "am working", ["work", "works", "worked"],
     "'This week' indicates a temporary state requiring Present Continuous.", "'This week' geçici bir durumu ifade ettiği için Present Continuous gerektirir.",
     {"work": "Geniş zaman kalıcı rutinleri ifade eder, geçici durumları değil.", "works": "'I' öznesi '-s' takısı almaz.", "worked": "Geçmiş zaman bu haftaki devam eden duruma uymaz."}),
    ("Water ___ at one hundred degrees Celsius.", "boils", ["is boiling", "boil", "boiled"],
     "Scientific facts require Present Simple.", "Bilimsel gerçekler geniş zaman (Present Simple) gerektirir.",
     {"is boiling": "Şimdiki zaman anlık süreçler içindir, evrensel doğa yasaları geniş zamanla verilir.", "boil": "Tekil sayılamayan 'water' öznesi '-s' gerektirir.", "boiled": "Geçmiş zaman genel bir doğa kuralını ifade edemez."}),
    ("Why ___ you wearing a safety helmet today?", "are", ["do", "does", "is"],
     "Present Continuous question with 'you' requires the auxiliary 'are'.", "'You' öznesiyle şimdiki zaman soru cümlesinde 'are' yardımcı fiili kullanılır.",
     {"do": "Geniş zaman yardımcı fiilidir, '-ing' ile doğrudan soru kuramaz.", "does": "Üçüncü tekil şahıslar içindir.", "is": "'You' öznesiyle 'is' kullanılamaz."}),
    ("Our software architect ___ three foreign languages fluently.", "speaks", ["is speaking", "speak", "spoke"],
     "Permanent ability requires Present Simple.", "Kalıcı yetenek ve diller geniş zamanla anlatılır.",
     {"is speaking": "Şu an konuşma eylemini anlatır, kalıcı dil bilme durumunu değil.", "speak": "Tekil özne '-s' takısı almalıdır.", "spoke": "Geçmiş zaman şu anki yeteneği karşılamaz."}),
    ("Be quiet, please! The CEO ___ on the international conference call.", "is speaking", ["speaks", "speak", "spoke"],
     "'Be quiet!' indicates an action currently in progress.", "'Be quiet!' konuşma anındaki eylemi işaret eder.",
     {"speaks": "Rutin değil, şu an devam eden bir konuşmadır.", "speak": "Yalın fiil şimdiki zaman için eksiktir.", "spoke": "Geçmiş zaman anlık duruma uymaz."}),
    ("How often ___ your team deploy code to production?", "does", ["is", "do", "are"],
     "'How often' asks about frequency, requiring Present Simple with singular team subject.", "'How often' sıklık sorar ve tekil 'team' öznesi 'does' gerektirir.",
     {"is": "Geniş zaman sıklık sorularında eylem fiiliyle 'is' kullanılmaz.", "do": "Tekil topluluk ismiyle 'does' kullanılır.", "are": "Eylem fiili yalınken 'are' yardımcı fiil olamaz."}),
    ("Right now, our database administrator ___ the corrupted table indices.", "is repairing", ["repairs", "repair", "repaired"],
     "'Right now' strictly requires the Present Continuous aspect.", "'Right now' tam şu anı ifade eder ve şimdiki zaman gerektirir.",
     {"repairs": "Geniş zaman anlık devam eden eylemlere uymaz.", "repair": "Tekil özne yalın fiil alamaz.", "repaired": "Geçmiş zaman şu ana ait değildir."}),
    ("The company ___ a monthly newsletter to all registered subscribers.", "sends", ["is sending", "send", "sent"],
     "'Monthly' indicates a regular recurring schedule.", "'Monthly' düzenli aralıklarla tekrarlanan bir rutini gösterir.",
     {"is sending": "Sürekli tekrarlanan bülten dağıtımı geniş zamanla ifade edilir.", "send": "Şirket tekil bir özne olduğu için '-s' almalıdır.", "sent": "Geçmiş zaman genel döngüyü kapsamaz."}),
    ("Look at the monitor! The download progress bar ___ rapidly.", "is advancing", ["advances", "advance", "advanced"],
     "'Look at...' calls attention to an unfolding real-time event.", "Konuşma anında ekranda ilerleyen süreç şimdiki zaman gerektirir.",
     {"advances": "Geniş zaman anlık gözlemlenen görsel hareketi karşılamaz.", "advance": "Tekil özne yalın fiille eşleşmez.", "advanced": "Eylem geçmişte bitmemiştir."}),
    ("She always ___ her code before opening a pull request.", "tests", ["is testing", "test", "tested"],
     "'Always' expresses a consistent professional habit.", "'Always' profesyonel bir alışkanlığı ve kuralı ifade eder.",
     {"is testing": "Kalıcı kural ve alışkanlıklarda şimdiki zaman kullanılmaz.", "test": "Üçüncü tekil şahıs için '-s' eksiktir.", "tested": "Her zaman yapılan iş için geçmiş zaman yanlıştır."}),
    ("Currently, the security team ___ network logs for unauthorized access.", "is monitoring", ["monitors", "monitor", "monitored"],
     "'Currently' with ongoing surveillance requires Present Continuous.", "'Currently' devam etmekte olan izleme sürecini anlatır.",
     {"monitors": "Rutin bildirir, mevcut devam eden süreci değil.", "monitor": "Tekil ekip öznesiyle uyumsuzdur.", "monitored": "Olay geçmişte tamamlanmış değildir."}),
    ("The morning train to the tech campus ___ at eight-fifteen sharp.", "departs", ["is departing", "depart", "departed"],
     "Timetables and fixed schedules require Present Simple.", "Tarifeli ve planlı seferler geniş zaman gerektirir.",
     {"is departing": "Sabit tarifeli kamu ulaşımında geniş zaman tercih edilir.", "depart": "Tekil tren öznesi '-s' takısı almalıdır.", "departed": "Düzenli kalkan tren için geçmiş zaman kullanılmaz."}),
    ("Don't disconnect the cable! The system ___ a backup archive.", "is creating", ["creates", "create", "created"],
     "Imperative warning 'Don't...!' signals an active in-flight operation.", "'Don't disconnect!' uyarısı o anda süren işlemi gösterir.",
     {"creates": "Genel özellik değil, o an süren işlemdir.", "create": "Yardımcı fiilsiz yalın form şimdiki zaman olamaz.", "created": "İşlem henüz bitmemiştir."}),
    ("Most web developers ___ coffee during their morning standup.", "drink", ["are drinking", "drinks", "drank"],
     "General observation about a group requires Present Simple plural form.", "Çoğul özneyle genel gözlem Present Simple yalın fiil gerektirir.",
     {"are drinking": "Geniş zamanlı genel gerçeği şimdiki zamana sıkıştırmaz.", "drinks": "Çoğul özne 'developers' '-s' almaz.", "drank": "Geçmiş zaman alışkanlığı yansıtmaz."}),
    ("Why ___ you checking your phone during the presentation?", "are", ["do", "does", "is"],
     "Ongoing action in progress requires 'are' with 'you'.", "'You' ile anlık devam eden eylem sorusu 'are' gerektirir.",
     {"do": "Fiil '-ing' aldığından 'do' kullanılamaz.", "does": "'You' öznesiyle kullanılmaz.", "is": "Çoğul/ikinci şahısla uyumsuzdur."}),
    ("The company founder rarely ___ public technical interviews.", "gives", ["is giving", "give", "gave"],
     "'Rarely' expresses negative frequency in Present Simple.", "'Rarely' sıklık zarfı geniş zaman ve tekil '-s' gerektirir.",
     {"is giving": "Sıklık zarfları şimdiki zamanla çelişir.", "give": "Tekil kurucu öznesi '-s' almalıdır.", "gave": "Genel kural için geçmiş zaman kullanılmaz."})
], "Choose the correct verb form:", "Zaman zarfına dikkat ederek doğru biçimi seçiniz.")

# 2. Past Simple: Regular & Irregular
add_lesson("grammar.a2.past-simple-regular-irregular", "past-simp", [
    ("Yesterday morning, the team ___ the final sprint deliverables.", "completed", ["complete", "completing", "has completed"],
     "Yesterday is a finished past time marker requiring Past Simple.", "Dün sabah kapalı geçmiş zaman olup Past Simple gerektirir.",
     {"complete": "Geniş zaman dünü ifade edemez.", "completing": "Yardımcı fiilsiz '-ing' geçmiş zaman yüklemi olamaz.", "has completed": "'Yesterday' ile Present Perfect kullanılamaz."}),
    ("They ___ thirty new servers for the European datacenter last month.", "bought", ["buy", "buyed", "have bought"],
     "'Buy' has the irregular past form 'bought'.", "'Buy' düzensiz bir fiil olup geçmiş zaman hali 'bought'tur.",
     {"buy": "Geçen ay için şimdiki zaman fiili kullanılamaz.", "buyed": "İngilizcede 'buyed' diye bir form yoktur, düzensizdir.", "have bought": "'Last month' ile Present Perfect kullanılmaz."}),
    ("She ___ the error in the server log two hours ago.", "found", ["find", "finded", "has found"],
     "'Ago' indicates a finished past event; past of 'find' is 'found'.", "'Ago' tamamlanmış geçmişi gösterir; 'find' düzensizdir.",
     {"find": "Geçmiş zaman için yalın fiil kullanılamaz.", "finded": "Düzenli '-ed' almaz, 'found' olmalıdır.", "has found": "'Two hours ago' net geçmiş zamandır."}),
    ("We ___ not receive the confirmation email yesterday.", "did", ["do", "does", "have"],
     "Negative past simple questions and statements use auxiliary 'did'.", "Past Simple olumsuz cümlelerde yardımcı fiil 'did' kullanılır.",
     {"do": "Geniş zaman yardımcı fiilidir.", "does": "Üçüncü tekil geniş zaman içindir.", "have": "'Did not receive' yapısında 'have' yer alamaz."}),
    ("Why ___ the production build fail last night?", "did", ["does", "do", "is"],
     "Past Simple questions use the auxiliary 'did'.", "Geçmiş zaman sorularında 'did' kullanılır.",
     {"does": "Dün gece için geniş zaman yardımcı fiili kullanılamaz.", "do": "Geçmiş zamanla uyumsuzdur.", "is": "Ana fiil 'fail' varken 'is' yardımcı fiil olamaz."}),
    ("The senior architect ___ the revised database architecture on Monday.", "explained", ["explain", "explaining", "explains"],
     "Regular past simple takes the '-ed' suffix.", "Düzenli fiiller geçmiş zamanda '-ed' takısı alır.",
     {"explain": "Geçmiş zaman için yalın kalamaz.", "explaining": "Yüklem tek başına '-ing' olamaz.", "explains": "Geçmiş zaman için geniş zaman '-s' yanlıştır."}),
    ("The intern ___ the laptop charger at the office yesterday evening.", "left", ["leave", "leaved", "has left"],
     "The irregular past form of 'leave' is 'left'.", "'Leave' fiilinin geçmiş zaman hali düzensiz olarak 'left'tir.",
     {"leave": "Geçmiş için yalın fiil yanlıştır.", "leaved": "Kuralsız fiile '-ed' eklenemez.", "has left": "Dün akşam zaman belirteciyle Present Perfect kullanılmaz."}),
    ("I ___ three bug reports to the QA team before leaving the office.", "sent", ["send", "sended", "sending"],
     "Irregular past form of 'send' is 'sent'.", "'Send' fiilinin geçmiş hali 'sent'tir.",
     {"send": "Geçmiş eylem için yalın kalamaz.", "sended": "Fiil düzenli değildir, 'sended' hatalıdır.", "sending": "Yardımcı fiilsiz fiil yüklem olamaz."}),
    ("Did you ___ the new deployment documentation?", "read", ["readed", "reading", "reads"],
     "After auxiliary 'did', the main verb must remain in its base form.", "'Did' yardımcı fiilinden sonra ana fiil yalın halde kalır.",
     {"readed": "'Read' fiiline asla '-ed' eklenmez.", "reading": "'Did' sonrası '-ing' gelemez.", "reads": "'Did' varken fiile '-s' takısı eklenmez."}),
    ("The company ___ forty junior developers during the summer campus drive.", "hired", ["hire", "hiring", "hires"],
     "Regular verb 'hire' takes '-ed' for completed past action.", "'Hire' düzenli fiil olup geçmiş zamanda '-ed' alır.",
     {"hire": "Geçmiş için yalın fiil yetersizdir.", "hiring": "Yardımcı fiilsiz yüklem olamaz.", "hires": "Geçmiş olay için geniş zaman kullanılmaz."}),
    ("He ___ to the office on foot yesterday because the metro was closed.", "went", ["go", "goed", "gone"],
     "Irregular past form of 'go' is 'went'.", "'Go' fiilinin Past Simple hali 'went'tir.",
     {"go": "Yalın fiil dünü anlatamaz.", "goed": "İngilizcede 'goed' diye bir form yoktur.", "gone": "'Gone' yalnızca yardımcı fiille (have/had) kullanılır."}),
    ("We ___ the contract last Tuesday after three hours of negotiation.", "signed", ["sign", "signing", "signs"],
     "Completed past event requires regular past form 'signed'.", "Geçen salı tamamlanan eylem 'signed' gerektirir.",
     {"sign": "Geçmiş zaman yalın olamaz.", "signing": "Yüklem olamaz.", "signs": "Geniş zaman yanlıştır."}),
    ("She ___ a glass of water before starting her presentation.", "drank", ["drink", "drinked", "drunk"],
     "The past form of irregular verb 'drink' is 'drank'.", "'Drink' fiilinin geçmiş zaman hali 'drank'tir.",
     {"drink": "Yalın hal geçmişi göstermez.", "drinked": "Fiil düzensizdir, '-ed' almaz.", "drunk": "Past participle hali olup Past Simple'da tek başına kullanılmaz."}),
    ("They ___ not understand the error message printed on the screen.", "did", ["do", "does", "were"],
     "Negative past statements use 'did not'.", "Geçmişte olumsuz eylem 'did not' gerektirir.",
     {"do": "Şimdiki zaman/geniş zaman yardımcı fiilidir.", "does": "Tekil geniş zamandır.", "were": "'Understand' ana fiili varken 'were not understand' denemez."}),
    ("The power grid failure ___ the primary cooling fans in the server room.", "stopped", ["stop", "stoped", "stopping"],
     "Spelling rule: one-syllable CVC verbs double the consonant ('stopped').", "Tek heceli sessiz-sesli-sessiz fiillerde son harf çiftleşir ('stopped').",
     {"stop": "Geçmiş zaman için yalın kalamaz.", "stoped": "Tek 'p' ile yazım kural hatasıdır.", "stopping": "Zaman eki almamıştır."}),
    ("Where ___ you meet our new technical director yesterday?", "did", ["do", "does", "have"],
     "Question about finished past time uses 'did'.", "Dün gerçekleşen soru için 'did' kullanılır.",
     {"do": "Geniş zaman yardımcı fiilidir.", "does": "Üçüncü tekil geniş zamandır.", "have": "Dün için Present Perfect sorusu kurulamaz."}),
    ("The security engineer ___ the suspicious IP address immediately.", "blocked", ["block", "blocking", "blocks"],
     "Completed event takes regular past '-ed'.", "Tamamlanan eylem düzenli '-ed' alır.",
     {"block": "Yalın fiil geçmişi anlatamaz.", "blocking": "Yardımcı fiilsiz yüklem olamaz.", "blocks": "Geniş zaman yanlıştır."}),
    ("We ___ our train tickets online three days ago.", "bought", ["buy", "buyed", "have bought"],
     "'Ago' mandates Past Simple with irregular 'bought'.", "'Ago' düzensiz 'bought' ile Past Simple gerektirir.",
     {"buy": "Yalın fiil yanlıştır.", "buyed": "Hatalı uydurma formdur.", "have bought": "'Ago' ile Present Perfect kullanılmaz."}),
    ("The CEO ___ the annual keynote speech in front of five hundred employees.", "gave", ["give", "gived", "given"],
     "The past form of 'give' is 'gave'.", "'Give' düzensiz fiilinin geçmiş hali 'gave'dir.",
     {"give": "Yalın hal geçmişi anlatamaz.", "gived": "Düzensiz fiile '-ed' eklenemez.", "given": "Tek başına Past Simple yüklemi olamaz."}),
    ("They ___ the project kick-off meeting on Zoom last Friday.", "held", ["hold", "holded", "holding"],
     "Irregular past form of 'hold' is 'held'.", "'Hold' fiilinin geçmiş hali 'held'dir.",
     {"hold": "Geçmiş için yalın fiil kullanılamaz.", "holded": "Hatalı düzenli uydurmadır.", "holding": "Yardımcı fiilsiz yüklem olamaz."})
], "Choose the correct past simple verb form:", "Tamamlanmış geçmiş zaman kuralına dikkat ediniz.")

# 3. Future Plans: Will vs Be Going To
add_lesson("grammar.a2.future-plans-will-going-to", "future-plans", [
    ("Look at those dark clouds! It ___ rain very soon.", "is going to", ["will", "shall", "is raining"],
     "Physical visible evidence in the present requires 'be going to'.", "Şu anki somut fiziksel kanıta dayanan tahminler 'be going to' gerektirir.",
     {"will": "Anlık karar veya kanıtsız sezgiler için 'will' kullanılır, burada açık kanıt vardır.", "shall": "Eski dilde birinci şahıs teklifleri içindir.", "is raining": "Şu an yağan yağmuru bildirir, geleceği değil."}),
    ("The phone is ringing. I ___ answer it!", "will", ["am going to", "going to", "shall be"],
     "Spontaneous decisions made at the moment of speech require 'will'.", "Konuşma anında aniden verilen spontane kararlar 'will' gerektirir.",
     {"am going to": "Önceden tasarlanmış niyetler içindir, ani kararlarda kullanılmaz.", "going to": "'am' olmadan eksik yapıdır.", "shall be": "Sıradan yanıtlar için doğal değildir."}),
    ("We have already bought our tickets. We ___ visit the tech conference in Berlin.", "are going to", ["will", "shall", "would"],
     "Pre-arranged plans with prior action already taken require 'be going to'.", "Bileti alınmış, önceden planlanmış niyetler 'be going to' gerektirir.",
     {"will": "Önceden planlanmış kesin niyetler 'will' ile verilmez.", "shall": "Plan bildirmek için kullanılmaz.", "would": "Koşullu geçmiş kipidir."}),
    ("I don't think artificial intelligence ___ replace human software engineers completely.", "will", ["is going to", "are going to", "shall"],
     "Personal opinions with 'I think / I don't think' require 'will'.", "'I think / I don't think' ile yapılan kişisel tahminlerde 'will' kullanılır.",
     {"is going to": "Kişisel kanaat bildiren 'I don't think' kalıbıyla genellikle 'will' tercih edilir.", "are going to": "'AI' tekil öznesine çoğul fiil gelemez.", "shall": "Üçüncü şahıslarla tahminlerde kullanılmaz."}),
    ("Don't worry about the heavy server box. I ___ carry it for you.", "will", ["am going to", "going to", "shall to"],
     "Spontaneous offers of assistance require 'will'.", "Anlık yardım teklifleri 'will' gerektirir.",
     {"am going to": "Önceden planlanmış plan bildirir, anlık teklif için doğal değildir.", "going to": "Yardımcı fiili eksiktir.", "shall to": "'Shall' arkasından 'to' almaz."}),
    ("Next year, our company ___ open a regional branch in Tokyo.", "is going to", ["will to", "is going", "shall"],
     "Prior strategic decisions and company intentions require 'is going to'.", "Şirketin önceden kararlaştırılmış kurumsal planları 'is going to' gerektirir.",
     {"will to": "Modal 'will' arkasından 'to' alamaz.", "is going": "Gelecek zaman bildiren 'to open' mastarı eksiktir.", "shall": "Üçüncü şahıs kurumsal planlarda kullanılmaz."}),
    ("I forgot to send the attachment! I ___ forward it right away.", "will", ["am going to", "going to", "was going to"],
     "Spontaneous immediate reaction to a realization takes 'will'.", "Hatanın farkına varıldığı anda verilen ani karar 'will' alır.",
     {"am going to": "Önceden planlanmış işler içindir.", "going to": "Eksik yardımcı fiildir.", "was going to": "Geçmişte niyet edilip yapılamayan işleri anlatır."}),
    ("She has applied for the visa. She ___ study computer science in London.", "is going to", ["will", "would", "shall"],
     "Prior steps completed indicate a planned intention ('is going to').", "Vize başvurusu yapılmış somut bir plan 'is going to' gerektirir.",
     {"will": "Spontane kararlar içindir.", "would": "Varsayımsal koşul kipidir.", "shall": "Üçüncü şahıslarla gelecek planı anlatmaz."}),
    ("I promise I ___ never disclose your system passwords to anyone.", "will", ["am going to", "going to", "shall to"],
     "Promises strictly require 'will'.", "Verilen sözler ve taahhütler kesinlikle 'will' gerektirir.",
     {"am going to": "Söz verme kalıbı 'I promise I will' şeklindedir.", "going to": "Gramer olarak eksiktir.", "shall to": "Hatalı sözdizimidir."}),
    ("Be careful! The ladder is wobbling; you ___ fall!", "are going to", ["will", "shall", "would"],
     "Immediate imminent physical danger visible right now takes 'be going to'.", "Gözle görülür ani tehlike durumlarında 'be going to' kullanılır.",
     {"will": "Göz önündeki fiziksel kanıt varken 'will' zayıf kalır.", "shall": "Uyarı durumlarına uymaz.", "would": "Geçmiş/koşul kipidir."}),
    ("We are completely out of coffee beans. - No problem, I ___ buy some at the grocery store.", "will", ["am going to", "going to", "would"],
     "Instantaneous reaction to new information takes 'will'.", "Yeni öğrenilen bilgiye karşı verilen anlık karar 'will' alır.",
     {"am going to": "Haberi önceden bilip plan yapmış gibi görünür, anlık duruma uymaz.", "going to": "Yardımcı fiili yoktur.", "would": "Şimdiki kararı anlatamaz."}),
    ("They have saved fifty thousand dollars. They ___ purchase new datacenter hardware.", "are going to", ["will", "shall", "would"],
     "Saving money is concrete prior preparation for a future plan ('are going to').", "Para biriktirmek gelecekteki somut planın hazırlığıdır ('are going to').",
     {"will": "Anlık karar değildir, hazırlığı yapılmıştır.", "shall": "Çoğul üçüncü şahısla plan bildirilmez.", "would": "Geçmiş niyet kipidir."}),
    ("I hope our software build ___ pass all security checks.", "will", ["is going to", "are going to", "shall to"],
     "'I hope' naturally pairs with 'will' for hopeful future expectations.", "'I hope' umut bildiren ifadeler doğal olarak 'will' ile kullanılır.",
     {"is going to": "Umut ve dileklerde 'will' standarttır.", "are going to": "Tekil özne 'build' çoğul alamaz.", "shall to": "'Shall' 'to' almaz."}),
    ("The printer has run out of paper. - I ___ fetch a fresh pack from the cabinet.", "will", ["am going to", "going to", "shall to"],
     "Spontaneous helpful response to an immediate need requires 'will'.", "Anlık yardım cevabı 'will' gerektirir.",
     {"am going to": "Önceden planlanmış hissi verir.", "going to": "Yardımcı fiilsizdir.", "shall to": "Hatalı yapıdır."}),
    ("Look at the time! We ___ be late for the client demonstration.", "are going to", ["will", "shall", "would"],
     "Clock evidence showing lateness takes 'be going to'.", "Saate bakarak görülen somut gecikme kanıtı 'be going to' alır.",
     {"will": "Açık kanıt varken 'be going to' tercih edilir.", "shall": "Günlük dilde gecikme uyarısına uymaz.", "would": "Varsayımsaldır."}),
    ("I believe the new mobile application ___ succeed in the Turkish market.", "will", ["is going to", "are going to", "shall"],
     "'I believe' expresses subjective belief about the future using 'will'.", "'I believe' öznel inanç belirterek 'will' gerektirir.",
     {"is going to": "Öznel inanç ve tahminlerde 'will' esastır.", "are going to": "Tekil özneyle uyumsuzdur.", "shall": "Üçüncü şahıs tahminlerinde kullanılmaz."}),
    ("Have you decided what to order? - Yes, I ___ have the grilled chicken salad.", "will", ["am going to", "going to", "would to"],
     "Ordering food at a restaurant is a classic spontaneous 'will' decision.", "Restoranda sipariş verirken konuşma anında 'will' kullanılır.",
     {"am going to": "Restoranda sipariş verirken 'I will have' kalıplaşmıştır.", "going to": "Eksik yapıdır.", "would to": "'Would' 'to' alamaz."}),
    ("The executive board has formally approved the budget. We ___ recruit five designers.", "are going to", ["will", "shall", "would"],
     "Formal approval constitutes prior organizational decision ('are going to').", "Resmi onay önceden alınmış kararı gösterir ('are going to').",
     {"will": "Anlık karar değildir, onaylanmış plandır.", "shall": "Kurumsal planda kullanılmaz.", "would": "Koşullu kuraldır."}),
    ("Wait a second! I ___ walk to the subway with you.", "will", ["am going to", "going to", "shall to"],
     "'Wait a second!' precedes an immediate spontaneous decision.", "'Bir saniye bekle!' ifadesi anlık spontane bir kararı bildirir.",
     {"am going to": "Önceden kurgulanmış plan izlenimi verir.", "going to": "Eksiktir.", "shall to": "Hatalı kullanımdır."}),
    ("According to the weather forecast, tomorrow ___ be warm and sunny.", "will", ["is going to", "shall", "would to"],
     "Official weather forecasts traditionally use 'will'.", "Hava durumu bültenlerinde genel tahmin için 'will' kullanılır.",
     {"is going to": "Bülten dilinde 'will' yaygın standarttır.", "shall": "Üçüncü şahıslarla hava durumunda kullanılmaz.", "would to": "Hatalı yapıdır."})
], "Choose between will and be going to:", "Spontane karar ile önceden yapılmış plan ayrımına dikkat ediniz.")

# 4. Comparatives and Superlatives
add_lesson("grammar.a2.comparatives-superlatives", "comp-sup", [
    ("This new SSD is significantly ___ than our legacy mechanical hard drive.", "faster", ["fast", "more fast", "fastest"],
     "One-syllable adjectives form comparatives with '-er'.", "Tek heceli sıfatlar karşılaştırmada '-er' takısı alır.",
     {"fast": "Karşılaştırmada 'than' varken yalın sıfat kullanılamaz.", "more fast": "Tek heceli sıfatlar 'more' almaz.", "fastest": "Üstünlük (superlative) derecesidir, 'than' ile kullanılmaz."}),
    ("Python is considered ___ to learn than C++ for beginning developers.", "easier", ["easy", "more easy", "easiest"],
     "Two-syllable adjectives ending in '-y' change 'y' to '-ier'.", "'-y' ile biten iki heceli sıfatlar 'y' düşerek '-ier' alır.",
     {"easy": "'Than' varken yalın kalamaz.", "more easy": "'-y' ile bitenlerde 'more' yerine '-ier' kuralı geçerlidir.", "easiest": "Süperlatif formdur."}),
    ("Cloud security is the ___ priority for our engineering infrastructure.", "highest", ["higher", "most high", "high"],
     "'The' indicates a superlative adjective; one-syllable takes '-est'.", "'The' üstünlük derecesi gösterir; tek heceliler '-est' alır.",
     {"higher": "İki şeyin kıyası için 'higher than' denir; 'the' tek başına süperlatif ister.", "most high": "Tek heceli sıfat 'most' almaz.", "high": "Yalın sıfat süperlatif yapamaz."}),
    ("This cloud provider is much more ___ than its local competitor.", "reliable", ["reliable than", "relier", "reliablest"],
     "Three-syllable adjectives take 'more' for comparison.", "Üç ve daha fazla heceli sıfatlar 'more' ile karşılaştırılır.",
     {"reliable than": "'More' zaten vardır, sıfat yalın kalır.", "relier": "Çok hecelilere '-er' eklenemez.", "reliablest": "Hatalı formdur."}),
    ("That was the ___ technical presentation I have ever attended.", "worst", ["bad", "baddest", "worse"],
     "Irregular superlative of 'bad' is 'worst'.", "'Bad' sıfatının düzensiz süperlatif hali 'worst'tür.",
     {"bad": "'The' sonrası yalın sıfat gelemez.", "baddest": "İngilizcede böyle bir form yoktur, düzensizdir.", "worse": "Karşılaştırma (comparative) halidir, süperlatif değildir."}),
    ("Our new microservice architecture is ___ than the old monolith.", "better", ["good", "gooder", "best"],
     "Irregular comparative of 'good' is 'better'.", "'Good' sıfatının karşılaştırma hali düzensiz olarak 'better'dır.",
     {"good": "'Than' ile yalın 'good' kullanılamaz.", "gooder": "Böyle bir kelime yoktur, 'good' düzensizdir.", "best": "Süperlatif halidir, 'than' ile kıyasta kullanılmaz."}),
    ("The mobile application is ___ than the desktop website.", "simpler", ["more simpler", "simple", "simplest"],
     "Two-syllable adjectives ending in '-le' take '-er' ('simpler').", "'-le' ile biten sıfatlar '-er' alarak 'simpler' olur.",
     {"more simpler": "Çift karşılaştırma (double comparative) kural hatasıdır.", "simple": "'Than' varken yalın kalamaz.", "simplest": "Süperlatif formdur."}),
    ("Which framework is the ___ popular among backend engineers today?", "most", ["more", "much", "many"],
     "Superlative of long adjectives uses 'the most'.", "Uzun sıfatların süperlatif derecesinde 'the most' kullanılır.",
     {"more": "Karşılaştırma bildirir, 'the' ile en üstünlüğü vermez.", "much": "Miktar bildirir, süperlatif eki değildir.", "many": "Sayılan çoğul isimler içindir."}),
    ("Working from home is often ___ comfortable than commuting to the office.", "more", ["most", "much", "many"],
     "Three-syllable 'comfortable' takes 'more' for comparison.", "'Comfortable' üç heceli olup karşılaştırmada 'more' alır.",
     {"most": "Süperlatif için 'the most' gerekir, 'than' ile 'more' kullanılır.", "much": "Derecelendirme zarfı olabilir ama tek başına kıyaslama yapmaz.", "many": "Sıfat derecelemez."}),
    ("The server room in building B is ___ than the one in building A.", "quieter", ["more quiet", "quietest", "quiet"],
     "Two-syllable adjective 'quiet' takes '-er'.", "'Quiet' iki heceli sıfatı genellikle '-er' alır ('quieter').",
     {"more quiet": "Tek veya iki hecelilerde '-er' öncelikli kuraldır.", "quietest": "Süperlatif haldir.", "quiet": "Kıyaslama yapılmamış yalın haldir."}),
    ("This bug is ___ serious than the one we resolved yesterday.", "less", ["least", "lesser", "little"],
     "Negative comparison uses 'less + adjective + than'.", "Daha az anlamında olumsuz kıyas 'less + sıfat + than' ile kurulur.",
     {"least": "En az anlamındaki süperlatiftir ('the least').", "lesser": "Resmi dilde sınırlı isimlerle kullanılır, sıfat derecelemez.", "little": "Yalın haldir."}),
    ("It was the ___ expensive software license in the entire enterprise catalog.", "most", ["more", "much", "many"],
     "Superlative with long adjective 'expensive' requires 'the most'.", "'Expensive' gibi uzun sıfatlarda en üstünlük 'the most' ile yapılır.",
     {"more": "'The more expensive' kıyasta iki şey arasında kullanılır, katalog bütününde 'most' gerekir.", "much": "Süperlatif oluşturmaz.", "many": "Sıfat önüne gelmez."}),
    ("Air travel is getting ___ expensive every year.", "more", ["most", "much", "many"],
     "Gradual increase uses 'more and more' or 'more + adjective'.", "Giderek artan durumlar 'more and more' veya 'more' ile ifade edilir.",
     {"most": "'The' olmadan süperlatif kullanılamaz.", "much": "Doğrudan kıyas sıfatı oluşturmaz.", "many": "Hatalıdır."}),
    ("My laptop screen is ___ than my tablet screen.", "larger", ["more large", "largest", "large"],
     "One-syllable adjective ending in '-e' adds '-r' ('larger').", "'-e' ile biten tek heceli sıfatlar sadece '-r' alır ('larger').",
     {"more large": "Tek heceli sıfatlar 'more' almaz.", "largest": "Süperlatiftir.", "large": "Yalın haldir."}),
    ("Of all the candidates interviewed, Selin was the ___ qualified.", "most", ["more", "much", "better"],
     "'The' before multi-syllable adjective in a group requires 'most'.", "Bir grup içindeki en üstünlük için 'the most' kullanılır.",
     {"more": "Kıyaslama için iki kişi olmalıydı; adayların bütününde süperlatif gerekir.", "much": "Süperlatif yapmaz.", "better": "Sıfat değil, kendi başına bir kelimedir."}),
    ("This network connection is ___ than the one at my home.", "worse", ["bad", "baddest", "worst"],
     "Comparative of irregular 'bad' is 'worse'.", "'Bad' sıfatının karşılaştırma derecesi 'worse'tur.",
     {"bad": "Yalın sıfattır.", "baddest": "Uydurma hatalı kelimedir.", "worst": "Süperlatif derecesidir."}),
    ("Gold is ___ heavier than aluminum.", "much", ["more", "most", "many"],
     "Adverb modifying comparative adjectives is 'much' or 'far'.", "Karşılaştırma sıfatlarını kuvvetlendirmek için 'much' veya 'far' kullanılır.",
     {"more": "'Heavier' zaten karşılaştırmadır, 'more heavier' çift kıyaslama hatasıdır.", "most": "Kıyaslama zarfı değildir.", "many": "Sayılamayan ağırlık kıyaslamasında kullanılmaz."}),
    ("The CEO is the ___ influential person in the technology summit.", "most", ["more", "much", "many"],
     "Superlative with multi-syllable adjective takes 'the most'.", "Çok heceli sıfatların süperlatifinde 'the most' kullanılır.",
     {"more": "Süperlatif 'the' ile 'more' eşleşmez.", "much": "Süperlatif belirteci değildir.", "many": "Yanlıştır."}),
    ("Public cloud hosting is ___ cheaper than building a private datacenter.", "far", ["more", "most", "many"],
     "'Far' intensifies a comparative adjective ('far cheaper').", "'Far', karşılaştırma sıfatlarını pekiştirmek için 'much' gibi kullanılır.",
     {"more": "'Cheaper' zaten kıyas halindedir, 'more cheaper' hatadır.", "most": "Kıyas zarfı olamaz.", "many": "Miktar sıfatıdır."}),
    ("That was the ___ complex database migration we have ever executed.", "most", ["more", "much", "many"],
     "'Ever executed' indicates an all-time superlative ('the most complex').", "'Şimdiye kadar yürütülen' ifadesi süperlatif 'the most' gerektirir.",
     {"more": "Kıyaslama bildirir, tüm zamanların en iyisini/kötüsünü vermez.", "much": "Süperlatif yapısı kurmaz.", "many": "Sıfat nitelemez."})
], "Select the correct comparative or superlative form:", "Tek ve çok heceli sıfat kurallarına ve 'than/the' ipuçlarına dikkat ediniz.")

# 5. Basic Modals: Ability and Permission (Can, Could, May)
add_lesson("grammar.a2.basic-modals-ability-permission", "modals-abil", [
    ("___ you help me review this pull request for a moment?", "Can", ["May", "Must", "Should"],
     "'Can you...?' is the standard informal/semi-formal request for ability/help.", "'Can you...?' günlük ve iş ortamında standart yardım isteme kalıbıdır.",
     {"May": "'May you...?' İngilizcede soru kalıbı olarak kullanılmaz (yalnızca 'May I...?').", "Must": "Zorunluluk bildirir, nezaket ricası değildir.", "Should": "Tavsiye sorar, doğrudan rica değildir."}),
    ("Excuse me, ___ I ask a question about the deployment architecture?", "may", ["can to", "must", "should to"],
     "'May I...?' is the polite formal request for permission.", "'May I...?' resmi ve son derece kibar izin isteme yapısıdır.",
     {"can to": "Modallar arkasından 'to' alamaz.", "must": "İzin istemek için 'Must I' (zorunda mıyım) uygun değildir.", "should to": "Modal fiiller 'to' almaz."}),
    ("Five years ago, she ___ not write complex database queries.", "could", ["can", "may", "might"],
     "Past general ability requires 'could' (negative: 'could not').", "Geçmişteki genel yetenek 'could' ile ifade edilir.",
     {"can": "Şimdiki zaman yeteneğidir, beş yıl önceye uymaz.", "may": "Geçmiş yetenek bildirmez.", "might": "Geçmiş genel yetenek için 'could' esastır."}),
    ("Developers ___ access the internal documentation portal from any workstation.", "can", ["may to", "could to", "must to"],
     "General present permission/possibility takes 'can + bare infinitive'.", "Genel izin ve olanak bildirmede 'can + yalın fiil' kullanılır.",
     {"may to": "Modallar 'to' almaz.", "could to": "Modal fiil mastar eki almaz.", "must to": "Hatalı sözdizimidir."}),
    ("___ you speak German when you lived in Berlin as a child?", "Could", ["Can", "May", "Must"],
     "Past ability in childhood requires 'Could you...?'.", "Çocukluktaki geçmiş yetenek sorusu 'Could you...?' gerektirir.",
     {"Can": "Geçmiş zamanla çelişir.", "May": "Geçmiş yetenek sormaz.", "Must": "Geçmiş yetenek için kullanılmaz."}),
    ("Visitors ___ not enter the server room without security authorization.", "may", ["can to", "could to", "may to"],
     "Formal prohibition and rules use 'may not'.", "Resmi kurallar ve yasaklamalarda 'may not' kullanılır.",
     {"can to": "'To' mastar eki modal sonrasına gelemez.", "could to": "Hatalı yapıdır.", "may to": "Modal 'to' alamaz."}),
    ("I ___ run three automated tests simultaneously on my laptop.", "can", ["could to", "may to", "am can"],
     "Present ability takes 'can + base verb'.", "Mevcut teknik yetenek ve kapasite 'can' ile ifade edilir.",
     {"could to": "Modallar 'to' almaz.", "may to": "Hatalı yapıdır.", "am can": "İki yardımcı fiil yan yana gelemez."}),
    ("___ I borrow your USB-C adapter for the meeting?", "May", ["Must", "Should to", "Could to"],
     "Polite request for personal permission uses 'May I...?'.", "Kibarca kişisel eşya ödünç istemede 'May I...?' kullanılır.",
     {"Must": "Zorunluluk sorar, izin istemez.", "Should to": "'Should' 'to' almaz.", "Could to": "'Could' 'to' alamaz."}),
    ("When I was an intern, I ___ only write basic HTML pages.", "could", ["can", "may", "must"],
     "Past limitation in ability requires 'could'.", "Stajyerlik dönemindeki geçmiş yetenek 'could' gerektirir.",
     {"can": "Geçmiş zamana uymaz.", "may": "Yetenek bildirmez.", "must": "Zorunluluk bildirir."}),
    ("You ___ leave the conference call early if you have another commitment.", "may", ["can to", "could to", "must to"],
     "Formal granting of permission takes 'may'.", "Resmi izin verme durumlarında 'may' kullanılır.",
     {"can to": "Modallar 'to' alamaz.", "could to": "Hatalı yapıdır.", "must to": "Gramer hatasıdır."}),
    ("Our junior engineer ___ solve complex algorithmic problems quickly.", "can", ["could to", "is can", "cans"],
     "Present ability takes 'can' without third-person '-s'.", "Modallar asla üçüncü tekil şahıs '-s' takısı almaz ('can').",
     {"could to": "'To' alamaz.", "is can": "Hatalı yardımcı fiil çiftlemesidir.", "cans": "Modal fiillere '-s' eklenemez."}),
    ("___ you please send me the meeting minutes when you finish?", "Could", ["May", "Must", "Should to"],
     "'Could you please...?' is a polite, respectful request for action.", "'Could you please...?' saygılı ve kibar bir eylem ricasıdır.",
     {"May": "'May you...?' kalıbı İngilizcede rica için kullanılmaz.", "Must": "Emir gibi algılanır, rica değildir.", "Should to": "'Should' 'to' alamaz."}),
    ("We ___ not deploy the update today because of the network freeze.", "can", ["can to", "could to", "may to"],
     "Present inability due to circumstances takes 'cannot / can not'.", "Mevcut engellerden kaynaklanan yapamama durumu 'cannot' alır.",
     {"can to": "'To' kullanılamaz.", "could to": "Hatalı formdur.", "may to": "Hatalıdır."}),
    ("___ I have a glass of water, please?", "May", ["Must", "Should to", "Could to"],
     "Polite request for permission/service uses 'May I have...?'", "Nezaketle bir şey talep ederken 'May I have...?' kalıbı kullanılır.",
     {"Must": "Zorunluluktur, kibar rica değildir.", "Should to": "Hatalı yapıdır.", "Could to": "'To' modal sonrasına gelemez."}),
    ("Ten years ago, mobile phones ___ not stream high-definition video.", "could", ["can", "may", "must"],
     "Past technological inability takes 'could not'.", "Geçmişteki teknolojik yetersizlik 'could not' ile verilir.",
     {"can": "Şimdiki zamandır.", "may": "Yetenek anlatmaz.", "must": "Geçmiş yetersizlik için kullanılmaz."}),
    ("You ___ use my workstation while your laptop is updating.", "can", ["could to", "can to", "may to"],
     "Informal granting of permission uses 'can'.", "Günlük izin vermede 'can' kullanılır.",
     {"could to": "'To' alamaz.", "can to": "Hatalı sözdizimidir.", "may to": "Hatalıdır."}),
    ("___ you hear the speaker clearly in the back of the auditorium?", "Could", ["Can to", "May", "Must"],
     "Past ability to perceive at an event requires 'Could you...?'.", "Etkinlikteki geçmiş algılama yeteneği 'Could you...?' gerektirir.",
     {"Can to": "'To' alamaz.", "May": "Geçmiş yetenek sormaz.", "Must": "Zorunluluk bildirir."}),
    ("Clients ___ download their monthly invoices directly from the portal.", "can", ["can to", "could to", "may to"],
     "General feature/ability provided by a system takes 'can'.", "Sistemin sunduğu genel kullanım yeteneği 'can' ile ifade edilir.",
     {"can to": "Modallar 'to' almaz.", "could to": "Hatalıdır.", "may to": "Hatalıdır."}),
    ("___ I take this seat, or is it reserved for the keynote speaker?", "May", ["Must", "Should to", "Could to"],
     "Formal polite inquiry for permission uses 'May I take...?'.", "Boş bir yere oturmak için izin isterken 'May I take...?' kullanılır.",
     {"Must": "Zorunluluk bildirir.", "Should to": "Hatalı sözdizimidir.", "Could to": "'Could' 'to' alamaz."}),
    ("Before the patch, attackers ___ exploit the memory buffer vulnerability.", "could", ["can", "may", "must"],
     "Past security vulnerability potential takes 'could'.", "Yama öncesindeki geçmiş potansiyel açıklık 'could' ile ifade edilir.",
     {"can": "Geçmiş zamanla çelişir.", "may": "Geçmiş yetenek anlatmaz.", "must": "Geçmiş potansiyel için kullanılmaz."})
], "Choose the correct modal verb for ability or permission:", "Zaman (şimdiki/geçmiş) ve nezaket derecesine (can/could/may) dikkat ediniz.")

# 6. Modals of Necessity and Obligation (Must, Have to, Need to, Musn't, Don't have to)
add_lesson("grammar.a2.modal-verbs-necessity", "modals-nec", [
    ("You ___ wear your security badge at all times inside the datacenter. It is strictly mandatory.", "must", ["don't have to", "mustn't", "needn't"],
     "Strict rule or strong official obligation requires 'must'.", "Kesin kural ve katı resmi zorunluluklarda 'must' kullanılır.",
     {"don't have to": "Zorunluluk yok demektir, kuralla çelişir.", "mustn't": "Yasak bildirir, takmaman gerekir anlamına gelir.", "needn't": "Gerek yok demektir."}),
    ("Tomorrow is a national holiday, so we ___ wake up early for work.", "don't have to", ["must", "mustn't", "have to"],
     "Lack of obligation/necessity requires 'don't have to'.", "Zorunluluğun bulunmadığı durumlarda 'don't have to' kullanılır.",
     {"must": "Zorunluluk bildirir, tatil günüyle çelişir.", "mustn't": "Yasak bildirir (erken uyanman yasaktır gibi anlamsız olur).", "have to": "Erken kalkmak zorundasın anlamına gelir."}),
    ("You ___ share your production database password with anyone. It is forbidden.", "mustn't", ["don't have to", "must", "have to"],
     "Strict prohibition (forbidden actions) requires 'mustn't'.", "Kesin yasaklamalarda 'mustn't' kullanılır.",
     {"don't have to": "İsteğe bağlılık bildirir ('paylaşmasan da olur'), yasak durumuna uymaz.", "must": "Paylaşmak zorundasın anlamına gelir.", "have to": "Zorunluluk bildirir."}),
    ("Every software engineer ___ pass the annual security compliance exam.", "has to", ["have to", "must to", "needs"],
     "Third-person singular external obligation takes 'has to'.", "Üçüncü tekil şahıs dışsal zorunluluklarda 'has to' kullanılır.",
     {"have to": "Tekil özne 'every engineer' ile 'has to' kullanılır.", "must to": "'Must' 'to' almaz.", "needs": "Arkasından 'to pass' mastarı olmalıdır."}),
    ("We have plenty of cloud storage credits left, so we ___ purchase more today.", "don't need to", ["must", "mustn't", "have to"],
     "Lack of necessity due to sufficient resources takes 'don't need to'.", "Yeterli kaynak olduğunda gereksizlik 'don't need to' ile ifade edilir.",
     {"must": "Almak zorundayız anlamına gelir.", "mustn't": "Yasak bildirir.", "have to": "Gereklilik bildirir."}),
    ("Developers ___ commit API keys directly into public GitHub repositories.", "mustn't", ["don't have to", "must", "have to"],
     "Strict security prohibition takes 'mustn't'.", "Katı güvenlik yasağı 'mustn't' gerektirir.",
     {"don't have to": "'Yüklemesen de olur' gibi algılanır, tehlikeli bir hatadır.", "must": "Yüklemek zorundasın anlamına gelir.", "have to": "Zorunluluk bildirir."}),
    ("In the UK office, drivers ___ drive on the left side of the road.", "have to", ["don't have to", "mustn't", "needs"],
     "Legal traffic regulations represent external obligation ('have to').", "Yasal trafik kuralları dışsal zorunluluk olarak 'have to' gerektirir.",
     {"don't have to": "Zorunluluk yok anlamına gelir, kaza yaratır.", "mustn't": "Soldan sürmek yasaktır anlamına gelir.", "needs": "Yalın fiille doğrudan birleşmez."}),
    ("You ___ print that document; the client accepts digital signatures.", "don't have to", ["must", "mustn't", "have to"],
     "Lack of necessity because a digital alternative exists takes 'don't have to'.", "Dijital imza kabul edildiği için çıktı alma zorunluluğu yoktur ('don't have to').",
     {"must": "Basmak zorundasın anlamına gelir.", "mustn't": "Basman yasaktır anlamına gelir.", "have to": "Gereklilik bildirir."}),
    ("All attendees ___ turn their mobile phones on silent during the keynote.", "must", ["mustn't", "don't have to", "needn't"],
     "Formal institutional instruction during a keynote takes 'must'.", "Sunum sırasındaki resmi talimat 'must' gerektirir.",
     {"mustn't": "Sessize almamalısınız anlamına gelir.", "don't have to": "Zorunlu değil serbestsiniz anlamına gelir.", "needn't": "Gerek yok demektir."}),
    ("She ___ submit her expense receipts before the end of the month to receive reimbursement.", "needs to", ["need to", "must to", "hasn't to"],
     "Third-person singular necessity takes 'needs to'.", "Üçüncü tekil şahısta gereklilik 'needs to' ile verilir.",
     {"need to": "Özne 'she' olduğu için '-s' eksiktir.", "must to": "'Must' 'to' almaz.", "hasn't to": "Böyle bir olumsuz kip İngilizcede yoktur."}),
    ("You ___ touch that exposed electrical wire! It carries high voltage.", "mustn't", ["don't have to", "must", "need to"],
     "Life-threatening prohibition strictly requires 'mustn't'.", "Hayati tehlike içeren yasaklarda 'mustn't' kullanılır.",
     {"don't have to": "'Dokunmasan da olur' gibi gevşek anlam verir, tehlikelidir.", "must": "Dokunmalısın anlamına gelir.", "need to": "Dokunman gerekir anlamına gelir."}),
    ("The office cafeteria provides free fruit, so employees ___ bring snacks.", "don't have to", ["must", "mustn't", "have to"],
     "Lack of necessity takes 'don't have to'.", "Ücretsiz meyve olduğu için getirme zorunluluğu yoktur ('don't have to').",
     {"must": "Getirmek zorundadır anlamına gelir.", "mustn't": "Getirmesi yasaktır anlamına gelir.", "have to": "Zorunluluktur."}),
    ("A candidate ___ bring a government-issued photo ID to the certification exam.", "must", ["mustn't", "doesn't have to", "needn't"],
     "Mandatory regulatory rule for exam entry requires 'must'.", "Sınava giriş için zorunlu kural 'must' gerektirir.",
     {"mustn't": "Getirmemeli anlamına gelir.", "doesn't have to": "Gerek yok anlamına gelir, sınava almazlar.", "needn't": "Gerek yoktur demektir."}),
    ("He ___ work overtime today because all sprint tasks were completed early.", "doesn't have to", ["must", "mustn't", "has to"],
     "Lack of obligation for third-person singular takes 'doesn't have to'.", "Üçüncü tekil şahısta zorunluluk yokluğu 'doesn't have to'dur.",
     {"must": "Fazla mesai yapmak zorunda anlamına gelir.", "mustn't": "Mesai yapması yasaktır anlamına gelir.", "has to": "Zorunluluk bildirir."}),
    ("You ___ click on suspicious links in unverified emails. It could be phishing.", "mustn't", ["don't have to", "must", "need to"],
     "Cybersecurity prohibition requires 'mustn't'.", "Siber güvenlik yasağı kesin olarak 'mustn't' gerektirir.",
     {"don't have to": "Tıklamasan da olur gibi algılanır, yasak bildirmez.", "must": "Tıklamalısın anlamına gelir.", "need to": "Gereklilik bildirir."}),
    ("We ___ backup our code repositories every night to prevent data loss.", "have to", ["mustn't", "don't have to", "must to"],
     "Routine operational necessity takes 'have to'.", "Düzenli operasyonel gereklilik 'have to' ile ifade edilir.",
     {"mustn't": "Yedeklememeliyiz anlamına gelir.", "don't have to": "Gerek yok anlamına gelir.", "must to": "'Must' 'to' alamaz."}),
    ("The conference is completely free, so attendees ___ pay any registration fee.", "don't have to", ["must", "mustn't", "have to"],
     "Lack of financial obligation takes 'don't have to'.", "Mali zorunluluğun olmaması 'don't have to' ile verilir.",
     {"must": "Ödemek zorundalar anlamına gelir.", "mustn't": "Ödemeleri yasaktır anlamına gelir.", "have to": "Zorunluluk bildirir."}),
    ("You ___ smoke anywhere inside the company building. It is against corporate law.", "mustn't", ["don't have to", "must", "have to"],
     "Legal prohibition takes 'mustn't'.", "Yasal sigara içme yasağı 'mustn't' gerektirir.",
     {"don't have to": "İçmesen iyi olur gibi algılanır, yasak belirtmez.", "must": "İçmek zorundasın anlamına gelir.", "have to": "Zorunluluktur."}),
    ("Every developer ___ update their multi-factor authentication tokens every ninety days.", "has to", ["have to", "must to", "needs"],
     "Third-person singular organizational rule takes 'has to'.", "Her geliştirici tekil öznesi için dış kural 'has to'dur.",
     {"have to": "'Every' tekildir, çoğul 'have' almaz.", "must to": "'Must' 'to' alamaz.", "needs": "Yalın fiille bağlanamaz."}),
    ("You ___ attend the optional team social dinner if you have personal errands.", "don't have to", ["must", "mustn't", "have to"],
     "Optional event means absence of obligation ('don't have to').", "İsteğe bağlı etkinlik zorunluluk yokluğunu ('don't have to') ifade eder.",
     {"must": "Katılmak zorundasın anlamına gelir.", "mustn't": "Katılman yasaktır anlamına gelir.", "have to": "Zorunluluk bildirir."})
], "Choose the correct modal of obligation, prohibition, or lack of necessity:", "Zorunluluk (must/have to), yasak (mustn't) ve zorunluluk yokluğu (don't have to) ayrımına dikkat ediniz.")

# 7. Countable vs Uncountable Nouns and Quantifiers
add_lesson("grammar.a2.countable-uncountable-quantifiers", "count-quant", [
    ("How ___ servers are currently running in the Frankfurt datacenter?", "many", ["much", "a little", "any"],
     "'Servers' is a plural countable noun requiring 'how many'.", "'Servers' sayılabilen çoğul isimdir, 'how many' ile sorulur.",
     {"much": "Sayılamayan tekil isimlerle kullanılır.", "a little": "Soru kelimesi değildir, miktar belirtir.", "any": "'How any' diye bir soru kalıbı yoktur."}),
    ("We don't have ___ information about the root cause of the network outage yet.", "much", ["many", "few", "a few"],
     "'Information' is an uncountable noun requiring 'much' in negatives.", "'Information' sayılamayan bir isimdir; olumsuzda 'much' alır.",
     {"many": "Sayılabilen çoğul isimlerle kullanılır ('informations' denemez).", "few": "Sayılabilen çoğullarla kullanılır.", "a few": "Sayılabilen isimler içindir."}),
    ("There are only a ___ open tickets left in our sprint backlog.", "few", ["little", "much", "any"],
     "'Tickets' is countable; 'a few' means a small number.", "'Tickets' sayılabilir çoğuldur; az sayıda olduğunu 'a few' belirtir.",
     {"little": "Sayılamayan isimlerle kullanılır ('a little water').", "much": "Çoğul sayılabilenle kullanılmaz.", "any": "'a any' şeklinde birleşemez."}),
    ("Could you please give me a ___ advice regarding my career path?", "little", ["few", "many", "several"],
     "'Advice' is an uncountable noun; 'a little advice' is correct.", "'Advice' sayılamaz bir isimdir; 'a little advice' (biraz tavsiye) denir.",
     {"few": "Sayılabilenlerle kullanılır ('advices' denemez).", "many": "Sayılamayan isimle kullanılmaz.", "several": "Sayılabilen çoğul isimler içindir."}),
    ("We received ___ positive customer reviews after the release.", "a lot of", ["much", "a little", "any"],
     "'A lot of' works with plural countable nouns in positive statements.", "'A lot of' olumlu cümlelerde çoğul sayılabilen isimlerle kullanılır.",
     {"much": "Olumlu cümlelerde sayılabilen çoğullarla 'much' kullanılmaz.", "a little": "Sayılamayan tekiller içindir.", "any": "Olumlu düz cümlelerde 'bazı/çok' anlamında kullanılmaz."}),
    ("How ___ RAM does this database server require for caching?", "much", ["many", "few", "several"],
     "'RAM / memory' is treated as uncountable requiring 'how much'.", "'RAM' sayılamayan bir kavramdır, 'how much' ile sorulur.",
     {"many": "Sayılabilen çoğul isimler içindir.", "few": "Soru kelimesi değildir.", "several": "Soru kalıbı oluşturmaz."}),
    ("Do you have ___ questions before we conclude the presentation?", "any", ["much", "a little", "little"],
     "Questions with plural countables typically use 'any'.", "Soru cümlelerinde çoğul sayılabilen isimlerle 'any' kullanılır.",
     {"much": "Çoğul 'questions' ile 'much' kullanılamaz.", "a little": "Sayılamayanlar içindir.", "little": "Soru belirteci olarak uyumsuzdur."}),
    ("There is very ___ coffee left in the kitchen pot.", "little", ["few", "many", "several"],
     "'Coffee' (liquid) is uncountable; 'very little' expresses scarcity.", "'Coffee' sayılamayan bir sıvıdır; azlığı 'very little' belirtir.",
     {"few": "Sayılabilen çoğullar içindir.", "many": "Sayılamayanla kullanılmaz.", "several": "Çoğul sayılanlar içindir."}),
    ("We encountered ___ unexpected compilation errors during the build.", "several", ["much", "a little", "little"],
     "'Errors' is plural countable; 'several' means a few/multiple.", "'Errors' sayılabilen çoğuldur; 'several' (birkaç) ile kullanılır.",
     {"much": "Sayılamayanlar içindir.", "a little": "Tekil sayılamayanla kullanılır.", "little": "Sayılamayan içindir."}),
    ("How ___ disk space is remaining on the primary SSD?", "much", ["many", "few", "a few"],
     "'Space' is uncountable when referring to storage capacity.", "Depolama alanı anlamındaki 'space' sayılamaz ('how much').",
     {"many": "Sayılabilen çoğullar içindir.", "few": "Soru kalıbı değildir.", "a few": "Miktar bildirir, soru oluşturmaz."}),
    ("The intern has made ___ progress on the frontend prototype.", "a lot of", ["many", "few", "several"],
     "'Progress' is uncountable; 'a lot of progress' is natural.", "'Progress' (ilerleme) sayılamayan bir isimdir ('a lot of progress').",
     {"many": "Sayılamayan isimle 'many' kullanılamaz ('progresses' denmez).", "few": "Sayılabilenler içindir.", "several": "Sayılabilen çoğullar içindir."}),
    ("We need a ___ more minutes to finalize the presentation slides.", "few", ["little", "much", "any"],
     "'Minutes' is plural countable; 'a few more minutes' is standard.", "'Minutes' sayılabilen çoğuldur; 'a few more' kullanılır.",
     {"little": "Sayılamayan isimler içindir.", "much": "Çoğul isimlerle eşleşmez.", "any": "'a any' yapısı kurulamaz."}),
    ("There isn't ___ traffic on the highway this early in the morning.", "much", ["many", "few", "several"],
     "'Traffic' is uncountable; negative takes 'much'.", "'Traffic' sayılamaz bir isimdir; olumsuzda 'much' alır.",
     {"many": "Sayılamayan isimle 'many' kullanılmaz.", "few": "Olumsuz cümlede 'isn't few' denmez.", "several": "Çoğul sayılabilenler içindir."}),
    ("The team has ___ meetings scheduled for this afternoon.", "no", ["none", "much", "any of"],
     "'No + noun' expresses absence of meetings.", "'No + isim' meetings ile doğrudan birleşerek hiç toplantı olmadığını belirtir.",
     {"none": "İsimden önce tek başına 'none meetings' denmez, zamirdir.", "much": "Çoğul 'meetings' ile 'much' kullanılamaz.", "any of": "Olumlu cümlede eksik ifadedir."}),
    ("Can I get a ___ water while we wait for the client to arrive?", "glass of", ["many", "few", "several"],
     "Partitive 'a glass of' counts uncountable water.", "Sayılamayan suyu ölçülebilir kılan parça zarfı 'a glass of'tur.",
     {"many": "'Many water' İngilizcede kural hatasıdır.", "few": "Sayılamayanla 'few' denmez.", "several": "'Several water' denemez."}),
    ("She has ___ experience in mobile application development.", "a lot of", ["many", "few", "several"],
     "'Experience' (knowledge/skill) is uncountable.", "Mesleki deneyim anlamındaki 'experience' sayılamaz ('a lot of experience').",
     {"many": "'Many experiences' yaşantılar demektir, mesleki deneyim için sayılamazdır.", "few": "Mesleki tecrübede sayılan gibi kullanılmaz.", "several": "Çoğul sayılanlar içindir."}),
    ("There are ___ software defects that need immediate attention.", "some", ["much", "a little", "any in"],
     "Affirmative statement with plural countable takes 'some'.", "Olumlu cümlede çoğul sayılabilen isim 'some' alır.",
     {"much": "Çoğul sayılabilenle 'much' kullanılmaz.", "a little": "Sayılamayan tekiller içindir.", "any in": "Anlamsız bağlaçtır."}),
    ("How ___ money was allocated for the marketing campaign?", "much", ["many", "few", "several"],
     "'Money' is uncountable; requires 'how much'.", "'Money' sayılamayan bir isimdir; 'how much' ile sorulur.",
     {"many": "Sayılabilen çoğullar içindir ('currencies/coins').", "few": "Soru oluşturmaz.", "several": "Soru kalıbı değildir."}),
    ("We have very ___ time left before the code freeze deadline.", "little", ["few", "many", "several"],
     "'Time' (duration) is uncountable; 'very little time' expresses scarcity.", "Süre anlamındaki 'time' sayılamaz; 'very little time' azlığı belirtir.",
     {"few": "Sayılabilen çoğullar içindir.", "many": "Sayılamayanla kullanılmaz.", "several": "Çoğul sayılanlar içindir."}),
    ("Are there ___ free conference rooms on the fourth floor?", "any", ["much", "a little", "little"],
     "Plural countable in interrogative sentences takes 'any'.", "Soru cümlelerinde çoğul sayılabilen isimler 'any' alır.",
     {"much": "Çoğul 'rooms' ile uyumsuzdur.", "a little": "Sayılamayanlar içindir.", "little": "Olumsuz sayılamayan sıfatıdır."})
], "Choose the correct quantifier (much, many, few, little, some, any):", "İsmin sayılabilir çoğul mu yoksa sayılamayan mı olduğuna dikkat ediniz.")

# 8. Basic Defining Relative Clauses (Who, Which, That)
add_lesson("grammar.a2.defining-relative-clauses-basics", "rel-clauses", [
    ("The software engineer ___ designed the database architecture received an award.", "who", ["which", "where", "whose of"],
     "'Who' refers to people ('the software engineer').", "'Who' insan niteleyen tanımlayıcı sıfat cümleciklerinde kullanılır.",
     {"which": "Cansız varlıklar ve hayvanlar için kullanılır.", "where": "Mekan ve yer nitelemek içindir.", "whose of": "Hatalı yapıdır."}),
    ("This is the mobile application ___ won the annual design competition.", "which", ["who", "whom", "where"],
     "'Which' refers to things and applications ('the application').", "'Which' nesneleri ve yazılımları nitelemek için kullanılır.",
     {"who": "Yalnızca insan özneler için kullanılır.", "whom": "İnsan nesne zamiridir.", "where": "Yer bildirir."}),
    ("The office building ___ our team works is located near Levent.", "where", ["which", "who", "that in"],
     "'Where' refers to a place in which an action happens.", "'Where' içinde bir eylemin gerçekleştiği mekanları niteler.",
     {"which": "Edat olmadan ('in which' demeden) yer nitelemesinde 'where' kullanılır.", "who": "İnsanlar içindir.", "that in": "Sözdizimi hatasıdır."}),
    ("I spoke to the customer ___ reported the authentication bug yesterday.", "who", ["which", "where", "whose of"],
     "'Customer' is a person, requiring 'who' or 'that'.", "'Customer' bir insan olduğu için 'who' gerektirir.",
     {"which": "İnsanlar için 'which' kullanılamaz.", "where": "Yer bildirir.", "whose of": "Hatalıdır."}),
    ("Here is the configuration file ___ was missing from the deployment directory.", "that", ["who", "whom", "where"],
     "'That' can refer to inanimate objects ('the configuration file').", "'That' cansız nesneleri niteleyen tanımlayıcı cümleciklerde kullanılır.",
     {"who": "Cansız dosyalar için 'who' kullanılamaz.", "whom": "İnsanlar için nesne zamiridir.", "where": "Yer bildirir."}),
    ("The developer ___ laptop battery died had to present from the phone.", "whose", ["who", "which", "whom"],
     "'Whose' expresses possession ('the developer's laptop').", "'Whose' iyelik ve aidiyet bildirir ('geliştiricinin dizüstü bilgisayarı').",
     {"who": "Özne zamiridir, arkasından doğrudan yalın isim alamaz.", "which": "İnsan iyeliklerinde kullanılmaz.", "whom": "Nesne zamiridir, iyelik bildirmez."}),
    ("The meeting room ___ we usually hold our retrospectives is currently booked.", "where", ["who", "whom", "whose"],
     "Refers to the location where an activity takes place ('where').", "Toplantının gerçekleştiği fiziksel odayı 'where' niteler.",
     {"who": "Oda bir insan değildir.", "whom": "İnsanlar içindir.", "whose": "İyelik bildirmez."}),
    ("The candidate ___ we interviewed on Tuesday had five years of Kotlin experience.", "whom", ["where", "which", "whose"],
     "Formal relative pronoun for human direct objects is 'whom' (or 'who').", "İnsan nesnelerini niteleyen resmi zamir 'whom'dur.",
     {"where": "Aday mekan değildir.", "which": "İnsanlar için 'which' denemez.", "whose": "İyelik bildiren isim takip etmemiştir."}),
    ("Is this the server ___ crashed during the morning peak traffic?", "that", ["who", "whom", "where"],
     "'That' can introduce defining relative clauses for inanimate things.", "'That' cansız nesneler için özne durumundaki sıfat cümleciklerini kurar.",
     {"who": "Sunucu bir insan değildir.", "whom": "İnsanlar içindir.", "where": "Özne olarak eylem yapan sunucuyu nitelemez."}),
    ("The doctor ___ treated the injured employee was very attentive.", "who", ["which", "where", "whose of"],
     "'Doctor' is a person requiring relative pronoun 'who'.", "'Doctor' insan olduğu için 'who' gerektirir.",
     {"which": "İnsanlar için kullanılmaz.", "where": "Mekan değildir.", "whose of": "Hatalı yapıdır."}),
    ("We ordered a new projector ___ supports 4K wireless streaming.", "which", ["who", "whom", "where"],
     "Refers to an electronic device ('the projector'), requiring 'which'.", "Elektronik cihazı nitelemek için 'which' kullanılır.",
     {"who": "Projeksiyon insan değildir.", "whom": "İnsanlar içindir.", "where": "Mekan değildir."}),
    ("The city ___ our headquarters is located has excellent public transit.", "where", ["who", "whom", "whose"],
     "Refers to the geographic location ('the city where...').", "Şehir mekanını nitelemek için 'where' kullanılır.",
     {"who": "İnsan değildir.", "whom": "İnsan nesneler içindir.", "whose": "İyelik takip etmemiştir."}),
    ("The manager ___ approves travel budgets is on vacation until Monday.", "who", ["which", "where", "whose of"],
     "'Manager' is a person acting as subject of the relative clause.", "'Manager' insan özne olup 'who' gerektirir.",
     {"which": "İnsanlar için kullanılmaz.", "where": "Mekan değildir.", "whose of": "Hatalıdır."}),
    ("The database table ___ stores customer credentials must be encrypted.", "that", ["who", "whom", "where"],
     "'That' correctly refers to the database table.", "Veritabanı tablosu nesne olup 'that' ile nitelenir.",
     {"who": "Tablo insan değildir.", "whom": "İnsan nesnesi değildir.", "where": "Özne durumundadır, mekan değildir."}),
    ("The colleague ___ desk is next to mine always brings fresh pastries.", "whose", ["who", "which", "whom"],
     "Expresses possession ('the colleague's desk').", "'Whose' meslektaşın masasını niteleyen iyelik yapısıdır.",
     {"who": "Yalın isim 'desk' önüne iyelik olmadan 'who' gelemez.", "which": "İnsanlar için kullanılmaz.", "whom": "İyelik bildirmez."}),
    ("This is the exact coffee shop ___ our founders wrote the first line of code.", "where", ["who", "which of", "whom"],
     "Specifies the location of an event ('the coffee shop where...').", "Kodun yazıldığı mekanı niteleyen ifade 'where'dir.",
     {"who": "Kafe insan değildir.", "which of": "Hatalı yapıdır.", "whom": "İnsanlar içindir."}),
    ("The technician ___ repaired our fiber optic cable was very skilled.", "who", ["which", "where", "whose of"],
     "'Technician' is a person performing the action.", "'Technician' insan olup 'who' gerektirir.",
     {"which": "İnsanlar için 'which' denmez.", "where": "Mekan değildir.", "whose of": "Hatalıdır."}),
    ("She showed me the error log ___ caused the system restart.", "which", ["who", "whom", "where"],
     "Refers to an inanimate error log file ('which').", "Hata günlüğü cansız bir nesne olup 'which' alır.",
     {"who": "İnsan değildir.", "whom": "İnsanlar içindir.", "where": "Mekan bildirmez."}),
    ("The intern ___ solved the algorithmic riddle received a gift voucher.", "who", ["which", "where", "whose of"],
     "'Intern' is a person, requiring 'who'.", "'Intern' insan özne olup 'who' gerektirir.",
     {"which": "İnsan için kullanılamaz.", "where": "Mekan değildir.", "whose of": "Hatalıdır."}),
    ("The backup script ___ runs every midnight saves data to the cloud.", "that", ["who", "whom", "where"],
     "'That' refers to the automated software script.", "Otomasyon komut dosyasını nitelemek için 'that' kullanılır.",
     {"who": "Komut dosyası insan değildir.", "whom": "İnsanlar içindir.", "where": "Mekan bildirmez."})
], "Choose the correct relative pronoun (who, which, that, where, whose):", "İnsan, nesne, mekan ve iyelik ayrımlarına dikkat ediniz.")

# 9. Zero Conditional: General Truths and Realities
add_lesson("grammar.a2.zero-conditional-general-truths", "zero-cond", [
    ("If you ___ water to one hundred degrees, it boils.", "heat", ["heats", "heated", "will heat"],
     "Zero conditional uses Present Simple in both clauses ('If you heat... it boils').", "Zero conditional her iki cümlecikte de Present Simple gerektirir.",
     {"heats": "'You' öznesi fiile '-s' almaz.", "heated": "Genel gerçekler geçmiş zamanla kurulmaz.", "will heat": "'If' yan cümleciğinde 'will' kullanılmaz."}),
    ("If the server temperature exceeds eighty degrees, the emergency fans ___ automatically.", "activate", ["activates", "will activate", "activated"],
     "Plural subject 'emergency fans' takes base verb in zero conditional.", "Zero conditional temel cümlesinde çoğul özne 'fans' yalın fiil alır.",
     {"activates": "Çoğul özne 'fans' '-s' alamaz.", "will activate": "First conditional oluşturur; genel otomatik doğa/sistem kurallarında Present Simple esastır.", "activated": "Geçmiş zaman kurala uymaz."}),
    ("If an employee ___ late three times, HR sends a reminder email.", "arrives", ["arrive", "will arrive", "arrived"],
     "Third-person singular 'an employee' takes '-s' in the if-clause.", "'An employee' tekil öznesi if cümleciğinde Present Simple '-s' alır.",
     {"arrive": "Tekil özne yalın fiil alamaz.", "will arrive": "'If' cümleciğinde 'will' kullanılmaz.", "arrived": "Genel şirket kuralında geçmiş zaman yanlıştır."}),
    ("When you press the power button for five seconds, the device ___ immediately.", "reboots", ["reboot", "will reboot", "rebooted"],
     "System functional rule takes Present Simple in both clauses.", "Donanım işleyiş kuralları her iki tarafta Present Simple alır.",
     {"reboot": "Tekil 'the device' öznesi '-s' gerektirir.", "will reboot": "Otomatik donanım kuralında Present Simple standarttır.", "rebooted": "Geçmiş zaman kural bildirmez."}),
    ("If you don't save your changes, the editor ___ your unsaved progress.", "discards", ["discard", "will discard", "discarded"],
     "Zero conditional software rule takes Present Simple with 3rd-person '-s'.", "Yazılım davranışı kuralı Present Simple ve tekil '-s' gerektirir.",
     {"discard": "Tekil 'editor' öznesi '-s' almalıdır.", "will discard": "Genel değişmez yazılım kuralında Present Simple esastır.", "discarded": "Geçmiş zaman yanlıştır."}),
    ("Plants die if they ___ not get enough sunlight and water.", "do", ["does", "will", "did"],
     "Plural subject 'they' takes 'do not' in the negative if-clause.", "Çoğul 'they' öznesi olumsuz geniş zaman cümlesinde 'do not' alır.",
     {"does": "Çoğul özneyle 'does' kullanılmaz.", "will": "'If' yan cümleciğinde 'will' yer almaz.", "did": "Doğa kanunu geçmiş zamanla verilmez."}),
    ("If you enter the wrong password three times, the account ___ automatically.", "locks", ["lock", "will lock", "locked"],
     "Standard system security behavior takes Present Simple.", "Otomatik güvenlik davranışları Present Simple alır.",
     {"lock": "Tekil 'the account' öznesi '-s' gerektirir.", "will lock": "Otomatik kuralda Present Simple tercih edilir.", "locked": "Geçmiş zaman kuralı yansıtmaz."}),
    ("Ice melts if you ___ it in warm room temperature.", "leave", ["leaves", "will leave", "left"],
     "Scientific physical fact requires Present Simple in the condition clause.", "Fiziksel doğa gerçeği if cümleciğinde Present Simple yalın fiil alır.",
     {"leaves": "'You' öznesi '-s' almaz.", "will leave": "'If' yan cümlesinde 'will' kullanılamaz.", "left": "Geçmiş zaman genel gerçeğe uymaz."}),
    ("When the build pipeline fails, our chat bot ___ an alert message to Slack.", "sends", ["send", "will send", "sent"],
     "Automated technical workflow takes Present Simple in both clauses.", "Otomatik teknik akış her iki tarafta Present Simple alır.",
     {"send": "Tekil bot öznesi '-s' almalıdır.", "will send": "Sistemik her zamanki kuralda Present Simple esastır.", "sent": "Geçmiş zaman yanlıştır."}),
    ("If you ___ red and blue light, you get magenta.", "mix", ["mixes", "will mix", "mixed"],
     "Physics of light fact takes Present Simple.", "Işık fiziği kuralı if cümleciğinde Present Simple yalın fiil alır.",
     {"mixes": "'You' öznesi '-s' almaz.", "will mix": "'If' cümlesinde 'will' kullanılmaz.", "mixed": "Geçmiş zaman doğa kuralını bozamaz."}),
    ("When the battery charge drops below ten percent, the smartphone ___ power-saving mode.", "enables", ["enable", "will enable", "enabled"],
     "Hardware rule takes Present Simple with 3rd-person singular '-s'.", "Donanım kuralı Present Simple ve tekil '-s' gerektirir.",
     {"enable": "Tekil akıllı telefon öznesi '-s' almalıdır.", "will enable": "Otomatik sistem kuralında Present Simple esastır.", "enabled": "Geçmiş zaman yanlıştır."}),
    ("If an employee has a fever, they ___ at home to rest.", "stay", ["stays", "will stay", "stayed"],
     "Company health guideline takes Present Simple.", "Kurumsal sağlık kuralı Present Simple çoğul fiil alır.",
     {"stays": "Çoğul 'they' öznesi '-s' alamaz.", "will stay": "Genel kuralda Present Simple tercih edilir.", "stayed": "Geçmiş zaman kural bildirmez."}),
    ("Butter melts if you ___ it in a hot frying pan.", "put", ["puts", "will put", "putted"],
     "General cooking fact requires Present Simple.", "Genel gerçeklik if cümleciğinde Present Simple alır.",
     {"puts": "'You' öznesi '-s' almaz.", "will put": "'If' yan cümlesinde 'will' yer almaz.", "putted": "İngilizcede böyle bir form yoktur, 'put' düzensizdir."}),
    ("When users click the submit button twice, the server ___ duplicate requests.", "rejects", ["reject", "will reject", "rejected"],
     "API validation rule takes Present Simple with 3rd-person singular '-s'.", "API doğrulama kuralı Present Simple ve tekil '-s' gerektirir.",
     {"reject": "Tekil sunucu öznesi '-s' almalıdır.", "will reject": "Deterministik kuralda Present Simple esastır.", "rejected": "Geçmiş zaman yanlıştır."}),
    ("If you disconnect the USB drive during file transfer, data ___ corrupted.", "becomes", ["become", "will become", "became"],
     "Technical consequence takes Present Simple.", "Teknik sonuç Present Simple ve tekil '-s' alır.",
     {"become": "Sayılamayan tekil 'data' öznesi '-s' gerektirir.", "will become": "Genel doğrudan kuralda Present Simple esastır.", "became": "Geçmiş zaman kural bildirmez."}),
    ("When you hover your mouse over the icon, a helpful tooltip ___ on the screen.", "appears", ["appear", "will appear", "appeared"],
     "UI interaction behavior takes Present Simple.", "Kullanıcı arayüzü davranışı her iki tarafta Present Simple alır.",
     {"appear": "Tekil ipucu öznesi '-s' almalıdır.", "will appear": "Deterministik UI kuralında Present Simple kullanılır.", "appeared": "Geçmiş zaman yanlıştır."}),
    ("If people ___ not exercise regularly, their physical health deteriorates.", "do", ["does", "will", "did"],
     "Plural subject 'people' takes 'do not' in the negative condition clause.", "Çoğul 'people' öznesi geniş zaman olumsuzda 'do not' alır.",
     {"does": "Çoğul özneyle 'does' kullanılmaz.", "will": "'If' yan cümlesinde 'will' kullanılamaz.", "did": "Genel sağlık gerçeğinde geçmiş zaman yanlıştır."}),
    ("When the alarm sounds, all elevators ___ down to the ground floor.", "travel", ["travels", "will travel", "traveled"],
     "Safety fire protocol takes Present Simple with plural subject.", "Yangın güvenlik protokolü çoğul özneyle Present Simple yalın fiil alır.",
     {"travels": "Çoğul asansörler öznesi '-s' alamaz.", "will travel": "Deterministik güvenlik kuralında Present Simple esastır.", "traveled": "Geçmiş zaman kural bildirmez."}),
    ("If metal gets extremely hot, it ___ in volume.", "expands", ["expand", "will expand", "expanded"],
     "Scientific thermal physics law takes Present Simple.", "Termal genleşme doğa kanunu Present Simple ve tekil '-s' gerektirir.",
     {"expand": "Tekil 'it' öznesi '-s' almalıdır.", "will expand": "Doğa kanunlarında Present Simple esastır.", "expanded": "Geçmiş zaman yanlıştır."}),
    ("When you press Control plus Z in the editor, it ___ your last action.", "undoes", ["undo", "will undo", "undid"],
     "Keyboard shortcut functionality takes Present Simple with 3rd-person singular '-es'.", "Klavye kısayolu kuralı Present Simple ve tekil '-es' ('undoes') gerektirir.",
     {"undo": "Tekil 'it' öznesi '-es' almalıdır.", "will undo": "Standart kısayol kuralında Present Simple kullanılır.", "undid": "Geçmiş zaman yanlıştır."})
], "Complete the zero conditional sentence (general truths / facts):", "Her iki cümlecikte de geniş zaman (Present Simple) kullanılması kuralına dikkat ediniz.")

# 10. Prepositions of Time and Place (In, On, At)
add_lesson("grammar.a2.prepositions-time-place", "prep-time-place", [
    ("Our sprint planning meeting starts ___ nine o'clock sharp.", "at", ["in", "on", "to"],
     "Precise clock times require the preposition 'at'.", "Kesin saatler 'at' edatı gerektirir ('at nine o'clock').",
     {"in": "Aylar ve yıllar için kullanılır, saatlerle kullanılmaz.", "on": "Günler ve tarihler içindir.", "to": "Saat belirtmede başlangıç edatı değildir."}),
    ("The company was founded ___ 2018 in a small garage.", "in", ["at", "on", "by"],
     "Years and centuries require the preposition 'in'.", "Yıllar ve yüzyıllar 'in' edatı gerektirir ('in 2018').",
     {"at": "Saatler ve özel bayramlar içindir.", "on": "Belirli günler içindir.", "by": "Süreç bitişi anlatır, kuruluş yılı belirtmez."}),
    ("We always have our weekly retrospective ___ Friday afternoons.", "on", ["in", "at", "during"],
     "Specific days and day parts require the preposition 'on'.", "Belirli günler ve gün bölümleri 'on' edatı alır ('on Friday afternoons').",
     {"in": "Sadece 'in the afternoon' denir; gün adı girdiğinde 'on' kullanılır.", "at": "Saatler içindir.", "during": "Burada doğrudan gün adının önüne gelmez."}),
    ("The primary database servers are located ___ Frankfurt.", "in", ["at", "on", "to"],
     "Cities and countries require the preposition 'in'.", "Şehirler ve ülkeler 'in' edatı gerektirir ('in Frankfurt').",
     {"at": "Belirli nokta ve kurumlar içindir, koca şehirler için 'in' kullanılır.", "on": "Yüzeyler ve sokaklar içindir.", "to": "Yönelme bildirir, konum belirtmez."}),
    ("Please place the delivery boxes ___ the table in the conference room.", "on", ["in", "at", "under to"],
     "Surfaces take the preposition 'on'.", "Masa yüzeyleri 'on' edatı gerektirir ('on the table').",
     {"in": "Masa içine koymak anlamsızdır.", "at": "Yüzey üzerine koyma eyleminde 'on' esastır.", "under to": "Hatalı birleşik edattır."}),
    ("The CEO is currently ___ London attending a European technology summit.", "in", ["at", "on", "into"],
     "Cities take the preposition 'in'.", "Şehir içinde bulunma durumu 'in London' gerektirir.",
     {"at": "Şehir genelinde bulunmada 'in' standarttır.", "on": "Yüzeyler içindir.", "into": "Hareket ve giriş bildirir, statik konum değildir."}),
    ("Our annual company summit takes place ___ September every year.", "in", ["at", "on", "by"],
     "Months take the preposition 'in'.", "Aylar 'in' edatı gerektirir ('in September').",
     {"at": "Saatler içindir.", "on": "Tam tarih veya gün olsaydı 'on' olurdu; sadece ay adı 'in' alır.", "by": "Tarihe kadar demektir, ay içi olayı anlatmaz."}),
    ("The engineer is sitting ___ his desk writing automated tests.", "at", ["in", "on", "onto"],
     "Working position at a workstation requires 'at his desk'.", "Masa başında çalışma pozisyonu 'at his desk' kalıbıdır.",
     {"in": "Masanın içinde oturulmaz.", "on": "Masanın üstüne oturmak profesyonel çalışma pozisyonu değildir.", "onto": "Üzerine hareket bildirir."}),
    ("The mobile application was launched ___ July 15th, 2023.", "on", ["in", "at", "during"],
     "Specific calendar dates require the preposition 'on'.", "Tam takvim tarihleri 'on' edatı gerektirir ('on July 15th').",
     {"in": "Sadece ay olsaydı 'in' olurdu, gün numarası girdiğinde 'on' kullanılır.", "at": "Saatler içindir.", "during": "Tarih önünde doğrudan gelmez."}),
    ("I will meet you ___ the cafeteria entrance at noon.", "at", ["in", "on", "onto"],
     "Specific points in space take 'at' ('at the entrance').", "Belirli buluşma noktaları 'at' alır ('at the entrance').",
     {"in": "Giriş kapısının içinde değil noktasında buluşulur.", "on": "Yüzeyler içindir.", "onto": "Hareket bildirir."}),
    ("The morning keynote presentation begins ___ half past ten.", "at", ["in", "on", "to"],
     "Clock times take 'at'.", "Saat ifadeleri 'at' edatı alır ('at half past ten').",
     {"in": "Saatlerle kullanılmaz.", "on": "Günler içindir.", "to": "Saat belirtmede başlangıç edatı değildir."}),
    ("The product catalog is displayed ___ the company website.", "on", ["in", "at", "into"],
     "Websites, screens, and digital platforms take 'on'.", "İnternet siteleri ve ekranlar 'on' edatı alır ('on the website').",
     {"in": "Web sitesi yüzey kabul edilir, 'in' kullanılmaz.", "at": "E-posta adreslerinde kullanılır, web sayfası için 'on'dur.", "into": "İçine giriş bildirir."}),
    ("The team usually rests ___ the weekend.", "at", ["in", "to", "onto"],
     "British English standardly uses 'at the weekend' (US: on the weekend).", "İngiliz İngilizcesinde 'at the weekend' kalıbı esastır.",
     {"in": "Hafta sonu için 'in the weekend' denmez.", "to": "Yönelmedir.", "onto": "Yüzeye harekettir."}),
    ("All company offices are closed ___ New Year's Day.", "on", ["in", "at", "by"],
     "Specific holiday days containing 'Day' take 'on'.", "Sonunda 'Day' olan belirli tatil günleri 'on' alır ('on New Year's Day').",
     {"in": "Gün adıyla 'in' kullanılmaz.", "at": "Sadece 'at New Year' (dönem) denirse 'at' olur; 'Day' varsa 'on' kullanılır.", "by": "Tarihe kadar demektir."}),
    ("There is a white noticeboard ___ the wall of the conference room.", "on", ["in", "at", "into"],
     "Vertical wall surfaces take 'on the wall'.", "Duvar yüzeyleri 'on' edatı alır ('on the wall').",
     {"in": "Duvarın içinde değil yüzeyindedir.", "at": "Yüzey temasında 'on' kullanılır.", "into": "İçine yönelmedir."}),
    ("The software development department is located ___ the third floor.", "on", ["in", "at", "under to"],
     "Building floor levels require 'on the third floor'.", "Bina kat seviyeleri 'on' edatı alır ('on the third floor').",
     {"in": "Katlar için 'in' denmez.", "at": "Belirli kat düzeyinde 'on' standarttır.", "under to": "Hatalı birleşik edattır."}),
    ("I always wake up early ___ the morning to read technical blogs.", "in", ["at", "on", "by"],
     "Standard time periods of the day take 'in the morning'.", "Günün standart bölümleri 'in' edatı alır ('in the morning').",
     {"at": "'At night' istisnadır ancak 'morning' için 'in' zorunludur.", "on": "Sadece gün adı girdiğinde ('on Monday morning') kullanılır.", "by": "Kalıba uymaz."}),
    ("The IT support specialist will arrive ___ ten minutes.", "in", ["at", "on", "by to"],
     "'In ten minutes' expresses future time duration ('ten minutes from now').", "'In ten minutes', on dakika sonra anlamında geleceğe yönelik süre belirtir.",
     {"at": "Saat noktası değildir, süre aralığıdır.", "on": "Dakikalarla kullanılmaz.", "by to": "Hatalı yapıdır."}),
    ("She keeps her backup memory drives ___ the bottom desk drawer.", "in", ["on", "at", "onto"],
     "Enclosed three-dimensional spaces (drawers, boxes) take 'in'.", "Çekmece ve kutu gibi kapalı üç boyutlu alanlar 'in' alır ('in the drawer').",
     {"on": "Çekmecenin üstünde değil içindedir.", "at": "Nokta değil kapalı hacimdir.", "onto": "Üzerine harekettir."}),
    ("The emergency power generator is located ___ the basement.", "in", ["on", "at", "onto"],
     "Basements and rooms take the preposition 'in'.", "Bodrum kat ve odalar hacim bildirdiği için 'in' alır ('in the basement').",
     {"on": "Bodrum kat bir hacimdir, yüzey değildir.", "at": "Belirli oda ve mekanlarda 'in' esastır.", "onto": "Hareket bildirir."})
], "Choose the correct preposition of time or place (in, on, at):", "Saat (at), gün/tarih/yüzey (on) ve ay/yıl/şehir/hacim (in) kurallarına dikkat ediniz.")

if __name__ == "__main__":
    print(f"Generated {len(A2_EXERCISES)} A2 grammar exercises across 10 lessons.")
